# ==============================================================================
# 02_descriptive_analysis.R
# ==============================================================================
#
# Project:
#   Pediatric appendicitis plasma miRNA-seq
#
# Script:
#   02_descriptive_analysis.R
#
# Purpose:
#   Perform descriptive and exploratory quality-control analyses on the final
#   cohort and the complete set of miRNAs retained by the prespecified
#   abundance/prevalence filter.
#
# Role in pipeline:
#   Global expression QC and exploratory descriptive analysis.
#
#   This script:
#     - validates the filtered RPM objects generated by script 01;
#     - performs PCA using all filtered miRNAs;
#     - quantifies variance explained by principal components;
#     - generates global PCA plots;
#     - evaluates non-destructive sample-level QC/outlier metrics;
#     - evaluates an exploratory sequencing-based hemolysis proxy;
#     - formally tests the hemolysis proxy across the three clinical groups;
#     - evaluates associations between PCs and biological/technical covariates;
#     - generates a fully unsupervised global heatmap;
#     - records clustering order and exploratory sample clusters;
#     - generates global-expression QC figures suitable for supplementary use.
#
# Important manuscript distinction:
#   The PCA and heatmap generated here use ALL miRNAs retained after the
#   prespecified expression filter.
#
#   They are global-expression QC / supplementary analyses.
#
#   No downstream differential-expression result or candidate prioritization
#   is used to construct these analyses.
#
# Statistical principles:
#   - PCA:
#       log2(RPM + 1), feature-centered and feature-scaled.
#
#   - PCA is exploratory/descriptive.
#
#   - No sample is automatically removed because of PCA position,
#     dendrogram position or QC flags.
#
#   - Sample QC:
#       robust z-scores based on median absolute deviation (MAD).
#
#   - Hemolysis:
#       exploratory sequencing-based proxy:
#
#         log2(miR-451a RPM + 1) -
#         log2(miR-23a-3p RPM + 1)
#
#       qPCR-specific delta-Cq thresholds are not applied.
#
#   - Hemolysis phenotype comparison:
#       Kruskal-Wallis test across Apend_type groups.
#
#   - PC/covariate associations:
#       continuous variables -> Spearman correlation
#       categorical variables -> Kruskal-Wallis test
#
#       Benjamini-Hochberg FDR is calculated across the complete PC/covariate
#       association audit.
#
# Inputs:
#   results/<analysis_id>/filtered_RPM.rds
#   results/<analysis_id>/RPM_counts_all_miRNAs.rds
#   results/<analysis_id>/metadata_analysis_samples.rds
#   results/<analysis_id>/Metrics_analysis_samples.rds
#
# Main outputs:
#   PCA_sample_coordinates.csv
#   PCA_variance_explained.csv
#   PCA_variance_summary.csv
#
#   outlier_evaluation_summary.csv
#
#   hemolysis_proxy.csv
#   hemolysis_phenotype_test.csv
#
#   PC_covariate_associations.csv
#   batch_audit_status.csv
#
#   global_heatmap_feature_manifest.csv
#   global_heatmap_miRNA_cluster_order.csv
#   global_heatmap_sample_cluster_order.csv
#   global_heatmap_sample_clusters_k3.csv
#   global_heatmap_cluster_vs_phenotype.csv
#
#   descriptive_stats.csv
#   02_final_QC_summary.csv
#
# Figures:
#   figures/<analysis_id>/PCA/
#   figures/<analysis_id>/heatmaps/
#   figures/<analysis_id>/outlier_assessment/
#   figures/<analysis_id>/hemolysis/
#   figures/<analysis_id>/global_expression/
#
# Reproducibility:
#   All analyses operate on the exact cohort, feature set and canonical clinical
#   labels generated by script 01. This script never changes cohort membership,
#   feature inclusion or clinical-group definitions.
#
# ==============================================================================


# ==============================================================================
# 1. DEPENDENCIES
# ==============================================================================

required_packages <- c(
  "here",
  "dplyr",
  "tidyr",
  "ggplot2",
  "ggrepel",
  "pheatmap"
)


missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]


if (length(missing_packages) > 0L) {
  
  stop(
    "Missing package(s) required by R/02_descriptive_analysis.R:\n",
    paste(
      "-",
      missing_packages,
      collapse = "\n"
    ),
    "\nRun R/00_packages_setup.R first.",
    call. = FALSE
  )
}


source(
  here::here(
    "R",
    "00_analysis_config.R"
  )
)


source(
  here::here(
    "R",
    "00_utils.R"
  )
)


# ==============================================================================
# 2. CONFIGURATION
# ==============================================================================

context <- get_analysis_context()


results_dir <- context$results_dir

figures_dir <- context$figures_dir


pca_dir <- file.path(
  figures_dir,
  "PCA"
)

heatmap_dir <- file.path(
  figures_dir,
  "heatmaps"
)

outlier_dir <- file.path(
  figures_dir,
  "outlier_assessment"
)

hemolysis_dir <- file.path(
  figures_dir,
  "hemolysis"
)

global_expression_dir <- file.path(
  figures_dir,
  "global_expression"
)


for (directory in c(
  pca_dir,
  heatmap_dir,
  outlier_dir,
  hemolysis_dir,
  global_expression_dir
)) {
  
  ensure_dir(
    directory
  )
}


message(
  "\n============================================================"
)

message(
  "02_descriptive_analysis.R"
)

message(
  "Analysis ID: ",
  context$analysis_id
)

message(
  "Role: ",
  context$role
)

message(
  "============================================================\n"
)


# ==============================================================================
# 3. INPUTS
# ==============================================================================

required_files <- c(
  
  filtered_RPM = file.path(
    results_dir,
    "filtered_RPM.rds"
  ),
  
  RPM_all = file.path(
    results_dir,
    "RPM_counts_all_miRNAs.rds"
  ),
  
  metadata = file.path(
    results_dir,
    "metadata_analysis_samples.rds"
  ),
  
  Metrics = file.path(
    results_dir,
    "Metrics_analysis_samples.rds"
  )
)


missing_files <- required_files[
  !file.exists(required_files)
]


if (length(missing_files) > 0L) {
  
  stop(
    "Run R/01_data_loading_and_filtering.R first. Missing file(s):\n",
    paste(
      "-",
      missing_files,
      collapse = "\n"
    ),
    call. = FALSE
  )
}


rpm <- readRDS(
  required_files[["filtered_RPM"]]
)


rpm_all <- readRDS(
  required_files[["RPM_all"]]
)


metadata <- as.data.frame(
  readRDS(
    required_files[["metadata"]]
  ),
  stringsAsFactors = FALSE
)


Metrics <- as.data.frame(
  readRDS(
    required_files[["Metrics"]]
  ),
  stringsAsFactors = FALSE
)


rpm <- as.matrix(
  rpm
)

rpm_all <- as.matrix(
  rpm_all
)


storage.mode(rpm) <- "numeric"

storage.mode(rpm_all) <- "numeric"


# ==============================================================================
# 4. VALIDATION
# ==============================================================================

# ==============================================================================
# 4.1 Expression matrices
# ==============================================================================

for (
  object_name in c(
    "rpm",
    "rpm_all"
  )
) {
  
  expression_matrix <- get(
    object_name
  )
  
  
  if (
    nrow(expression_matrix) == 0L ||
    ncol(expression_matrix) == 0L
  ) {
    
    stop(
      object_name,
      " is empty.",
      call. = FALSE
    )
  }
  
  
  if (
    anyNA(expression_matrix) ||
    any(!is.finite(expression_matrix)) ||
    any(expression_matrix < 0)
  ) {
    
    stop(
      object_name,
      " contains invalid expression values.",
      call. = FALSE
    )
  }
  
  
  if (
    anyDuplicated(
      rownames(expression_matrix)
    ) > 0L ||
    anyDuplicated(
      colnames(expression_matrix)
    ) > 0L
  ) {
    
    stop(
      object_name,
      " contains duplicated feature or sample identifiers.",
      call. = FALSE
    )
  }
}


# Filtered miRNAs must be a strict subset or complete subset of the original
# normalized matrix.

missing_filtered_mirnas <- setdiff(
  rownames(rpm),
  rownames(rpm_all)
)


if (length(missing_filtered_mirnas) > 0L) {
  
  stop(
    "Filtered RPM matrix contains miRNAs absent from the complete RPM matrix: ",
    paste(
      missing_filtered_mirnas,
      collapse = ", "
    ),
    call. = FALSE
  )
}


# The selected samples must be identical.

if (!identical(
  colnames(rpm),
  colnames(rpm_all)
)) {
  
  stop(
    "Filtered and complete RPM matrices are not sample-aligned.",
    call. = FALSE
  )
}


# ==============================================================================
# 4.2 Metadata and metrics alignment
# ==============================================================================

metadata$Sample <- as.character(
  metadata$Sample
)


Metrics$Sample <- as.character(
  Metrics$Sample
)


metadata <- metadata[
  match(
    colnames(rpm),
    metadata$Sample
  ),
  ,
  drop = FALSE
]


Metrics <- Metrics[
  match(
    colnames(rpm),
    Metrics$Sample
  ),
  ,
  drop = FALSE
]


if (
  anyNA(metadata$Sample) ||
  anyNA(Metrics$Sample)
) {
  
  stop(
    "Metadata or metrics alignment produced missing sample IDs.",
    call. = FALSE
  )
}


if (!identical(
  metadata$Sample,
  colnames(rpm)
)) {
  
  stop(
    "Metadata and RPM matrix are not sample-aligned.",
    call. = FALSE
  )
}


if (!identical(
  Metrics$Sample,
  colnames(rpm)
)) {
  
  stop(
    "Metrics and RPM matrix are not sample-aligned.",
    call. = FALSE
  )
}


validate_selected_metadata(
  metadata
)


# ==============================================================================
# 4.3 Primary-cohort integrity
# ==============================================================================

if (
  nrow(metadata) == 0L ||
  ncol(rpm) == 0L
) {
  stop(
    "Selected cohort or filtered RPM matrix is empty.",
    call. = FALSE
  )
}


# ==============================================================================
# 4.4 Validate complete RPM normalization
# ==============================================================================

rpm_all_sums <- colSums(
  rpm_all
)


if (any(
  abs(
    rpm_all_sums -
    1e6
  ) > 1e-4
)) {
  
  stop(
    "Complete RPM matrix failed the 1,000,000 RPM column-sum check.",
    call. = FALSE
  )
}


message(
  "Input validation complete: ",
  ncol(rpm),
  " samples; ",
  nrow(rpm),
  " filtered miRNAs; ",
  nrow(rpm_all),
  " total quantified miRNAs."
)


# ==============================================================================
# 5. ANALYSIS / PROCESSING
# ==============================================================================

# ==============================================================================
# 5.1 Validate inherited clinical-group labels
# ==============================================================================

# Clinical display labels are created once in script 01 and inherited here.
#
# This script MUST NOT independently recode Apend_type or Condition.
#
# Canonical labels:

#   Phenotype:
#       NIA / Mild / Severe
#
#   Phenotype_full:
#       Non-inflamed appendix / Mild appendicitis / Severe appendicitis
#
#   Appendicitis_status:
#       NIA / Appendicitis
#
# NIA = non-inflamed appendix.
# The NIA group is not a healthy-control cohort.

required_clinical_label_columns <- c(
  "Phenotype",
  "Phenotype_full",
  "Appendicitis_status"
)


missing_clinical_label_columns <- setdiff(
  required_clinical_label_columns,
  colnames(
    metadata
  )
)


if (
  length(
    missing_clinical_label_columns
  ) > 0L
) {

  stop(
    "Metadata is missing canonical clinical-group column(s): ",
    paste(
      missing_clinical_label_columns,
      collapse = ", "
    ),
    ". Re-run R/01_data_loading_and_filtering.R with the updated clinical ",
    "label definitions before running script 02.",
    call. = FALSE
  )
}


metadata$Phenotype <- factor(
  as.character(
    metadata$Phenotype
  ),
  levels = c(
    "NIA",
    "Mild",
    "Severe"
  )
)


metadata$Phenotype_full <- factor(
  as.character(
    metadata$Phenotype_full
  ),
  levels = c(
    "Non-inflamed appendix",
    "Mild appendicitis",
    "Severe appendicitis"
  )
)


metadata$Appendicitis_status <- factor(
  as.character(
    metadata$Appendicitis_status
  ),
  levels = c(
    "NIA",
    "Appendicitis"
  )
)


if (
  anyNA(
    metadata$Phenotype
  ) ||
  anyNA(
    metadata$Phenotype_full
  ) ||
  anyNA(
    metadata$Appendicitis_status
  )
) {

  stop(
    "Canonical clinical-group labels contain missing or unexpected values.",
    call. = FALSE
  )
}


expected_phenotype_from_apend_type <- unname(
  c(
    "0" = "NIA",
    "1" = "Mild",
    "2" = "Severe"
  )[
    as.character(
      metadata$Apend_type
    )
  ]
)


expected_full_phenotype_from_apend_type <- unname(
  c(
    "0" = "Non-inflamed appendix",
    "1" = "Mild appendicitis",
    "2" = "Severe appendicitis"
  )[
    as.character(
      metadata$Apend_type
    )
  ]
)


expected_appendicitis_status <- ifelse(
  as.character(
    metadata$Apend_type
  ) == "0",
  "NIA",
  "Appendicitis"
)


if (
  !identical(
    as.character(
      metadata$Phenotype
    ),
    expected_phenotype_from_apend_type
  ) ||
  !identical(
    as.character(
      metadata$Phenotype_full
    ),
    expected_full_phenotype_from_apend_type
  ) ||
  !identical(
    as.character(
      metadata$Appendicitis_status
    ),
    expected_appendicitis_status
  )
) {

  stop(
    "Inherited clinical-group labels are inconsistent with Apend_type. ",
    "Re-run script 01 and inspect metadata_analysis_samples.rds.",
    call. = FALSE
  )
}


message(
  "Clinical labels validated: NIA / Mild / Severe."
)


# ==============================================================================
# 5.2 Global log2-RPM matrix
# ==============================================================================

# PCA and heatmap use the complete feature set retained by script 01.
#
# No DE result, p value or manuscript-candidate status is used here.

log_rpm <- safe_log2(
  rpm
)


feature_sd <- apply(
  log_rpm,
  1L,
  stats::sd
)


pca_features <- (
  is.finite(feature_sd) &
    feature_sd > 0
)


if (sum(
  pca_features
) < 2L) {
  
  stop(
    "Fewer than two variable miRNAs are available for PCA.",
    call. = FALSE
  )
}


# ==============================================================================
# 5.3 Global PCA
# ==============================================================================

pca_input <- t(
  log_rpm[
    pca_features,
    ,
    drop = FALSE
  ]
)


pca <- stats::prcomp(
  pca_input,
  center = TRUE,
  scale. = TRUE
)


variance <- (
  pca$sdev^2
) / sum(
  pca$sdev^2
)


variance_df <- data.frame(
  
  PC = paste0(
    "PC",
    seq_along(
      variance
    )
  ),
  
  variance_explained = variance,
  
  variance_explained_pct =
    100 * variance,
  
  cumulative_variance_explained =
    cumsum(
      variance
    ),
  
  cumulative_variance_explained_pct =
    100 * cumsum(
      variance
    ),
  
  stringsAsFactors = FALSE
)


n_pcs_to_store <- min(
  5L,
  ncol(
    pca$x
  )
)


pca_score_df <- as.data.frame(
  pca$x[
    ,
    seq_len(
      n_pcs_to_store
    ),
    drop = FALSE
  ]
)


pca_score_df$Sample <- rownames(
  pca$x
)


pca_df <- pca_score_df[
  ,
  c(
    "Sample",
    paste0(
      "PC",
      seq_len(
        n_pcs_to_store
      )
    )
  ),
  drop = FALSE
]


pca_df <- dplyr::left_join(
  pca_df,
  metadata,
  by = "Sample"
)


utils::write.csv(
  pca_df,
  prepare_output_file(
    file.path(
      results_dir,
      "PCA_sample_coordinates.csv"
    )
  ),
  row.names = FALSE
)


utils::write.csv(
  variance_df,
  prepare_output_file(
    file.path(
      results_dir,
      "PCA_variance_explained.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 5.4 PCA variance summary
# ==============================================================================

pc_number_for_threshold <- function(
    cumulative_pct,
    threshold
) {
  
  hit <- which(
    cumulative_pct >= threshold
  )
  
  
  if (length(
    hit
  ) == 0L) {
    
    return(
      NA_integer_
    )
  }
  
  
  hit[1L]
}


pca_variance_summary <- data.frame(
  
  analysis_id = context$analysis_id,
  
  n_filtered_miRNAs = nrow(
    rpm
  ),
  
  n_variable_PCA_features = sum(
    pca_features
  ),
  
  n_samples = ncol(
    rpm
  ),
  
  PC1_variance_pct =
    variance_df$variance_explained_pct[1L],
  
  PC2_variance_pct =
    variance_df$variance_explained_pct[2L],
  
  PC3_variance_pct = if (
    nrow(
      variance_df
    ) >= 3L
  ) {
    variance_df$variance_explained_pct[3L]
  } else {
    NA_real_
  },
  
  PC1_PC2_cumulative_pct = sum(
    variance_df$variance_explained_pct[
      seq_len(
        min(
          2L,
          nrow(
            variance_df
          )
        )
      )
    ]
  ),
  
  PC1_PC3_cumulative_pct = sum(
    variance_df$variance_explained_pct[
      seq_len(
        min(
          3L,
          nrow(
            variance_df
          )
        )
      )
    ]
  ),
  
  n_PCs_for_50pct = pc_number_for_threshold(
    variance_df$cumulative_variance_explained_pct,
    50
  ),
  
  n_PCs_for_80pct = pc_number_for_threshold(
    variance_df$cumulative_variance_explained_pct,
    80
  ),
  
  n_PCs_for_90pct = pc_number_for_threshold(
    variance_df$cumulative_variance_explained_pct,
    90
  ),
  
  stringsAsFactors = FALSE
)


utils::write.csv(
  pca_variance_summary,
  prepare_output_file(
    file.path(
      results_dir,
      "PCA_variance_summary.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 5.5 PCA variance plots
# ==============================================================================

n_pc_plot <- min(
  10L,
  nrow(
    variance_df
  )
)


variance_plot_df <- variance_df[
  seq_len(
    n_pc_plot
  ),
  ,
  drop = FALSE
]


variance_plot_df$PC <- factor(
  variance_plot_df$PC,
  levels = variance_plot_df$PC
)


p_scree <- ggplot2::ggplot(
  variance_plot_df,
  ggplot2::aes(
    x = PC,
    y = variance_explained_pct
  )
) +
  ggplot2::geom_col(
    width = 0.72
  ) +
  ggplot2::geom_text(
    ggplot2::aes(
      label = sprintf(
        "%.1f%%",
        variance_explained_pct
      )
    ),
    vjust = -0.35,
    size = 3
  ) +
  ggplot2::scale_y_continuous(
    expand = ggplot2::expansion(
      mult = c(
        0,
        0.12
      )
    )
  ) +
  ggplot2::labs(
    title = "Variance explained by principal components",
    x = "Principal component",
    y = "Variance explained (%)"
  ) +
  ggplot2::theme_classic(
    base_size = 10
  ) +
  ggplot2::theme(
    plot.title = ggplot2::element_text(
      face = "bold",
      size = 10
    ),
    axis.text.x = ggplot2::element_text(
      angle = 45,
      hjust = 1
    )
  )


save_ggplot_pdf(
  plot = p_scree,
  filename = file.path(
    pca_dir,
    "PCA_variance_scree_plot.pdf"
  ),
  width = 7,
  height = 4.5
)


save_ggplot_tiff(
  plot = p_scree,
  filename = file.path(
    pca_dir,
    "PCA_variance_scree_plot.tiff"
  ),
  width = 7,
  height = 4.5,
  dpi = 600
)


p_cumulative <- ggplot2::ggplot(
  variance_plot_df,
  ggplot2::aes(
    x = PC,
    y = cumulative_variance_explained_pct,
    group = 1
  )
) +
  ggplot2::geom_hline(
    yintercept = c(
      50,
      80,
      90
    ),
    linetype = "dashed",
    linewidth = 0.35
  ) +
  ggplot2::geom_line(
    linewidth = 0.7
  ) +
  ggplot2::geom_point(
    size = 2
  ) +
  ggplot2::scale_y_continuous(
    limits = c(
      0,
      100
    ),
    breaks = seq(
      0,
      100,
      by = 20
    )
  ) +
  ggplot2::labs(
    title = "Cumulative variance explained",
    x = "Principal component",
    y = "Cumulative variance explained (%)"
  ) +
  ggplot2::theme_classic(
    base_size = 10
  ) +
  ggplot2::theme(
    plot.title = ggplot2::element_text(
      face = "bold",
      size = 10
    ),
    axis.text.x = ggplot2::element_text(
      angle = 45,
      hjust = 1
    )
  )


save_ggplot_pdf(
  plot = p_cumulative,
  filename = file.path(
    pca_dir,
    "PCA_cumulative_variance.pdf"
  ),
  width = 7,
  height = 4.5
)


save_ggplot_tiff(
  plot = p_cumulative,
  filename = file.path(
    pca_dir,
    "PCA_cumulative_variance.tiff"
  ),
  width = 7,
  height = 4.5,
  dpi = 600
)


# ==============================================================================
# 5.6 Global PCA plotting helpers
# ==============================================================================

PCA_ELLIPSE_LEVEL <- 0.95


get_ellipse_data <- function(
    data,
    group_var,
    x_var,
    y_var,
    minimum_group_n = 3L
) {
  
  required_columns <- c(
    group_var,
    x_var,
    y_var
  )
  
  
  if (!all(
    required_columns %in%
    colnames(data)
  )) {
    
    return(
      data[
        0,
        ,
        drop = FALSE
      ]
    )
  }
  
  
  keep_complete <- stats::complete.cases(
    data[
      ,
      required_columns,
      drop = FALSE
    ]
  )
  
  
  ellipse_data <- data[
    keep_complete,
    ,
    drop = FALSE
  ]
  
  
  if (nrow(
    ellipse_data
  ) == 0L) {
    
    return(
      ellipse_data
    )
  }
  
  
  group_values <- as.character(
    ellipse_data[[group_var]]
  )
  
  
  group_counts <- table(
    group_values
  )
  
  
  eligible_groups <- names(
    group_counts[
      group_counts >= minimum_group_n
    ]
  )
  
  
  ellipse_data[
    group_values %in%
      eligible_groups,
    ,
    drop = FALSE
  ]
}


plot_global_pca <- function(
    group_var,
    filename,
    pc_x = 1L,
    pc_y = 2L,
    label_samples = FALSE,
    add_ellipses = TRUE,
    pdf_output = FALSE
) {
  
  if (!group_var %in%
      colnames(
        pca_df
      )) {
    
    return(
      invisible(NULL)
    )
  }
  
  
  x_name <- paste0(
    "PC",
    pc_x
  )
  
  y_name <- paste0(
    "PC",
    pc_y
  )
  
  
  if (!all(
    c(
      x_name,
      y_name
    ) %in%
    colnames(
      pca_df
    )
  )) {
    
    return(
      invisible(NULL)
    )
  }
  
  
  ellipse_data <- get_ellipse_data(
    data = pca_df,
    group_var = group_var,
    x_var = x_name,
    y_var = y_name
  )
  
  
  p <- ggplot2::ggplot(
    pca_df,
    ggplot2::aes(
      x = .data[[x_name]],
      y = .data[[y_name]],
      color = .data[[group_var]]
    )
  )
  
  
  if (
    isTRUE(
      add_ellipses
    ) &&
    nrow(
      ellipse_data
    ) > 0L
  ) {
    
    p <- p +
      ggplot2::stat_ellipse(
        data = ellipse_data,
        ggplot2::aes(
          fill = .data[[group_var]]
        ),
        geom = "polygon",
        type = "norm",
        level = PCA_ELLIPSE_LEVEL,
        alpha = 0.12,
        color = NA,
        show.legend = FALSE
      ) +
      ggplot2::stat_ellipse(
        data = ellipse_data,
        type = "norm",
        level = PCA_ELLIPSE_LEVEL,
        linewidth = 0.6,
        alpha = 0.85,
        show.legend = FALSE
      )
  }
  
  
  p <- p +
    ggplot2::geom_point(
      size = 3,
      alpha = 0.95
    ) +
    ggplot2::labs(
      title = paste(
        "Global PCA by",
        group_var
      ),
      subtitle = paste0(
        nrow(rpm),
        " filtered miRNAs"
      ),
      x = sprintf(
        "%s (%.1f%%)",
        x_name,
        100 * variance[pc_x]
      ),
      y = sprintf(
        "%s (%.1f%%)",
        y_name,
        100 * variance[pc_y]
      ),
      color = group_var
    ) +
    ggplot2::theme_classic(
      base_size = 11
    )
  
  
  if (isTRUE(
    label_samples
  )) {
    
    p <- p +
      ggrepel::geom_text_repel(
        ggplot2::aes(
          label = Sample
        ),
        size = 2.7,
        max.overlaps = Inf,
        show.legend = FALSE
      )
  }
  
  
  if (isTRUE(
    pdf_output
  )) {
    
    save_ggplot_pdf(
      plot = p,
      filename = file.path(
        pca_dir,
        filename
      ),
      width = 7,
      height = 5
    )
    
  } else {
    
    save_ggplot_png(
      plot = p,
      filename = file.path(
        pca_dir,
        filename
      ),
      width = 7.5,
      height = 6,
      dpi = 300
    )
  }
  
  
  invisible(
    p
  )
}


# Primary global QC view.

p_pca_global <- plot_global_pca(
  group_var = "Phenotype",
  filename = "PCA_global_filtered_miRNAs.pdf",
  pc_x = 1L,
  pc_y = 2L,
  label_samples = FALSE,
  add_ellipses = TRUE,
  pdf_output = TRUE
)


save_ggplot_tiff(
  plot = p_pca_global,
  filename = file.path(
    pca_dir,
    "PCA_global_filtered_miRNAs.tiff"
  ),
  width = 7,
  height = 5,
  dpi = 600
)


# Additional audit views.

plot_global_pca(
  "Appendicitis_status",
  "PCA_Appendicitis_status.png",
  1L,
  2L,
  TRUE,
  TRUE,
  FALSE
)


plot_global_pca(
  "Apend_type",
  "PCA_Apend_type.png",
  1L,
  2L,
  TRUE,
  TRUE,
  FALSE
)


plot_global_pca(
  "Phenotype",
  "PCA_Phenotype.png",
  1L,
  2L,
  FALSE,
  TRUE,
  FALSE
)


plot_global_pca(
  "Sex",
  "PCA_Sex.png",
  1L,
  2L,
  TRUE,
  TRUE,
  FALSE
)


plot_global_pca(
  "Phenotype",
  "PCA_Phenotype_PC1_PC3.png",
  1L,
  3L,
  FALSE,
  TRUE,
  FALSE
)


plot_global_pca(
  "Phenotype",
  "PCA_Phenotype_PC2_PC3.png",
  2L,
  3L,
  FALSE,
  TRUE,
  FALSE
)


if (
  !is.na(
    BATCH_COLUMN
  ) &&
  BATCH_COLUMN %in%
  colnames(
    pca_df
  )
) {
  
  plot_global_pca(
    BATCH_COLUMN,
    paste0(
      "PCA_",
      sanitize_filename(
        BATCH_COLUMN
      ),
      ".png"
    ),
    1L,
    2L,
    TRUE,
    TRUE,
    FALSE
  )
}


# ==============================================================================
# 5.7 Sample-level QC and non-destructive outlier flags
# ==============================================================================

robust_z <- function(x) {
  
  x <- as.numeric(
    x
  )
  
  
  med <- stats::median(
    x,
    na.rm = TRUE
  )
  
  
  mad_value <- stats::mad(
    x,
    center = med,
    constant = 1.4826,
    na.rm = TRUE
  )
  
  
  if (
    !is.finite(
      mad_value
    ) ||
    mad_value == 0
  ) {
    
    return(
      rep(
        0,
        length(
          x
        )
      )
    )
  }
  
  
  (
    x -
      med
  ) / mad_value
}


sample_qc <- data.frame(
  
  Sample = colnames(
    rpm_all
  ),
  
  library_size_miRNA_counts = as.numeric(
    Metrics$Reads
  ),
  
  detected_miRNAs = colSums(
    rpm_all > 0
  ),
  
  zero_fraction = colMeans(
    rpm_all == 0
  ),
  
  top1_fraction = vapply(
    seq_len(
      ncol(
        rpm_all
      )
    ),
    function(j) {
      
      sample_sum <- sum(
        rpm_all[
          ,
          j
        ]
      )
      
      
      if (
        !is.finite(
          sample_sum
        ) ||
        sample_sum <= 0
      ) {
        
        return(
          NA_real_
        )
      }
      
      
      max(
        rpm_all[
          ,
          j
        ]
      ) / sample_sum
    },
    numeric(1)
  ),
  
  stringsAsFactors = FALSE
)


sample_qc$log10_library_size <- log10(
  sample_qc$library_size_miRNA_counts
)


sample_qc$z_library_size <- robust_z(
  sample_qc$log10_library_size
)


sample_qc$z_detected_miRNAs <- robust_z(
  sample_qc$detected_miRNAs
)


sample_qc$z_zero_fraction <- robust_z(
  sample_qc$zero_fraction
)


sample_qc$z_top1_fraction <- robust_z(
  sample_qc$top1_fraction
)


sample_qc$flag_library_size <- abs(
  sample_qc$z_library_size
) > 3


sample_qc$flag_detected_miRNAs <- abs(
  sample_qc$z_detected_miRNAs
) > 3


sample_qc$flag_zero_fraction <- abs(
  sample_qc$z_zero_fraction
) > 3


sample_qc$flag_top1_fraction <- abs(
  sample_qc$z_top1_fraction
) > 3


flag_columns <- grep(
  "^flag_",
  names(
    sample_qc
  ),
  value = TRUE
)


sample_qc$n_flags <- rowSums(
  sample_qc[
    ,
    flag_columns,
    drop = FALSE
  ]
)


sample_qc$outlier_status <- ifelse(
  sample_qc$n_flags >= 2L,
  "MULTIPLE_FLAGS",
  ifelse(
    sample_qc$n_flags == 1L,
    "SINGLE_FLAG",
    "NO_FLAG"
  )
)


sample_qc <- dplyr::left_join(
  sample_qc,
  metadata[
    ,
    c(
      "Sample",
      "Apend_type",
      "Phenotype",
      "Phenotype_full",
      "Appendicitis_status",
      "Sex",
      "Age"
    ),
    drop = FALSE
  ],
  by = "Sample"
)


utils::write.csv(
  sample_qc,
  prepare_output_file(
    file.path(
      results_dir,
      "outlier_evaluation_summary.csv"
    )
  ),
  row.names = FALSE
)


qc_long <- tidyr::pivot_longer(
  sample_qc,
  cols = c(
    z_library_size,
    z_detected_miRNAs,
    z_zero_fraction,
    z_top1_fraction
  ),
  names_to = "metric",
  values_to = "robust_z"
)


p_out <- ggplot2::ggplot(
  qc_long,
  ggplot2::aes(
    x = Sample,
    y = robust_z
  )
) +
  ggplot2::geom_hline(
    yintercept = c(
      -3,
      3
    ),
    linetype = 2
  ) +
  ggplot2::geom_point() +
  ggplot2::facet_wrap(
    ~metric,
    scales = "free_y",
    ncol = 1
  ) +
  ggplot2::theme_classic(
    base_size = 9
  ) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(
      angle = 90,
      hjust = 1
    )
  ) +
  ggplot2::labs(
    title = "Sample QC robust z-scores",
    subtitle = "Flags are descriptive and do not trigger automatic exclusion",
    x = NULL,
    y = "Robust z"
  )


save_ggplot_png(
  plot = p_out,
  filename = file.path(
    outlier_dir,
    "sample_outlier_z_scores.png"
  ),
  width = 10,
  height = 8,
  dpi = 300
)


# ==============================================================================
# 5.9 Exploratory sequencing-based hemolysis proxy
# ==============================================================================

hemolysis_available <- all(
  c(
    HEMOLYSIS_MIRNA_RBC,
    HEMOLYSIS_MIRNA_REFERENCE
  ) %in%
    rownames(
      rpm_all
    )
)


hemolysis_test <- data.frame()


if (hemolysis_available) {
  
  hemolysis <- data.frame(
    
    Sample = colnames(
      rpm_all
    ),
    
    miR_451a_RPM = as.numeric(
      rpm_all[
        HEMOLYSIS_MIRNA_RBC,
        ,
        drop = TRUE
      ]
    ),
    
    miR_23a_3p_RPM = as.numeric(
      rpm_all[
        HEMOLYSIS_MIRNA_REFERENCE,
        ,
        drop = TRUE
      ]
    ),
    
    stringsAsFactors = FALSE
  )
  
  
  hemolysis$hemolysis_logRPM_difference <-
    safe_log2(
      hemolysis$miR_451a_RPM
    ) -
    safe_log2(
      hemolysis$miR_23a_3p_RPM
    )
  
  
  hemolysis <- dplyr::left_join(
    hemolysis,
    metadata[
      ,
      c(
        "Sample",
        "Apend_type",
        "Phenotype",
        "Phenotype_full",
        "Appendicitis_status",
        "Sex",
        "Age"
      ),
      drop = FALSE
    ],
    by = "Sample"
  )
  
  
  hemolysis <- dplyr::left_join(
    hemolysis,
    pca_df[
      ,
      c(
        "Sample",
        intersect(
          c(
            "PC1",
            "PC2",
            "PC3",
            "PC4",
            "PC5"
          ),
          colnames(
            pca_df
          )
        )
      ),
      drop = FALSE
    ],
    by = "Sample"
  )
  
  
  utils::write.csv(
    hemolysis,
    prepare_output_file(
      file.path(
        results_dir,
        "hemolysis_proxy.csv"
      )
    ),
    row.names = FALSE
  )
  
  
  # ---------------------------------------------------------------------------
  # Formal phenotype comparison
  # ---------------------------------------------------------------------------
  
  hemolysis_kw_data <- hemolysis[
    stats::complete.cases(
      hemolysis[
        ,
        c(
          "hemolysis_logRPM_difference",
          "Phenotype"
        )
      ]
    ),
    ,
    drop = FALSE
  ]
  
  
  if (
    nrow(
      hemolysis_kw_data
    ) >= 3L &&
    length(
      unique(
        hemolysis_kw_data$Phenotype
      )
    ) >= 2L
  ) {
    
    hemolysis_kw <- stats::kruskal.test(
      hemolysis_logRPM_difference ~ Phenotype,
      data = hemolysis_kw_data
    )
    
    
    hemolysis_test <- data.frame(
      
      analysis_id = context$analysis_id,
      
      variable = "hemolysis_logRPM_difference",
      
      grouping_variable = "Phenotype",
      
      method = "Kruskal-Wallis",
      
      statistic = unname(
        hemolysis_kw$statistic
      ),
      
      df = unname(
        hemolysis_kw$parameter
      ),
      
      p_value = hemolysis_kw$p.value,
      
      nominal_significant =
        hemolysis_kw$p.value < ALPHA_RAW,
      
      n = nrow(
        hemolysis_kw_data
      ),
      
      stringsAsFactors = FALSE
    )
  }
  
  
  utils::write.csv(
    hemolysis_test,
    prepare_output_file(
      file.path(
        results_dir,
        "hemolysis_phenotype_test.csv"
      )
    ),
    row.names = FALSE
  )
  
  
  p_hemo <- ggplot2::ggplot(
    hemolysis,
    ggplot2::aes(
      x = Phenotype,
      y = hemolysis_logRPM_difference
    )
  ) +
    ggplot2::geom_boxplot(
      outlier.shape = NA
    ) +
    ggplot2::geom_jitter(
      width = 0.12,
      height = 0,
      size = 2
    ) +
    ggplot2::theme_classic(
      base_size = 11
    ) +
    ggplot2::labs(
      title = "Exploratory sequencing-based hemolysis proxy",
      subtitle = paste0(
        "log2(miR-451a RPM + 1) - log2(miR-23a-3p RPM + 1); ",
        "no qPCR-specific cutoffs applied"
      ),
      x = "Clinical group",
      y = "Hemolysis proxy"
    )
  
  
  save_ggplot_png(
    plot = p_hemo,
    filename = file.path(
      hemolysis_dir,
      "hemolysis_proxy_by_phenotype.png"
    ),
    width = 7,
    height = 5.5,
    dpi = 300
  )
  
  
} else {
  
  hemolysis <- data.frame(
    
    note = paste(
      "Hemolysis proxy not calculated because one or both miRNAs are absent:",
      HEMOLYSIS_MIRNA_RBC,
      HEMOLYSIS_MIRNA_REFERENCE
    ),
    
    stringsAsFactors = FALSE
  )
  
  
  utils::write.csv(
    hemolysis,
    prepare_output_file(
      file.path(
        results_dir,
        "hemolysis_proxy.csv"
      )
    ),
    row.names = FALSE
  )
  
  
  utils::write.csv(
    data.frame(
      note = "Hemolysis phenotype test not performed because proxy was unavailable."
    ),
    prepare_output_file(
      file.path(
        results_dir,
        "hemolysis_phenotype_test.csv"
      )
    ),
    row.names = FALSE
  )
}


# ==============================================================================
# 5.10 PC associations with biological and technical covariates
# ==============================================================================

pca_covariate_df <- dplyr::left_join(
  pca_df,
  sample_qc[
    ,
    c(
      "Sample",
      "log10_library_size",
      "detected_miRNAs",
      "zero_fraction",
      "top1_fraction"
    ),
    drop = FALSE
  ],
  by = "Sample"
)


if (hemolysis_available) {
  
  pca_covariate_df <- dplyr::left_join(
    pca_covariate_df,
    hemolysis[
      ,
      c(
        "Sample",
        "hemolysis_logRPM_difference"
      ),
      drop = FALSE
    ],
    by = "Sample"
  )
}


pc_names_for_audit <- intersect(
  paste0(
    "PC",
    1:5
  ),
  colnames(
    pca_covariate_df
  )
)


continuous_covariates <- intersect(
  c(
    "Age",
    "hemolysis_logRPM_difference",
    "log10_library_size",
    "detected_miRNAs",
    "zero_fraction",
    "top1_fraction"
  ),
  colnames(
    pca_covariate_df
  )
)


categorical_covariates <- intersect(
  c(
    "Sex",
    "Appendicitis_status",
    "Phenotype"
  ),
  colnames(
    pca_covariate_df
  )
)


if (
  !is.na(
    BATCH_COLUMN
  ) &&
  BATCH_COLUMN %in%
  colnames(
    pca_covariate_df
  )
) {
  
  categorical_covariates <- unique(
    c(
      categorical_covariates,
      BATCH_COLUMN
    )
  )
}


pc_association_rows <- list()

association_index <- 0L


for (pc in pc_names_for_audit) {
  
  # ---------------------------------------------------------------------------
  # Continuous covariates
  # ---------------------------------------------------------------------------
  
  for (
    variable in continuous_covariates
  ) {
    
    dat <- pca_covariate_df[
      stats::complete.cases(
        pca_covariate_df[
          ,
          c(
            pc,
            variable
          ),
          drop = FALSE
        ]
      ),
      c(
        pc,
        variable
      ),
      drop = FALSE
    ]
    
    
    if (
      nrow(
        dat
      ) >= 5L &&
      length(
        unique(
          dat[[variable]]
        )
      ) >= 2L
    ) {
      
      test_result <- suppressWarnings(
        stats::cor.test(
          dat[[pc]],
          dat[[variable]],
          method = "spearman",
          exact = FALSE
        )
      )
      
      
      association_index <- association_index + 1L
      
      
      pc_association_rows[[
        association_index
      ]] <- data.frame(
        
        PC = pc,
        
        variable = variable,
        
        variable_type = "continuous_spearman",
        
        statistic = unname(
          test_result$estimate
        ),
        
        p_value = test_result$p.value,
        
        n = nrow(
          dat
        ),
        
        stringsAsFactors = FALSE
      )
    }
  }
  
  
  # ---------------------------------------------------------------------------
  # Categorical covariates
  # ---------------------------------------------------------------------------
  
  for (
    variable in categorical_covariates
  ) {
    
    dat <- pca_covariate_df[
      stats::complete.cases(
        pca_covariate_df[
          ,
          c(
            pc,
            variable
          ),
          drop = FALSE
        ]
      ),
      c(
        pc,
        variable
      ),
      drop = FALSE
    ]
    
    
    if (
      nrow(
        dat
      ) >= 5L &&
      length(
        unique(
          dat[[variable]]
        )
      ) >= 2L
    ) {
      
      test_result <- stats::kruskal.test(
        dat[[pc]] ~
          as.factor(
            dat[[variable]]
          )
      )
      
      
      association_index <- association_index + 1L
      
      
      pc_association_rows[[
        association_index
      ]] <- data.frame(
        
        PC = pc,
        
        variable = variable,
        
        variable_type = "categorical_kruskal",
        
        statistic = unname(
          test_result$statistic
        ),
        
        p_value = test_result$p.value,
        
        n = nrow(
          dat
        ),
        
        stringsAsFactors = FALSE
      )
    }
  }
}


if (length(
  pc_association_rows
) > 0L) {
  
  pc_associations <- do.call(
    rbind,
    pc_association_rows
  )
  
  
  pc_associations$FDR <- bh_adjust(
    pc_associations$p_value
  )
  
  
  pc_associations$nominal_significant <-
    pc_associations$p_value < ALPHA_RAW
  
  
  pc_associations$FDR_significant <-
    pc_associations$FDR < ALPHA_FDR
  
  
  pc_associations <- pc_associations[
    order(
      pc_associations$p_value
    ),
    ,
    drop = FALSE
  ]
  
  
  rownames(
    pc_associations
  ) <- NULL
  
} else {
  
  pc_associations <- data.frame(
    PC = character(0),
    variable = character(0),
    variable_type = character(0),
    statistic = numeric(0),
    p_value = numeric(0),
    n = integer(0),
    FDR = numeric(0),
    nominal_significant = logical(0),
    FDR_significant = logical(0)
  )
}


utils::write.csv(
  pc_associations,
  prepare_output_file(
    file.path(
      results_dir,
      "PC_covariate_associations.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 5.11 Batch audit
# ==============================================================================

batch_audit <- data.frame(
  
  configured_batch_column = ifelse(
    is.na(
      BATCH_COLUMN
    ),
    "",
    BATCH_COLUMN
  ),
  
  available_in_metadata = (
    !is.na(
      BATCH_COLUMN
    ) &&
      BATCH_COLUMN %in%
      colnames(
        metadata
      )
  ),
  
  decision = ifelse(
    is.na(
      BATCH_COLUMN
    ),
    paste0(
      "No validated batch variable is currently configured; ",
      "do not adjust for batch."
    ),
    ifelse(
      BATCH_COLUMN %in%
        colnames(
          metadata
        ),
      paste0(
        "Validated batch variable is available; inspect PC association ",
        "and phenotype confounding before inclusion in statistical models."
      ),
      "Configured batch variable is absent from metadata."
    )
  ),
  
  stringsAsFactors = FALSE
)


utils::write.csv(
  batch_audit,
  prepare_output_file(
    file.path(
      results_dir,
      "batch_audit_status.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 5.12 Global unsupervised heatmap
# ==============================================================================

# This heatmap is a GLOBAL EXPRESSION QC analysis.
#
# It deliberately uses:
#   - all filtered miRNAs;
#   - no differential-expression result;
#   - no manuscript-candidate selection;
#   - unsupervised row clustering;
#   - unsupervised sample clustering.
#
# This is a global-expression QC heatmap and is not used to define or
# prioritize downstream miRNA candidates.

heat_z_all <- t(
  scale(
    t(
      log_rpm
    )
  )
)


heat_z_all[
  !is.finite(
    heat_z_all
  )
] <- 0


storage.mode(
  heat_z_all
) <- "numeric"


ann_all <- data.frame(
  
  Phenotype = metadata$Phenotype,
  
  stringsAsFactors = FALSE,
  
  row.names = metadata$Sample
)


if (
  "Sex" %in%
  colnames(
    metadata
  )
) {
  
  ann_all$Sex <- as.character(
    metadata$Sex
  )
}


global_heatmap_manifest <- data.frame(
  
  miRNA = rownames(
    heat_z_all
  ),
  
  included = TRUE,
  
  source = "prespecified_expression_filter",
  
  stringsAsFactors = FALSE
)


utils::write.csv(
  global_heatmap_manifest,
  prepare_output_file(
    file.path(
      results_dir,
      "global_heatmap_feature_manifest.csv"
    )
  ),
  row.names = FALSE
)


heatmap_object <- pheatmap::pheatmap(
  
  heat_z_all,
  
  annotation_col = ann_all,
  
  cluster_rows = TRUE,
  
  cluster_cols = TRUE,
  
  clustering_distance_rows = "euclidean",
  
  clustering_distance_cols = "euclidean",
  
  clustering_method = "complete",
  
  show_rownames = FALSE,
  
  show_colnames = FALSE,
  
  border_color = NA,
  
  fontsize = 8,
  
  main = paste0(
    "Global unsupervised heatmap (",
    nrow(
      heat_z_all
    ),
    " filtered miRNAs)"
  ),
  
  silent = TRUE
)


# ==============================================================================
# 5.13 Heatmap clustering audit
# ==============================================================================

row_order <- heatmap_object$tree_row$order

col_order <- heatmap_object$tree_col$order


heatmap_row_order <- data.frame(
  
  heatmap_row_rank = seq_along(
    row_order
  ),
  
  miRNA = rownames(
    heat_z_all
  )[
    row_order
  ],
  
  stringsAsFactors = FALSE
)


heatmap_sample_order <- data.frame(
  
  heatmap_column_rank = seq_along(
    col_order
  ),
  
  Sample = colnames(
    heat_z_all
  )[
    col_order
  ],
  
  stringsAsFactors = FALSE
)


heatmap_sample_order <- dplyr::left_join(
  heatmap_sample_order,
  metadata[
    ,
    c(
      "Sample",
      "Phenotype",
      "Phenotype_full",
      "Appendicitis_status",
      "Apend_type",
      "Sex"
    ),
    drop = FALSE
  ],
  by = "Sample"
)


utils::write.csv(
  heatmap_row_order,
  prepare_output_file(
    file.path(
      results_dir,
      "global_heatmap_miRNA_cluster_order.csv"
    )
  ),
  row.names = FALSE
)


utils::write.csv(
  heatmap_sample_order,
  prepare_output_file(
    file.path(
      results_dir,
      "global_heatmap_sample_cluster_order.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 5.14 Exploratory three-cluster sample audit
# ==============================================================================

n_sample_clusters <- min(
  3L,
  ncol(
    heat_z_all
  )
)


sample_clusters <- stats::cutree(
  heatmap_object$tree_col,
  k = n_sample_clusters
)


sample_cluster_audit <- data.frame(
  
  Sample = names(
    sample_clusters
  ),
  
  unsupervised_cluster = as.integer(
    sample_clusters
  ),
  
  stringsAsFactors = FALSE
)


sample_cluster_audit <- dplyr::left_join(
  sample_cluster_audit,
  metadata[
    ,
    c(
      "Sample",
      "Phenotype",
      "Phenotype_full",
      "Appendicitis_status",
      "Apend_type",
      "Sex"
    ),
    drop = FALSE
  ],
  by = "Sample"
)


utils::write.csv(
  sample_cluster_audit,
  prepare_output_file(
    file.path(
      results_dir,
      "global_heatmap_sample_clusters_k3.csv"
    )
  ),
  row.names = FALSE
)


cluster_vs_phenotype <- as.data.frame.matrix(
  table(
    sample_cluster_audit$unsupervised_cluster,
    sample_cluster_audit$Phenotype,
    useNA = "ifany"
  )
)


cluster_vs_phenotype$unsupervised_cluster <-
  rownames(
    cluster_vs_phenotype
  )


cluster_vs_phenotype <- cluster_vs_phenotype[
  ,
  c(
    "unsupervised_cluster",
    setdiff(
      colnames(
        cluster_vs_phenotype
      ),
      "unsupervised_cluster"
    )
  ),
  drop = FALSE
]


rownames(
  cluster_vs_phenotype
) <- NULL


utils::write.csv(
  cluster_vs_phenotype,
  prepare_output_file(
    file.path(
      results_dir,
      "global_heatmap_cluster_vs_phenotype.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 6. OUTPUTS
# ==============================================================================

# ==============================================================================
# 6.1 Heatmap export helper
# ==============================================================================

draw_heatmap_gtable <- function(
    heatmap_gtable,
    filename,
    type = c(
      "pdf",
      "tiff"
    )
) {
  
  type <- match.arg(
    type
  )
  
  
  draw_function <- function() {
    
    grid::grid.newpage()
    
    grid::grid.draw(
      heatmap_gtable
    )
  }
  
  
  if (
    type == "pdf"
  ) {
    
    draw_to_pdf(
      filename = filename,
      width = 7,
      height = 5.2,
      draw = draw_function
    )
    
  } else {
    
    draw_to_tiff(
      filename = filename,
      width = 7,
      height = 5.2,
      units = "in",
      res = 600,
      compression = "lzw",
      draw = draw_function
    )
  }
  
  
  invisible(
    filename
  )
}


draw_heatmap_gtable(
  heatmap_object$gtable,
  file.path(
    heatmap_dir,
    "global_filtered_miRNAs_heatmap.pdf"
  ),
  "pdf"
)


draw_heatmap_gtable(
  heatmap_object$gtable,
  file.path(
    heatmap_dir,
    "global_filtered_miRNAs_heatmap.tiff"
  ),
  "tiff"
)


# ==============================================================================
# 6.2 Combined supplementary global-expression figure
# ==============================================================================

draw_global_expression_figure <- function(
    filename,
    type = c(
      "pdf",
      "tiff"
    )
) {
  
  type <- match.arg(
    type
  )
  
  
  draw_function <- function() {
    
    grid::grid.newpage()
    
    
    layout <- grid::grid.layout(
      
      nrow = 2L,
      
      ncol = 1L,
      
      heights = grid::unit(
        c(
          0.43,
          0.57
        ),
        "null"
      )
    )
    
    
    root_viewport <- grid::viewport(
      layout = layout
    )
    
    
    grid::pushViewport(
      root_viewport
    )
    
    
    print(
      p_pca_global,
      vp = grid::viewport(
        layout.pos.row = 1L,
        layout.pos.col = 1L
      ),
      newpage = FALSE
    )
    
    
    grid::pushViewport(
      grid::viewport(
        layout.pos.row = 2L,
        layout.pos.col = 1L
      )
    )
    
    
    grid::grid.draw(
      heatmap_object$gtable
    )
    
    
    grid::popViewport()
    
    grid::popViewport()
  }
  
  
  if (
    type == "pdf"
  ) {
    
    draw_to_pdf(
      filename = filename,
      width = 7,
      height = 9,
      draw = draw_function
    )
    
  } else {
    
    draw_to_tiff(
      filename = filename,
      width = 7,
      height = 9,
      units = "in",
      res = 600,
      compression = "lzw",
      draw = draw_function
    )
  }
  
  
  invisible(
    filename
  )
}


draw_global_expression_figure(
  file.path(
    global_expression_dir,
    "Supplementary_global_expression_PCA_heatmap.pdf"
  ),
  "pdf"
)


draw_global_expression_figure(
  file.path(
    global_expression_dir,
    "Supplementary_global_expression_PCA_heatmap.tiff"
  ),
  "tiff"
)


# ==============================================================================
# 7. QC / AUDIT
# ==============================================================================

# ==============================================================================
# 7.1 Descriptive summary
# ==============================================================================

descriptive <- data.frame(
  
  analysis_id = context$analysis_id,
  
  n_samples = nrow(
    metadata
  ),

  n_NIA = sum(
    metadata$Phenotype == "NIA"
  ),

  n_appendicitis = sum(
    metadata$Appendicitis_status == "Appendicitis"
  ),

  n_mild = sum(
    metadata$Phenotype == "Mild"
  ),

  n_severe = sum(
    metadata$Phenotype == "Severe"
  ),
  
  n_total_quantified_miRNAs = nrow(
    rpm_all
  ),
  
  n_filtered_miRNAs = nrow(
    rpm
  ),
  
  n_PCA_features = sum(
    pca_features
  ),
  
  PC1_variance_pct =
    variance_df$variance_explained_pct[1L],
  
  PC2_variance_pct =
    variance_df$variance_explained_pct[2L],
  
  median_library_size = stats::median(
    Metrics$Reads
  ),
  
  min_library_size = min(
    Metrics$Reads
  ),
  
  max_library_size = max(
    Metrics$Reads
  ),
  
  n_single_flag_samples = sum(
    sample_qc$outlier_status ==
      "SINGLE_FLAG"
  ),
  
  n_multiple_flag_samples = sum(
    sample_qc$outlier_status ==
      "MULTIPLE_FLAGS"
  ),
  
  hemolysis_proxy_available =
    hemolysis_available,
  
  hemolysis_phenotype_p = if (
    hemolysis_available &&
    nrow(
      hemolysis_test
    ) > 0L
  ) {
    hemolysis_test$p_value[1L]
  } else {
    NA_real_
  },
  
  stringsAsFactors = FALSE
)


utils::write.csv(
  descriptive,
  prepare_output_file(
    file.path(
      results_dir,
      "descriptive_stats.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 7.2 Final QC summary
# ==============================================================================

final_qc <- data.frame(
  
  analysis_id = context$analysis_id,
  
  sample_alignment_valid = (
    identical(
      metadata$Sample,
      colnames(rpm)
    ) &&
      identical(
        Metrics$Sample,
        colnames(rpm)
      )
  ),
  
  complete_RPM_sums_valid = all(
    abs(
      colSums(
        rpm_all
      ) -
        1e6
    ) <= 1e-4
  ),
  
  n_samples = ncol(
    rpm
  ),

  n_NIA = sum(
    metadata$Phenotype == "NIA"
  ),

  n_mild = sum(
    metadata$Phenotype == "Mild"
  ),

  n_severe = sum(
    metadata$Phenotype == "Severe"
  ),

  clinical_labels_valid = (
    identical(
      levels(
        metadata$Phenotype
      ),
      c(
        "NIA",
        "Mild",
        "Severe"
      )
    ) &&
      identical(
        levels(
          metadata$Appendicitis_status
        ),
        c(
          "NIA",
          "Appendicitis"
        )
      )
  ),

  n_filtered_miRNAs = nrow(
    rpm
  ),
  
  n_variable_PCA_features = sum(
    pca_features
  ),
  
  n_single_QC_flags = sum(
    sample_qc$outlier_status ==
      "SINGLE_FLAG"
  ),
  
  n_multiple_QC_flags = sum(
    sample_qc$outlier_status ==
      "MULTIPLE_FLAGS"
  ),
  
  samples_removed_by_script = 0L,
  
  global_heatmap_rows = nrow(
    heat_z_all
  ),
  
  global_heatmap_columns = ncol(
    heat_z_all
  ),
  
  stringsAsFactors = FALSE
)


utils::write.csv(
  final_qc,
  prepare_output_file(
    file.path(
      results_dir,
      "02_final_QC_summary.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 8. REPRODUCIBILITY
# ==============================================================================

write_session_info(
  results_dir
)


message(
  "\n============================================================"
)

message(
  "02 complete"
)

message(
  "Analysis: ",
  context$analysis_id
)

message(
  "Samples: ",
  ncol(
    rpm
  )
)


message(
  "NIA / Mild / Severe: ",
  sum(
    metadata$Phenotype == "NIA"
  ),
  " / ",
  sum(
    metadata$Phenotype == "Mild"
  ),
  " / ",
  sum(
    metadata$Phenotype == "Severe"
  )
)


message(
  "Filtered miRNAs used for global QC: ",
  nrow(
    rpm
  )
)

message(
  "Variable PCA features: ",
  sum(
    pca_features
  )
)

message(
  sprintf(
    "PC1 / PC2 variance: %.2f%% / %.2f%%",
    variance_df$variance_explained_pct[1L],
    variance_df$variance_explained_pct[2L]
  )
)

message(
  "QC flags — single / multiple: ",
  sum(
    sample_qc$outlier_status ==
      "SINGLE_FLAG"
  ),
  " / ",
  sum(
    sample_qc$outlier_status ==
      "MULTIPLE_FLAGS"
  )
)


if (
  hemolysis_available &&
  nrow(
    hemolysis_test
  ) > 0L
) {
  
  message(
    sprintf(
      "Hemolysis proxy clinical-group test: Kruskal-Wallis p = %.6g",
      hemolysis_test$p_value[1L]
    )
  )
}


message(
  "No samples were removed automatically."
)

message(
  "Global PCA/heatmap are QC/supplementary analyses and do not define ",
  "downstream miRNA candidates."
)

message(
  "============================================================\n"
)
