# ==============================================================================
# 03_DANA_analysis.R
# ==============================================================================
#
# Project:
#   Pediatric appendicitis plasma miRNA-seq
#
# Script:
#   03_DANA_analysis.R
#
# Purpose:
#   Evaluate normalization performance using the original DANA framework
#   (Data-driven Assessment of Normalization Methods for miRNA-seq).
#
# Role in pipeline:
#   Normalization assessment / methodological validation.
#
#   This script:
#     - uses the complete raw miRNA count matrix from the selected cohort;
#     - inherits the canonical clinical labels created by script 01;
#     - validates cohort/metadata consistency inherited from script 01;
#     - verifies mathematical equivalence between project RPM and Total Count;
#     - maps miRNAs to DANA miRBase v22 genomic coordinates;
#     - defines polycistronic miRNA clusters;
#     - defines DANA positive and negative controls;
#     - applies the normalization methods implemented by DANA;
#     - adds project RPM as the Total-Count-equivalent normalization;
#     - evaluates normalization using the original DANA cc and mscr metrics;
#     - records complete control, coordinate and normalization traceability.
#
# IMPORTANT:
#   DANA is applied to the COMPLETE raw miRNA count matrix generated by script
#   01, before the 100-RPM / 50%-prevalence feature filter.
#
#   This is required because DANA uses poorly expressed miRNAs as negative
#   controls. Applying the downstream expression filter first would invalidate
#   that component of the method.
#
# Canonical clinical groups inherited from script 01:
#   NIA    = non-inflamed appendix
#   Mild   = mild appendicitis
#   Severe = severe appendicitis
#
#   NIA is NOT a healthy-control cohort.
#
# DANA control thresholds:
#   tZero = 2
#   tPoor = 5
#   tWell = 100
#
# Polycistronic cluster threshold:
#   <= 10,000 bp
#
# Normalization methods assessed:
#   UQ
#   Median (returned by DANA as Med)
#   TMM
#   DESeq
#   PoissonSeq
#   QN
#   RUVg
#   RUVs
#   RUVr
#   RPM
#
# Total Count (TC):
#   TC is not evaluated as a duplicated method because project RPM uses:
#
#       raw count / complete raw-count library size * 1,000,000
#
#   which is mathematically equivalent to DANA Total Count normalization.
#   Numerical equivalence is explicitly verified before DANA assessment.
#
# DANA interpretation:
#   cc:
#     preservation of biological correlation structure among clustered positive
#     controls. Higher values, ideally close to 1, indicate better preservation.
#
#   mscr:
#     relative reduction of unwanted correlation among negative controls.
#     Higher values indicate stronger removal of handling effects.
#
#   No post hoc composite score is calculated or used to rank methods.
#
# IMPORTANT FOR DOWNSTREAM ANALYSIS:
#   The normalized matrices generated here are DANA assessment products only.
#   They are not automatically substituted into the differential-expression
#   workflow. edgeR and DESeq2 downstream analyses continue to use raw counts
#   with their method-appropriate normalization/modeling procedures.
#
# Inputs:
#   results/<analysis_id>/counts_analysis_samples.rds
#   results/<analysis_id>/RPM_counts_all_miRNAs.rds
#   results/<analysis_id>/metadata_analysis_samples.rds
#
# Main outputs:
#   results/<analysis_id>/DANA/
#
#     DANA_group_summary.csv
#     DANA_RPM_TC_equivalence.csv
#     miRNA_name_mapping.csv
#     DANA_coordinate_coverage_summary.csv
#     DANA_miRNAs_without_coordinates.csv
#     DANA_unclustered_miRNAs.csv
#     DANA_miRNA_clusters.csv
#     DANA_cluster_sizes.csv
#     DANA_cluster_summary.csv
#     DANA_control_thresholds.csv
#     DANA_controls.csv
#     DANA_control_summary.csv
#     DANA_positive_control_clusters.csv
#     DANA_normalization_method_summary.csv
#     DANA_control_availability_by_method.csv
#     DANA_assessment_results.csv
#     DANA_assessment_results.rds
#     normalized_matrices/
#     03_final_QC_summary.csv
#     sessionInfo.txt
#
# Figures:
#   figures/<analysis_id>/DANA/
#
#     DANA_count_distribution.png
#     DANA_mean_SD.png
#     DANA_normalization_assessment.pdf
#     DANA_normalization_assessment.tiff
#     DANA_normalization_assessment.png
#
# Methodological decisions:
#   - No samples are removed in this script.
#   - No artificial positive or negative controls are added.
#   - The original DANA cc and mscr metrics are preserved.
#   - Clinical grouping is inherited from metadata$Phenotype generated in 01;
#     this script never remaps Apend_type values to new display labels.
#   - DANA's bundled human miRBase v22 coordinates are supplied explicitly to
#     defineClusters() to avoid a namespace-dependent issue in DANA 1.4.0.
#
# Reproducibility:
#   Cohort membership and clinical labels are inherited from scripts 00/01.
#   All DANA thresholds, control sets, normalization methods and assessment
#   outputs are exported explicitly.
#
# ==============================================================================


# ==============================================================================
# 1. DEPENDENCIES
# ==============================================================================

required_packages <- c(
  "here",
  "DANA",
  "ggplot2",
  "ggrepel",
  "edgeR",
  "DESeq2",
  "PoissonSeq",
  "limma",
  "RUVSeq",
  "EDASeq",
  "Biobase",
  "DescTools"
)


missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]


if (length(missing_packages) > 0L) {
  stop(
    "Missing package(s) required by R/03_DANA_analysis.R:\n",
    paste(
      "-",
      missing_packages,
      collapse = "\n"
    ),
    "\nRun R/00_packages_setup.R first.",
    call. = FALSE
  )
}


source(
  here::here(
    "R",
    "00_analysis_config.R"
  )
)


source(
  here::here(
    "R",
    "00_utils.R"
  )
)


if (
  utils::compareVersion(
    as.character(
      utils::packageVersion("DANA")
    ),
    "1.4.0"
  ) < 0
) {
  stop(
    "DANA >= 1.4.0 is required.",
    call. = FALSE
  )
}


# ==============================================================================
# 2. CONFIGURATION
# ==============================================================================

context <- get_analysis_context()

results_dir <- context$results_dir
figures_dir <- context$figures_dir


dana_results_dir <- file.path(
  results_dir,
  "DANA"
)


dana_figures_dir <- file.path(
  figures_dir,
  "DANA"
)


normalized_output_dir <- file.path(
  dana_results_dir,
  "normalized_matrices"
)


for (
  directory in c(
    dana_results_dir,
    dana_figures_dir,
    normalized_output_dir
  )
) {
  ensure_dir(directory)
}


# Prespecified DANA control thresholds.
DANA_TZERO <- 2
DANA_TPOOR <- 5
DANA_TWELL <- 100

# DANA / miRBase default cluster distance.
DANA_CLUSTER_DISTANCE_BP <- 10000L

# DANA::assessNormalization() internally requires at least 10 positive and
# 10 negative controls for every normalization method.
DANA_MIN_CONTROLS <- 10L

# TC is intentionally omitted because RPM is demonstrated to be equivalent.
normalization_methods_requested <- c(
  "UQ",
  "median",
  "TMM",
  "DESeq",
  "PoissonSeq",
  "QN",
  "RUV"
)

# applyNormalization() expands RUV into RUVg/RUVs/RUVr and returns median as Med.
expected_normalized_methods <- c(
  "UQ",
  "Med",
  "TMM",
  "DESeq",
  "PoissonSeq",
  "QN",
  "RUVg",
  "RUVs",
  "RUVr",
  "RPM"
)


message(
  "\n============================================================"
)
message(
  "03_DANA_analysis.R"
)
message(
  "Analysis ID: ",
  context$analysis_id
)
message(
  "Role: ",
  context$role
)
message(
  "Expected n: ",
  context$expected_n
)
message(
  "============================================================\n"
)


# ==============================================================================
# 3. INPUTS
# ==============================================================================

required_files <- c(
  counts = file.path(
    results_dir,
    "counts_analysis_samples.rds"
  ),
  RPM = file.path(
    results_dir,
    "RPM_counts_all_miRNAs.rds"
  ),
  metadata = file.path(
    results_dir,
    "metadata_analysis_samples.rds"
  )
)


missing_files <- required_files[
  !file.exists(required_files)
]


if (length(missing_files) > 0L) {
  stop(
    "Missing input file(s) generated by script 01:\n",
    paste(
      "-",
      missing_files,
      collapse = "\n"
    ),
    call. = FALSE
  )
}


counts <- readRDS(
  required_files[["counts"]]
)

RPM_counts <- readRDS(
  required_files[["RPM"]]
)

metadata <- readRDS(
  required_files[["metadata"]]
)


counts <- as.matrix(counts)
RPM_counts <- as.matrix(RPM_counts)
metadata <- as.data.frame(
  metadata,
  stringsAsFactors = FALSE
)

storage.mode(counts) <- "numeric"
storage.mode(RPM_counts) <- "numeric"


message(
  "Loaded data:"
)
message(
  "- Raw counts: ",
  nrow(counts),
  " miRNAs x ",
  ncol(counts),
  " samples"
)
message(
  "- RPM matrix: ",
  nrow(RPM_counts),
  " miRNAs x ",
  ncol(RPM_counts),
  " samples"
)
message(
  "- Metadata: ",
  nrow(metadata),
  " samples"
)


# ==============================================================================
# 4. VALIDATION
# ==============================================================================

# ==============================================================================
# 4.1 Expression-matrix integrity
# ==============================================================================

for (
  object_name in c(
    "counts",
    "RPM_counts"
  )
) {
  expression_matrix <- get(object_name)

  if (
    nrow(expression_matrix) == 0L ||
    ncol(expression_matrix) == 0L
  ) {
    stop(
      object_name,
      " is empty.",
      call. = FALSE
    )
  }

  if (
    is.null(rownames(expression_matrix)) ||
    is.null(colnames(expression_matrix))
  ) {
    stop(
      object_name,
      " must contain miRNA row names and sample column names.",
      call. = FALSE
    )
  }

  if (
    anyDuplicated(rownames(expression_matrix)) > 0L ||
    anyDuplicated(colnames(expression_matrix)) > 0L
  ) {
    stop(
      object_name,
      " contains duplicated miRNA or sample identifiers.",
      call. = FALSE
    )
  }

  if (
    anyNA(expression_matrix) ||
    any(!is.finite(expression_matrix)) ||
    any(expression_matrix < 0)
  ) {
    stop(
      object_name,
      " contains missing, non-finite or negative values.",
      call. = FALSE
    )
  }
}


if (
  any(
    abs(
      counts - round(counts)
    ) > sqrt(.Machine$double.eps)
  )
) {
  stop(
    "Raw-count matrix contains non-integer-like values.",
    call. = FALSE
  )
}


# ==============================================================================
# 4.2 Metadata integrity and canonical clinical labels
# ==============================================================================

required_metadata_columns <- c(
  "Sample",
  "Condition",
  "Apend_type",
  "Phenotype",
  "Phenotype_full",
  "Appendicitis_status",
  "Sex",
  "Age"
)


missing_metadata_columns <- setdiff(
  required_metadata_columns,
  colnames(metadata)
)


if (length(missing_metadata_columns) > 0L) {
  stop(
    "metadata_analysis_samples.rds lacks canonical variable(s) expected from ",
    "script 01: ",
    paste(
      missing_metadata_columns,
      collapse = ", "
    ),
    ". Re-run R/01_data_loading_and_filtering.R before DANA.",
    call. = FALSE
  )
}


metadata$Sample <- as.character(metadata$Sample)


if (
  anyNA(metadata$Sample) ||
  any(!nzchar(metadata$Sample)) ||
  anyDuplicated(metadata$Sample) > 0L
) {
  stop(
    "Metadata contains invalid or duplicated Sample identifiers.",
    call. = FALSE
  )
}


validate_selected_metadata(metadata)


expected_short_labels <- c(
  "0" = "NIA",
  "1" = "Mild",
  "2" = "Severe"
)

expected_full_labels <- c(
  "0" = "Non-inflamed appendix",
  "1" = "Mild appendicitis",
  "2" = "Severe appendicitis"
)


apend_chr <- as.character(metadata$Apend_type)

expected_phenotype <- unname(
  expected_short_labels[apend_chr]
)

expected_phenotype_full <- unname(
  expected_full_labels[apend_chr]
)

expected_appendicitis_status <- ifelse(
  apend_chr == "0",
  "NIA",
  "Appendicitis"
)


clinical_labels_valid <- (
  !anyNA(expected_phenotype) &&
  identical(
    as.character(metadata$Phenotype),
    expected_phenotype
  ) &&
  identical(
    as.character(metadata$Phenotype_full),
    expected_phenotype_full
  ) &&
  identical(
    as.character(metadata$Appendicitis_status),
    expected_appendicitis_status
  )
)


if (!clinical_labels_valid) {
  stop(
    "Canonical clinical labels in metadata are inconsistent with Apend_type. ",
    "Re-run script 01 and do not recode phenotype groups inside DANA.",
    call. = FALSE
  )
}


message(
  "Canonical clinical labels validated: NIA / Mild / Severe."
)


# ==============================================================================
# 4.3 Cross-object alignment
# ==============================================================================

if (!setequal(
  colnames(counts),
  metadata$Sample
)) {
  stop(
    "Raw counts and metadata contain different samples.",
    call. = FALSE
  )
}


if (!setequal(
  colnames(counts),
  colnames(RPM_counts)
)) {
  stop(
    "Raw counts and RPM matrix contain different samples.",
    call. = FALSE
  )
}


if (!setequal(
  rownames(counts),
  rownames(RPM_counts)
)) {
  stop(
    "Raw counts and RPM matrix contain different miRNAs.",
    call. = FALSE
  )
}


metadata <- metadata[
  match(
    colnames(counts),
    metadata$Sample
  ),
  ,
  drop = FALSE
]

rownames(metadata) <- metadata$Sample


RPM_counts <- RPM_counts[
  rownames(counts),
  colnames(counts),
  drop = FALSE
]


if (!identical(
  metadata$Sample,
  colnames(counts)
)) {
  stop(
    "Metadata/count sample alignment failed.",
    call. = FALSE
  )
}


if (!identical(
  colnames(RPM_counts),
  colnames(counts)
)) {
  stop(
    "RPM/count sample alignment failed.",
    call. = FALSE
  )
}


if (!identical(
  rownames(RPM_counts),
  rownames(counts)
)) {
  stop(
    "RPM/count miRNA alignment failed.",
    call. = FALSE
  )
}


# ==============================================================================
# 4.4 Primary-cohort freeze
# ==============================================================================

if (
  nrow(metadata) == 0L
) {
  stop(
    "DANA analysis requires a non-empty selected cohort.",
    call. = FALSE
  )
}


# ==============================================================================
# 4.5 DANA grouping inherited from metadata$Phenotype
# ==============================================================================

# No Apend_type -> display-label recoding is performed here.
# The canonical labels were created and frozen in script 01.

groups <- factor(
  as.character(metadata$Phenotype),
  levels = c(
    "NIA",
    "Mild",
    "Severe"
  )
)

names(groups) <- metadata$Sample


if (anyNA(groups)) {
  stop(
    "metadata$Phenotype contains values outside NIA/Mild/Severe.",
    call. = FALSE
  )
}


if (nlevels(droplevels(groups)) < 2L) {
  stop(
    "DANA requires at least two experimental groups.",
    call. = FALSE
  )
}


group_table <- table(groups)


dana_group_summary <- data.frame(
  Phenotype = names(group_table),
  Phenotype_full = c(
    "NIA" = "Non-inflamed appendix",
    "Mild" = "Mild appendicitis",
    "Severe" = "Severe appendicitis"
  )[names(group_table)],
  n = as.integer(group_table),
  stringsAsFactors = FALSE
)


utils::write.csv(
  dana_group_summary,
  prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_group_summary.csv"
    )
  ),
  row.names = FALSE
)


message(
  "Samples per DANA group: ",
  paste(
    paste0(
      dana_group_summary$Phenotype,
      "=",
      dana_group_summary$n
    ),
    collapse = "; "
  )
)


# ==============================================================================
# 4.6 Validate complete RPM matrix
# ==============================================================================

rpm_column_sums <- colSums(RPM_counts)


if (
  any(
    abs(
      rpm_column_sums - 1e6
    ) > 1e-4
  )
) {
  stop(
    "Complete RPM matrix failed the 1,000,000 RPM column-sum check.",
    call. = FALSE
  )
}


# ==============================================================================
# 4.7 Verify RPM / Total Count equivalence
# ==============================================================================

library_sizes <- colSums(counts)


if (
  anyNA(library_sizes) ||
  any(!is.finite(library_sizes)) ||
  any(library_sizes <= 0)
) {
  stop(
    "At least one sample has an invalid raw-count library size.",
    call. = FALSE
  )
}


TC_reference <- sweep(
  counts,
  2L,
  library_sizes,
  FUN = "/"
) * 1e6


TC_reference <- TC_reference[
  rownames(RPM_counts),
  colnames(RPM_counts),
  drop = FALSE
]


absolute_difference <- abs(
  TC_reference - RPM_counts
)


maximum_absolute_difference <- max(
  absolute_difference,
  na.rm = TRUE
)

mean_absolute_difference <- mean(
  absolute_difference,
  na.rm = TRUE
)


rpm_tc_equivalent <- isTRUE(
  all.equal(
    TC_reference,
    RPM_counts,
    tolerance = 1e-10,
    check.attributes = FALSE
  )
)


rpm_tc_equivalence <- data.frame(
  comparison = "RPM_vs_Total_Count",
  equivalent = rpm_tc_equivalent,
  tolerance = 1e-10,
  maximum_absolute_difference = maximum_absolute_difference,
  mean_absolute_difference = mean_absolute_difference,
  denominator = "complete_raw_count_matrix_column_sum",
  stringsAsFactors = FALSE
)


utils::write.csv(
  rpm_tc_equivalence,
  prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_RPM_TC_equivalence.csv"
    )
  ),
  row.names = FALSE
)


if (!rpm_tc_equivalent) {
  stop(
    "RPM and Total Count normalization are not numerically equivalent. ",
    "Maximum absolute difference: ",
    signif(
      maximum_absolute_difference,
      6
    ),
    ". Check the RPM denominator and sample alignment before continuing.",
    call. = FALSE
  )
}


message(
  "RPM and DANA Total Count normalization are numerically equivalent."
)
message(
  "TC will not be included as a duplicated normalization method."
)


# ==============================================================================
# 5. ANALYSIS / PROCESSING
# ==============================================================================

# ==============================================================================
# 5.1 Harmonize miRNA identifiers for DANA
# ==============================================================================

counts_dana <- counts
RPM_dana <- RPM_counts


original_miRNA_names <- rownames(counts_dana)

harmonised_miRNA_names <- tolower(
  original_miRNA_names
)


if (
  anyNA(harmonised_miRNA_names) ||
  any(!nzchar(harmonised_miRNA_names))
) {
  stop(
    "Invalid miRNA identifiers after lower-case DANA harmonization.",
    call. = FALSE
  )
}


if (anyDuplicated(harmonised_miRNA_names) > 0L) {
  duplicated_names <- unique(
    harmonised_miRNA_names[
      duplicated(harmonised_miRNA_names)
    ]
  )

  stop(
    "Duplicated miRNA identifiers after lower-case harmonization: ",
    paste(
      duplicated_names,
      collapse = ", "
    ),
    call. = FALSE
  )
}


rownames(counts_dana) <- harmonised_miRNA_names
rownames(RPM_dana) <- harmonised_miRNA_names


miRNA_name_mapping <- data.frame(
  original_miRNA = original_miRNA_names,
  DANA_miRNA = harmonised_miRNA_names,
  stringsAsFactors = FALSE
)


utils::write.csv(
  miRNA_name_mapping,
  prepare_output_file(
    file.path(
      dana_results_dir,
      "miRNA_name_mapping.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 5.2 Map miRNAs to DANA miRBase v22 coordinates
# ==============================================================================

message(
  "Mapping miRNAs to DANA miRBase v22 coordinates..."
)


# DANA::defineClusters() is intended to use the package's bundled coordinates
# when chr/pos are omitted. In DANA 1.4.0, the function contains an unqualified
# reference to miRNA.coordinates before subsequently using DANA::miRNA.coordinates.
# Passing the bundled coordinate table explicitly avoids namespace-dependent
# failure while preserving DANA's intended human miRBase v22 annotation.

mirbase_coordinates <- as.data.frame(
  DANA::miRNA.coordinates,
  stringsAsFactors = FALSE
)


if (
  is.null(rownames(mirbase_coordinates)) ||
  !all(
    c(
      "chromosome",
      "position"
    ) %in% colnames(mirbase_coordinates)
  )
) {
  stop(
    "DANA::miRNA.coordinates does not have the expected row names and ",
    "chromosome/position columns.",
    call. = FALSE
  )
}


dana_genes <- rownames(counts_dana)

coordinate_match <- match(
  dana_genes,
  rownames(mirbase_coordinates)
)


genes_with_coordinates <- dana_genes[
  !is.na(coordinate_match)
]

genes_without_coordinates <- dana_genes[
  is.na(coordinate_match)
]


coordinate_coverage_summary <- data.frame(
  n_input_miRNAs = length(dana_genes),
  n_with_DANA_miRBase_v22_coordinates = length(genes_with_coordinates),
  n_without_DANA_miRBase_v22_coordinates = length(genes_without_coordinates),
  coordinate_coverage_fraction = length(genes_with_coordinates) / length(dana_genes),
  coordinate_coverage_percent = 100 * length(genes_with_coordinates) / length(dana_genes),
  stringsAsFactors = FALSE
)


utils::write.csv(
  coordinate_coverage_summary,
  prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_coordinate_coverage_summary.csv"
    )
  ),
  row.names = FALSE
)


message(
  "miRNAs found in DANA miRBase v22 coordinates: ",
  length(genes_with_coordinates),
  "/",
  length(dana_genes),
  " (",
  round(
    100 * length(genes_with_coordinates) / length(dana_genes),
    2
  ),
  "%)"
)


if (length(genes_with_coordinates) == 0L) {
  stop(
    "No miRNAs could be matched to DANA's bundled human miRBase v22 ",
    "coordinates. Check miRNA annotation before continuing.",
    call. = FALSE
  )
}


utils::write.csv(
  data.frame(
    miRNA = genes_without_coordinates,
    reason = rep(
      "not_found_in_DANA_miRBase_v22_coordinates",
      length(genes_without_coordinates)
    ),
    stringsAsFactors = FALSE
  ),
  prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_miRNAs_without_coordinates.csv"
    )
  ),
  row.names = FALSE
)


# Backwards-compatible audit filename retained from the previous pipeline.
# In DANA terms these genes are outside the coordinate-derived cluster vector
# and can still contribute as unclustered negative-control candidates.
utils::write.csv(
  data.frame(
    miRNA = genes_without_coordinates,
    reason = rep(
      "outside_coordinate_derived_cluster_vector",
      length(genes_without_coordinates)
    ),
    stringsAsFactors = FALSE
  ),
  prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_unclustered_miRNAs.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 5.3 Define polycistronic clusters
# ==============================================================================

message(
  "Defining DANA polycistronic miRNA clusters..."
)


chr_dana <- mirbase_coordinates[
  genes_with_coordinates,
  "chromosome"
]

pos_dana <- mirbase_coordinates[
  genes_with_coordinates,
  "position"
]


clusters <- DANA::defineClusters(
  genes = genes_with_coordinates,
  chr = chr_dana,
  pos = pos_dana,
  threshold = DANA_CLUSTER_DISTANCE_BP
)


if (
  is.null(clusters) ||
  length(clusters) == 0L ||
  is.null(names(clusters))
) {
  stop(
    "DANA did not return a valid named cluster vector.",
    call. = FALSE
  )
}


if (!all(
  names(clusters) %in% genes_with_coordinates
)) {
  stop(
    "DANA cluster object contains unexpected miRNA identifiers.",
    call. = FALSE
  )
}


cluster_table <- data.frame(
  miRNA = names(clusters),
  cluster = as.character(clusters),
  stringsAsFactors = FALSE
)

cluster_table <- cluster_table[
  !is.na(cluster_table$miRNA) &
    !is.na(cluster_table$cluster),
  ,
  drop = FALSE
]


cluster_sizes <- as.data.frame(
  table(cluster_table$cluster),
  stringsAsFactors = FALSE
)

colnames(cluster_sizes) <- c(
  "cluster",
  "n_miRNAs"
)

cluster_sizes$n_miRNAs <- as.integer(
  cluster_sizes$n_miRNAs
)

cluster_sizes$is_polycistronic <- (
  cluster_sizes$n_miRNAs >= 2L
)

cluster_sizes <- cluster_sizes[
  order(
    cluster_sizes$n_miRNAs,
    decreasing = TRUE
  ),
  ,
  drop = FALSE
]


polycistronic_cluster_names <- cluster_sizes$cluster[
  cluster_sizes$is_polycistronic
]

miRNAs_in_polycistronic_clusters <- cluster_table$miRNA[
  cluster_table$cluster %in% polycistronic_cluster_names
]


cluster_summary <- data.frame(
  distance_threshold_bp = DANA_CLUSTER_DISTANCE_BP,
  n_miRNAs_with_coordinates = length(genes_with_coordinates),
  n_coordinate_defined_clusters = nrow(cluster_sizes),
  n_polycistronic_clusters = length(polycistronic_cluster_names),
  n_miRNAs_in_polycistronic_clusters = length(unique(miRNAs_in_polycistronic_clusters)),
  n_singleton_clusters = sum(cluster_sizes$n_miRNAs == 1L),
  n_miRNAs_without_coordinates = length(genes_without_coordinates),
  stringsAsFactors = FALSE
)


utils::write.csv(
  cluster_table,
  prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_miRNA_clusters.csv"
    )
  ),
  row.names = FALSE
)


utils::write.csv(
  cluster_sizes,
  prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_cluster_sizes.csv"
    )
  ),
  row.names = FALSE
)


utils::write.csv(
  cluster_summary,
  prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_cluster_summary.csv"
    )
  ),
  row.names = FALSE
)


message(
  "DANA coordinate-defined clusters: ",
  nrow(cluster_sizes),
  "; polycistronic clusters (>=2 miRNAs): ",
  length(polycistronic_cluster_names),
  "; miRNAs in polycistronic clusters: ",
  length(unique(miRNAs_in_polycistronic_clusters))
)


# ==============================================================================
# 5.4 Define and audit DANA control thresholds
# ==============================================================================

# These thresholds are frozen methodological parameters. Diagnostic plots are
# regenerated below as an audit; thresholds must not be optimized using
# downstream DE results.

threshold_table <- data.frame(
  parameter = c(
    "tZero",
    "tPoor",
    "tWell"
  ),
  value = c(
    DANA_TZERO,
    DANA_TPOOR,
    DANA_TWELL
  ),
  role = c(
    "negative_control_lower_bound",
    "negative_control_upper_bound",
    "positive_control_lower_bound"
  ),
  status = "prespecified",
  stringsAsFactors = FALSE
)


utils::write.csv(
  threshold_table,
  prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_control_thresholds.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 5.5 Diagnostic figures for threshold audit
# ==============================================================================

message(
  "Generating DANA control-threshold diagnostic figures..."
)


grDevices::png(
  filename = prepare_output_file(
    file.path(
      dana_figures_dir,
      "DANA_count_distribution.png"
    )
  ),
  width = 1800,
  height = 1400,
  res = 200
)

count_distribution_plot <- DANA::plotCountHist(
  counts_dana,
  binwidth = 0.1,
  DANA_TZERO,
  DANA_TPOOR,
  DANA_TWELL,
  title = "miRNA count distribution"
)

print(count_distribution_plot)
grDevices::dev.off()


grDevices::png(
  filename = prepare_output_file(
    file.path(
      dana_figures_dir,
      "DANA_mean_SD.png"
    )
  ),
  width = 1800,
  height = 1400,
  res = 200
)

mean_sd_plot <- DANA::plotMeanSD(
  counts_dana,
  DANA_TZERO,
  DANA_TPOOR,
  DANA_TWELL,
  title = "Mean versus standard deviation"
)

print(mean_sd_plot)
grDevices::dev.off()


# ==============================================================================
# 5.6 Define positive and negative DANA controls
# ==============================================================================

message(
  "Defining DANA positive and negative controls..."
)


controls <- DANA::defineControls(
  counts_dana,
  tZero = DANA_TZERO,
  tPoor = DANA_TPOOR,
  tWell = DANA_TWELL,
  clusters = clusters
)


if (
  is.null(controls$posControls) ||
  is.null(controls$negControls)
) {
  stop(
    "DANA::defineControls() did not return positive and negative controls.",
    call. = FALSE
  )
}


positive_controls <- unique(
  as.character(controls$posControls)
)

negative_controls <- unique(
  as.character(controls$negControls)
)


if (length(intersect(
  positive_controls,
  negative_controls
)) > 0L) {
  stop(
    "A miRNA was classified simultaneously as a DANA positive and negative ",
    "control.",
    call. = FALSE
  )
}


if (!all(
  positive_controls %in% rownames(counts_dana)
)) {
  stop(
    "One or more DANA positive controls are absent from the raw count matrix.",
    call. = FALSE
  )
}


if (!all(
  negative_controls %in% rownames(counts_dana)
)) {
  stop(
    "One or more DANA negative controls are absent from the raw count matrix.",
    call. = FALSE
  )
}


if (!all(
  positive_controls %in% names(clusters)
)) {
  stop(
    "One or more DANA positive controls lack cluster information.",
    call. = FALSE
  )
}


control_cluster_lookup <- setNames(
  as.character(clusters),
  names(clusters)
)


control_table <- rbind(
  data.frame(
    miRNA = positive_controls,
    control_type = "positive",
    raw_mean_count = rowMeans(counts_dana[positive_controls, , drop = FALSE]),
    cluster = unname(control_cluster_lookup[positive_controls]),
    has_DANA_coordinate = positive_controls %in% genes_with_coordinates,
    stringsAsFactors = FALSE
  ),
  data.frame(
    miRNA = negative_controls,
    control_type = "negative",
    raw_mean_count = rowMeans(counts_dana[negative_controls, , drop = FALSE]),
    cluster = unname(control_cluster_lookup[negative_controls]),
    has_DANA_coordinate = negative_controls %in% genes_with_coordinates,
    stringsAsFactors = FALSE
  )
)


control_summary <- data.frame(
  control_type = c(
    "positive",
    "negative"
  ),
  n_controls = c(
    length(positive_controls),
    length(negative_controls)
  ),
  minimum_required_by_DANA = DANA_MIN_CONTROLS,
  sufficient = c(
    length(positive_controls) >= DANA_MIN_CONTROLS,
    length(negative_controls) >= DANA_MIN_CONTROLS
  ),
  stringsAsFactors = FALSE
)


positive_control_clusters <- data.frame(
  miRNA = positive_controls,
  cluster = unname(
    control_cluster_lookup[positive_controls]
  ),
  stringsAsFactors = FALSE
)

positive_control_clusters <- merge(
  positive_control_clusters,
  cluster_sizes[
    ,
    c(
      "cluster",
      "n_miRNAs",
      "is_polycistronic"
    ),
    drop = FALSE
  ],
  by = "cluster",
  all.x = TRUE,
  sort = FALSE
)


utils::write.csv(
  control_table,
  prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_controls.csv"
    )
  ),
  row.names = FALSE
)


utils::write.csv(
  control_summary,
  prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_control_summary.csv"
    )
  ),
  row.names = FALSE
)


utils::write.csv(
  positive_control_clusters,
  prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_positive_control_clusters.csv"
    )
  ),
  row.names = FALSE
)


message(
  "Positive controls identified: ",
  length(positive_controls)
)
message(
  "Negative controls identified: ",
  length(negative_controls)
)


if (
  length(positive_controls) < DANA_MIN_CONTROLS ||
  length(negative_controls) < DANA_MIN_CONTROLS
) {
  stop(
    "Insufficient valid DANA controls with the current thresholds.\n",
    "Positive controls: ",
    length(positive_controls),
    " (minimum required: ",
    DANA_MIN_CONTROLS,
    ")\n",
    "Negative controls: ",
    length(negative_controls),
    " (minimum required: ",
    DANA_MIN_CONTROLS,
    ")\n",
    "Review the prespecified threshold diagnostics. Do not add artificial ",
    "controls and do not optimize thresholds on downstream DE results.",
    call. = FALSE
  )
}


# ==============================================================================
# 5.7 Apply DANA normalization methods
# ==============================================================================

message(
  "Applying DANA normalization methods..."
)


normalized <- tryCatch(
  {
    DANA::applyNormalization(
      data = counts_dana,
      groups = groups,
      method = normalization_methods_requested
    )
  },
  error = function(e) {
    stop(
      "DANA normalization failed: ",
      conditionMessage(e),
      call. = FALSE
    )
  }
)


if (
  !is.list(normalized) ||
  length(normalized) == 0L ||
  is.null(names(normalized))
) {
  stop(
    "DANA::applyNormalization() did not return a valid named list of matrices.",
    call. = FALSE
  )
}


# Project RPM is added explicitly as the Total-Count-equivalent method.
normalized$RPM <- RPM_dana


missing_expected_methods <- setdiff(
  expected_normalized_methods,
  names(normalized)
)


if (length(missing_expected_methods) > 0L) {
  stop(
    "DANA did not return all expected normalization methods: ",
    paste(
      missing_expected_methods,
      collapse = ", "
    ),
    call. = FALSE
  )
}


unexpected_methods <- setdiff(
  names(normalized),
  expected_normalized_methods
)


if (length(unexpected_methods) > 0L) {
  warning(
    "DANA returned additional normalization method(s): ",
    paste(
      unexpected_methods,
      collapse = ", "
    ),
    call. = FALSE
  )
}


expected_samples <- colnames(counts_dana)
expected_miRNAs <- rownames(counts_dana)


normalization_method_rows <- list()


for (
  method_name in names(normalized)
) {
  normalized_matrix <- as.matrix(
    normalized[[method_name]]
  )

  storage.mode(normalized_matrix) <- "numeric"

  if (
    is.null(rownames(normalized_matrix)) ||
    is.null(colnames(normalized_matrix))
  ) {
    stop(
      "Normalization method ",
      method_name,
      " returned a matrix without row/column names.",
      call. = FALSE
    )
  }

  if (!setequal(
    colnames(normalized_matrix),
    expected_samples
  )) {
    stop(
      "Normalization method ",
      method_name,
      " returned a different set of samples.",
      call. = FALSE
    )
  }

  unknown_miRNAs <- setdiff(
    rownames(normalized_matrix),
    expected_miRNAs
  )

  if (length(unknown_miRNAs) > 0L) {
    stop(
      "Normalization method ",
      method_name,
      " returned miRNAs absent from the raw matrix: ",
      paste(
        head(
          unknown_miRNAs,
          10L
        ),
        collapse = ", "
      ),
      call. = FALSE
    )
  }

  normalized_matrix <- normalized_matrix[
    ,
    expected_samples,
    drop = FALSE
  ]

  if (
    anyNA(normalized_matrix) ||
    any(!is.finite(normalized_matrix))
  ) {
    stop(
      "Normalization method ",
      method_name,
      " produced missing or non-finite values.",
      call. = FALSE
    )
  }

  if (any(normalized_matrix < 0)) {
    stop(
      "Normalization method ",
      method_name,
      " produced negative values.",
      call. = FALSE
    )
  }

  normalized[[method_name]] <- normalized_matrix

  normalization_method_rows[[method_name]] <- data.frame(
    method = method_name,
    n_miRNAs = nrow(normalized_matrix),
    n_samples = ncol(normalized_matrix),
    full_feature_set_retained = setequal(
      rownames(normalized_matrix),
      expected_miRNAs
    ),
    all_values_finite = TRUE,
    assessment_only = TRUE,
    stringsAsFactors = FALSE
  )

  message(
    method_name,
    ": ",
    nrow(normalized_matrix),
    " miRNAs retained."
  )
}


normalization_method_summary <- do.call(
  rbind,
  normalization_method_rows
)

rownames(normalization_method_summary) <- NULL


utils::write.csv(
  normalization_method_summary,
  prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_normalization_method_summary.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 5.8 Check DANA control availability by normalization method
# ==============================================================================

control_availability <- do.call(
  rbind,
  lapply(
    names(normalized),
    function(method_name) {
      method_miRNAs <- rownames(
        normalized[[method_name]]
      )

      data.frame(
        method = method_name,
        n_miRNAs = length(method_miRNAs),
        positive_controls_available = sum(
          positive_controls %in% method_miRNAs
        ),
        negative_controls_available = sum(
          negative_controls %in% method_miRNAs
        ),
        minimum_required = DANA_MIN_CONTROLS,
        controls_sufficient = (
          sum(positive_controls %in% method_miRNAs) >= DANA_MIN_CONTROLS &&
          sum(negative_controls %in% method_miRNAs) >= DANA_MIN_CONTROLS
        ),
        stringsAsFactors = FALSE
      )
    }
  )
)

rownames(control_availability) <- NULL


utils::write.csv(
  control_availability,
  prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_control_availability_by_method.csv"
    )
  ),
  row.names = FALSE
)


print(control_availability)


if (!all(
  control_availability$controls_sufficient
)) {
  stop(
    "At least one normalization method retains fewer than ",
    DANA_MIN_CONTROLS,
    " positive controls or fewer than ",
    DANA_MIN_CONTROLS,
    " negative controls.",
    call. = FALSE
  )
}


# ==============================================================================
# 5.9 Assess normalization with original DANA metrics
# ==============================================================================

message(
  "Assessing normalization methods with original DANA cc and mscr metrics..."
)


dana_results <- tryCatch(
  {
    withCallingHandlers(
      DANA::assessNormalization(
        raw = counts_dana,
        normalized = normalized,
        negControls = negative_controls,
        posControls = positive_controls,
        clusters = clusters
      ),
      warning = function(w) {
        msg <- conditionMessage(w)

        expected_control_adjustment <- grepl(
          "negative control markers not found in normalized data set",
          msg,
          fixed = TRUE
        )

        if (expected_control_adjustment) {
          message(
            "DANA control-set adjustment: ",
            msg
          )
          invokeRestart("muffleWarning")
        }
      }
    )
  },
  error = function(e) {
    stop(
      "DANA assessment failed: ",
      conditionMessage(e),
      call. = FALSE
    )
  }
)


dana_results_table <- as.data.frame(
  dana_results,
  stringsAsFactors = FALSE
)


if (!all(
  c(
    "cc",
    "mscr"
  ) %in% colnames(dana_results_table)
)) {
  stop(
    "DANA assessment output does not contain both cc and mscr.",
    call. = FALSE
  )
}


if (
  anyNA(dana_results_table$cc) ||
  anyNA(dana_results_table$mscr) ||
  any(!is.finite(dana_results_table$cc)) ||
  any(!is.finite(dana_results_table$mscr))
) {
  stop(
    "DANA returned non-finite cc or mscr values. Assessment cannot be ",
    "interpreted reliably.",
    call. = FALSE
  )
}


if (
  is.null(rownames(dana_results_table)) ||
  all(rownames(dana_results_table) == "")
) {
  dana_results_table$method <- names(normalized)
} else {
  dana_results_table$method <- rownames(dana_results_table)
}


dana_results_table <- dana_results_table[
  ,
  c(
    "method",
    "cc",
    "mscr",
    setdiff(
      colnames(dana_results_table),
      c(
        "method",
        "cc",
        "mscr"
      )
    )
  ),
  drop = FALSE
]

rownames(dana_results_table) <- NULL


# ==============================================================================
# 6. OUTPUTS
# ==============================================================================

# ==============================================================================
# 6.1 Export DANA assessment objects and table
# ==============================================================================

saveRDS(
  dana_results,
  prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_assessment_results.rds"
    )
  )
)


utils::write.csv(
  dana_results_table,
  prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_assessment_results.csv"
    )
  ),
  row.names = FALSE
)


print(dana_results_table)


# ==============================================================================
# 6.2 Official DANA normalization-assessment figure
# ==============================================================================

message(
  "Generating official DANA normalization-assessment figure..."
)


dana_plot <- DANA::plotDANA(
  dana_results
)


if (!inherits(
  dana_plot,
  "ggplot"
)) {
  stop(
    "DANA::plotDANA() did not return a ggplot object.",
    call. = FALSE
  )
}


save_ggplot_pdf(
  plot = dana_plot,
  filename = file.path(
    dana_figures_dir,
    "DANA_normalization_assessment.pdf"
  ),
  width = 7,
  height = 5.5
)


save_ggplot_tiff(
  plot = dana_plot,
  filename = file.path(
    dana_figures_dir,
    "DANA_normalization_assessment.tiff"
  ),
  width = 7,
  height = 5.5,
  dpi = 600
)


save_ggplot_png(
  plot = dana_plot,
  filename = file.path(
    dana_figures_dir,
    "DANA_normalization_assessment.png"
  ),
  width = 7,
  height = 5.5,
  dpi = 300
)


# ==============================================================================
# 6.3 Save DANA assessment-only normalized matrices
# ==============================================================================

for (
  method_name in names(normalized)
) {
  saveRDS(
    normalized[[method_name]],
    prepare_output_file(
      file.path(
        normalized_output_dir,
        paste0(
          "normalized_",
          sanitize_filename(method_name),
          ".rds"
        )
      )
    )
  )
}


# ==============================================================================
# 7. QC / AUDIT
# ==============================================================================

# ==============================================================================
# 7.1 Final DANA QC summary
# ==============================================================================

final_qc <- data.frame(
  analysis_id = context$analysis_id,
  n_samples = ncol(counts_dana),
  n_NIA = sum(groups == "NIA"),
  n_Mild = sum(groups == "Mild"),
  n_Severe = sum(groups == "Severe"),
  n_input_miRNAs = nrow(counts_dana),
  clinical_labels_valid = clinical_labels_valid,
  RPM_sums_valid = all(
    abs(
      colSums(RPM_counts) - 1e6
    ) <= 1e-4
  ),
  RPM_TC_equivalent = rpm_tc_equivalent,
  n_miRNAs_with_DANA_coordinates = length(genes_with_coordinates),
  n_miRNAs_without_DANA_coordinates = length(genes_without_coordinates),
  n_coordinate_defined_clusters = nrow(cluster_sizes),
  n_polycistronic_clusters = length(polycistronic_cluster_names),
  n_miRNAs_in_polycistronic_clusters = length(unique(miRNAs_in_polycistronic_clusters)),
  n_positive_controls = length(positive_controls),
  n_negative_controls = length(negative_controls),
  controls_minimum_valid = (
    length(positive_controls) >= DANA_MIN_CONTROLS &&
    length(negative_controls) >= DANA_MIN_CONTROLS
  ),
  n_normalization_methods_assessed = nrow(dana_results_table),
  all_methods_have_sufficient_controls = all(
    control_availability$controls_sufficient
  ),
  all_DANA_metrics_finite = all(
    is.finite(dana_results_table$cc)
  ) && all(
    is.finite(dana_results_table$mscr)
  ),
  composite_score_used = FALSE,
  samples_removed_by_script = 0L,
  stringsAsFactors = FALSE
)


utils::write.csv(
  final_qc,
  prepare_output_file(
    file.path(
      dana_results_dir,
      "03_final_QC_summary.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 7.2 Methodological interpretation note
# ==============================================================================

interpretation_note <- c(
  "DANA assessment uses the original cc and mscr metrics.",
  "Higher cc indicates better preservation of biological correlation structure.",
  "Higher mscr indicates stronger reduction of unwanted correlation among negative controls.",
  "No post hoc composite score is calculated or used to rank normalization methods.",
  "DANA-normalized matrices are retained as normalization-assessment products only.",
  "They are not automatically substituted into the downstream differential-expression workflow.",
  "Clinical groups are inherited from script 01 as NIA, Mild and Severe.",
  "NIA means non-inflamed appendix and is not a healthy-control cohort."
)


writeLines(
  interpretation_note,
  con = prepare_output_file(
    file.path(
      dana_results_dir,
      "DANA_interpretation_note.txt"
    )
  )
)


# ==============================================================================
# 8. REPRODUCIBILITY
# ==============================================================================

write_session_info(
  dana_results_dir
)


message(
  "\n============================================================"
)
message(
  "03 DANA complete"
)
message(
  "Analysis: ",
  context$analysis_id
)
message(
  "Samples: ",
  ncol(counts_dana)
)
message(
  "NIA / Mild / Severe: ",
  sum(groups == "NIA"),
  " / ",
  sum(groups == "Mild"),
  " / ",
  sum(groups == "Severe")
)
message(
  "Input miRNAs: ",
  nrow(counts_dana)
)
message(
  "miRBase v22 coordinate coverage: ",
  length(genes_with_coordinates),
  " / ",
  length(dana_genes)
)
message(
  "Polycistronic clusters: ",
  length(polycistronic_cluster_names)
)
message(
  "Positive / negative DANA controls: ",
  length(positive_controls),
  " / ",
  length(negative_controls)
)
message(
  "Normalization methods assessed: ",
  paste(
    dana_results_table$method,
    collapse = ", "
  )
)
message(
  "RPM and Total Count equivalent: ",
  rpm_tc_equivalent
)
message(
  "No samples were removed by DANA."
)
message(
  "No composite normalization score was used."
)
message(
  "Clinical grouping inherited from script 01: NIA / Mild / Severe."
)
message(
  "============================================================\n"
)
