# ==============================================================================
# 04_DE_analysis_miRPM.R
# ==============================================================================
#
# Project:
#   Pediatric appendicitis plasma miRNA-seq
#
# Script:
#   04_DE_analysis_miRPM.R
#
# Purpose:
#   Perform RPM-based non-parametric differential-expression analysis using the
#   package-native miRPM workflow across the complete prespecified filtered
#   feature set and retain all nominal, recurrent and FDR-supported signals for
#   subsequent cross-method validation.
#
# Role in pipeline:
#   Primary RPM-based non-parametric differential-expression layer.
#
# IMPORTANT:
#   This script does NOT select or force a predefined manuscript miRNA panel.
#
#   All miRNAs retained by the prespecified expression filter are tested
#   without reference to historical candidate lists.
#
#   Candidate outputs are descriptive/exploratory summaries of the signals that
#   arise naturally from the current analysis.
#
# Clinical labels inherited from script 01:
#
#   Phenotype:
#       NIA / Mild / Severe
#
#   Phenotype_full:
#       Non-inflamed appendix
#       Mild appendicitis
#       Severe appendicitis
#
#   Appendicitis_status:
#       NIA / Appendicitis
#
#   NIA = non-inflamed appendix.
#   NIA is not a healthy-control cohort.
#
# Feature set:
#   Complete filtered miRNA set generated by script 01.
#   The feature set is inherited from the prespecified filtering step.
#
# Statistical analyses:
#
#   1. Appendicitis versus NIA
#      Mann-Whitney-Wilcoxon through miRPM.
#
#   2. Global NIA / Mild / Severe
#      Kruskal-Wallis through miRPM.
#
#   3. Prespecified pairwise clinical-group comparisons
#      NIA versus Mild
#      NIA versus Severe
#      Mild versus Severe
#
#      Each pairwise comparison is run as an independent two-group miRPM
#      analysis to preserve the intended Mann-Whitney-Wilcoxon framework.
#
# Multiple testing:
#   Primary correction:
#       Benjamini-Hochberg FDR across all tested miRNAs within each analysis.
#
#   Additional audit:
#       Holm correction.
#
#   Raw p < 0.05:
#       exploratory only.
#
# Exploratory signal tiers:
#
#   FDR_supported:
#       FDR < 0.05 in at least one prespecified analysis.
#
#   recurrent_nominal:
#       raw p < 0.05 in at least two prespecified analyses but no FDR < 0.05.
#
#   single_nominal:
#       raw p < 0.05 in exactly one prespecified analysis but no FDR < 0.05.
#
#   no_nominal_signal:
#       no raw p < 0.05 in any prespecified analysis.
#
# IMPORTANT:
#   These tiers are NOT additional hypothesis tests and do not alter p-values.
#   The five analyses are not statistically independent, so recurrence counts
#   are descriptive only. Their purpose is to preserve potentially relevant
#   signals for subsequent edgeR/DESeq2 and integrated-method validation.
#
# Visualization:
#   Candidate heatmaps:
#       row Z-scores of log2(RPM + 1).
#
#   Candidate PCA:
#       explicitly exploratory/post-selection.
#
#   Raw-p and FDR candidate plots are contrast-specific visualization aids and
#   must not be interpreted as independent validation.
#
# No sample or miRNA is removed in this script beyond the frozen feature set
# inherited from script 01.
#
# Inputs:
#   results/<analysis_id>/filtered_RPM.rds
#   results/<analysis_id>/metadata_analysis_samples.rds
#
# Main outputs:
#   results/<analysis_id>/de_rpm/
#
#     DE_RPM_analysis_manifest.csv
#     DE_RPM_analysis_summary.csv
#     DE_RPM_results.xlsx
#
#     DE_RPM_all_contrasts_long.csv
#     DE_RPM_candidate_signal_summary.csv
#     DE_RPM_candidate_any_nominal.csv
#     DE_RPM_candidate_recurrent_nominal.csv
#     DE_RPM_candidate_FDR_supported.csv
#
#     Candidate-set exploratory visualizations:
#       figures/<analysis_id>/de_rpm/hm/summary/
#       figures/<analysis_id>/de_rpm/pca/summary/
#
#       - any nominal signal set (p < 0.05 in >=1 analysis)
#       - recurrent nominal signal set (p < 0.05 in >=2 analyses)
#
#     tab/
#       complete result tables for every analysis
#
#     cand/raw/
#       nominal raw-p candidate sets
#
#     cand/fdr/
#       BH-FDR candidate sets
#
#     cand/holm/
#       Holm candidate sets
#
#     04_final_QC_summary.csv
#
# Reproducibility:
#   Clinical labels and cohort membership are inherited from script 01.
#   This script never recreates 0/1/2 clinical labels independently.
#   No historical candidate list is used as an analysis input.
#
# ==============================================================================


# ==============================================================================
# 1. DEPENDENCIES
# ==============================================================================

required_packages <- c(
  "here",
  "dplyr",
  "ggplot2",
  "ComplexHeatmap",
  "circlize",
  "openxlsx",
  "miRPM"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]

if (
  length(
    missing_packages
  ) > 0L
) {
  stop(
    "Missing package(s) required by R/04_DE_analysis_miRPM.R:\n",
    paste(
      "-",
      missing_packages,
      collapse = "\n"
    ),
    "\nRun R/00_packages_setup.R first.",
    call. = FALSE
  )
}

source(
  here::here(
    "R",
    "00_analysis_config.R"
  )
)

source(
  here::here(
    "R",
    "00_utils.R"
  )
)

if (
  utils::compareVersion(
    as.character(
      utils::packageVersion(
        "miRPM"
      )
    ),
    "0.2.0"
  ) < 0
) {
  stop(
    "miRPM >= 0.2.0 is required. Run R/00_packages_setup.R to update it.",
    call. = FALSE
  )
}

if (!exists(
  "perform_statistical_tests",
  where = asNamespace(
    "miRPM"
  ),
  inherits = FALSE
)) {
  stop(
    "The installed miRPM version does not expose perform_statistical_tests().",
    call. = FALSE
  )
}


# ==============================================================================
# 2. CONFIGURATION
# ==============================================================================

context <- get_analysis_context()

results_dir <- context$results_dir
figures_dir <- context$figures_dir

alpha_raw <- ALPHA_RAW
alpha_fdr <- ALPHA_FDR

de_results_dir <- file.path(
  results_dir,
  "de_rpm"
)

de_figures_dir <- file.path(
  figures_dir,
  "de_rpm"
)

tables_dir <- file.path(
  de_results_dir,
  "tab"
)

candidate_dir <- file.path(
  de_results_dir,
  "cand"
)

candidate_raw_dir <- file.path(
  candidate_dir,
  "raw"
)

candidate_fdr_dir <- file.path(
  candidate_dir,
  "fdr"
)

candidate_holm_dir <- file.path(
  candidate_dir,
  "holm"
)

native_dir <- file.path(
  de_results_dir,
  "native"
)

effect_plot_dir <- file.path(
  de_figures_dir,
  "effect"
)

expression_plot_dir <- file.path(
  de_figures_dir,
  "expr"
)

heatmap_dir <- file.path(
  de_figures_dir,
  "hm"
)

heatmap_raw_dir <- file.path(
  heatmap_dir,
  "raw"
)

heatmap_fdr_dir <- file.path(
  heatmap_dir,
  "fdr"
)

candidate_pca_dir <- file.path(
  de_figures_dir,
  "pca"
)

candidate_pca_raw_dir <- file.path(
  candidate_pca_dir,
  "raw"
)

candidate_pca_fdr_dir <- file.path(
  candidate_pca_dir,
  "fdr"
)

candidate_summary_heatmap_dir <- file.path(
  heatmap_dir,
  "summary"
)

candidate_summary_pca_dir <- file.path(
  candidate_pca_dir,
  "summary"
)

directories <- c(
  de_results_dir,
  de_figures_dir,
  tables_dir,
  candidate_dir,
  candidate_raw_dir,
  candidate_fdr_dir,
  candidate_holm_dir,
  native_dir,
  effect_plot_dir,
  expression_plot_dir,
  heatmap_dir,
  heatmap_raw_dir,
  heatmap_fdr_dir,
  candidate_pca_dir,
  candidate_pca_raw_dir,
  candidate_pca_fdr_dir,
  candidate_summary_heatmap_dir,
  candidate_summary_pca_dir
)

for (
  directory in directories
) {
  ensure_dir(
    directory
  )
}

contrast_code <- function(
    contrast_name
) {
  codes <- c(
    Appendicitis_vs_NIA = "AvN",
    Phenotype_global = "Pg",
    NIA_vs_Mild = "NvM",
    NIA_vs_Severe = "NvS",
    Mild_vs_Severe = "MvS"
  )

  code <- unname(
    codes[
      contrast_name
    ]
  )

  if (
    length(
      code
    ) != 1L ||
    is.na(
      code
    )
  ) {
    stop(
      "Unknown contrast name: ",
      contrast_name,
      call. = FALSE
    )
  }

  code
}

output_path_dictionary <- data.frame(
  type = "contrast",
  code = c(
    "AvN",
    "Pg",
    "NvM",
    "NvS",
    "MvS"
  ),
  label = c(
    "Appendicitis_vs_NIA",
    "Phenotype_global",
    "NIA_vs_Mild",
    "NIA_vs_Severe",
    "Mild_vs_Severe"
  ),
  stringsAsFactors = FALSE
)

utils::write.csv(
  output_path_dictionary,
  prepare_output_file(
    file.path(
      de_results_dir,
      "output_path_dictionary.csv"
    )
  ),
  row.names = FALSE
)

message(
  "\n============================================================"
)

message(
  "04_DE_analysis_miRPM.R"
)

message(
  "Analysis ID: ",
  context$analysis_id
)

message(
  "Role: ",
  context$role
)

message(
  "Expected n: ",
  context$expected_n
)

message(
  "Data-driven candidate signal tracking enabled."
)

message(
  "============================================================\n"
)


# ==============================================================================
# 3. INPUTS
# ==============================================================================

required_files <- c(
  filtered_RPM = file.path(
    results_dir,
    "filtered_RPM.rds"
  ),
  metadata = file.path(
    results_dir,
    "metadata_analysis_samples.rds"
  )
)

missing_files <- required_files[
  !file.exists(
    required_files
  )
]

if (length(missing_files) > 0) {
  stop(
    "Missing input files generated by script 01:\n",
    paste(
      "-",
      missing_files,
      collapse = "\n"
    )
  )
}

rpm <- readRDS(
  required_files[["filtered_RPM"]]
)

metadata <- readRDS(
  required_files[["metadata"]]
)

rpm <- as.matrix(
  rpm
)

metadata <- as.data.frame(
  metadata,
  stringsAsFactors = FALSE
)

metadata$Sample <- as.character(
  metadata$Sample
)

storage.mode(
  rpm
) <- "numeric"


# ==============================================================================
# 4. VALIDATION
# ==============================================================================

# ==============================================================================
# 4.1 Validate and align inputs
# ==============================================================================

required_metadata_columns <- c(
  "Sample",
  "Apend_type",
  "Phenotype",
  "Phenotype_full",
  "Appendicitis_status"
)

missing_metadata_columns <- setdiff(
  required_metadata_columns,
  colnames(
    metadata
  )
)

if (length(missing_metadata_columns) > 0) {
  stop(
    "Missing required metadata columns: ",
    paste(
      missing_metadata_columns,
      collapse = ", "
    )
  )
}

if (anyDuplicated(metadata$Sample) > 0) {
  stop(
    "Duplicated sample identifiers detected in metadata."
  )
}

if (anyDuplicated(colnames(rpm)) > 0) {
  stop(
    "Duplicated sample identifiers detected in the RPM matrix."
  )
}

if (anyDuplicated(rownames(rpm)) > 0) {
  stop(
    "Duplicated miRNA identifiers detected in the RPM matrix."
  )
}

if (!setequal(
  colnames(rpm),
  metadata$Sample
)) {
  stop(
    "RPM matrix and metadata contain different samples."
  )
}

if (
  anyNA(rpm) ||
  any(!is.finite(rpm)) ||
  any(rpm < 0)
) {
  stop(
    "RPM matrix contains missing, non-finite or negative values."
  )
}

metadata <- metadata[
  match(
    colnames(rpm),
    metadata$Sample
  ),
  ,
  drop = FALSE
]

rownames(
  metadata
) <- metadata$Sample

metadata$Apend_type <- factor(
  as.character(
    metadata$Apend_type
  ),
  levels = c(
    "0",
    "1",
    "2"
  )
)

metadata$Phenotype <- factor(
  as.character(
    metadata$Phenotype
  ),
  levels = c(
    "NIA",
    "Mild",
    "Severe"
  )
)

metadata$Phenotype_full <- factor(
  as.character(
    metadata$Phenotype_full
  ),
  levels = c(
    "Non-inflamed appendix",
    "Mild appendicitis",
    "Severe appendicitis"
  )
)

metadata$Appendicitis_status <- factor(
  as.character(
    metadata$Appendicitis_status
  ),
  levels = c(
    "NIA",
    "Appendicitis"
  )
)

if (anyNA(metadata$Apend_type)) {
  stop(
    "Apend_type contains missing or unexpected values."
  )
}

if (anyNA(metadata$Phenotype)) {
  stop(
    "Phenotype contains missing or unexpected values."
  )
}

if (anyNA(metadata$Phenotype_full)) {
  stop(
    "Phenotype_full contains missing or unexpected values."
  )
}

if (anyNA(metadata$Appendicitis_status)) {
  stop(
    "Appendicitis_status contains missing or unexpected values."
  )
}

expected_phenotype <- c(
  "0" = "NIA",
  "1" = "Mild",
  "2" = "Severe"
)[
  as.character(
    metadata$Apend_type
  )
]

expected_phenotype_full <- c(
  "0" = "Non-inflamed appendix",
  "1" = "Mild appendicitis",
  "2" = "Severe appendicitis"
)[
  as.character(
    metadata$Apend_type
  )
]

expected_appendicitis_status <- ifelse(
  as.character(
    metadata$Apend_type
  ) == "0",
  "NIA",
  "Appendicitis"
)

if (!identical(
  as.character(metadata$Phenotype),
  unname(expected_phenotype)
)) {
  stop(
    "Phenotype is inconsistent with Apend_type. Re-run script 01."
  )
}

if (!identical(
  as.character(metadata$Phenotype_full),
  unname(expected_phenotype_full)
)) {
  stop(
    "Phenotype_full is inconsistent with Apend_type. Re-run script 01."
  )
}

if (!identical(
  as.character(metadata$Appendicitis_status),
  expected_appendicitis_status
)) {
  stop(
    "Appendicitis_status is inconsistent with Apend_type. Re-run script 01."
  )
}

if (!identical(
  metadata$Sample,
  colnames(rpm)
)) {
  stop(
    "Metadata and RPM samples are not identically ordered."
  )
}

message(
  "Loaded and aligned: ",
  nrow(rpm),
  " miRNAs x ",
  ncol(rpm),
  " samples."
)

message(
  "Appendicitis status: ",
  paste(
    names(
      table(
        metadata$Appendicitis_status
      )
    ),
    as.integer(
      table(
        metadata$Appendicitis_status
      )
    ),
    collapse = "; "
  )
)

message(
  "Clinical groups: ",
  paste(
    names(
      table(
        metadata$Phenotype
      )
    ),
    as.integer(
      table(
        metadata$Phenotype
      )
    ),
    collapse = "; "
  )
)

if (
  ncol(rpm) != nrow(metadata)
) {
  stop(
    "RPM matrix and metadata contain different numbers of samples.",
    call. = FALSE
  )
}


# ==============================================================================
# 4.2 Record miRPM version and analysis settings
# ==============================================================================

mirpm_manifest <- data.frame(
  analysis_id = context$analysis_id,
  miRPM_version = as.character(
    utils::packageVersion(
      "miRPM"
    )
  ),
  n_samples = ncol(rpm),
  n_NIA = sum(
    metadata$Phenotype == "NIA"
  ),
  n_Mild = sum(
    metadata$Phenotype == "Mild"
  ),
  n_Severe = sum(
    metadata$Phenotype == "Severe"
  ),
  n_Appendicitis = sum(
    metadata$Appendicitis_status == "Appendicitis"
  ),
  n_miRNAs_tested = nrow(rpm),
  primary_adjustment = "BH",
  alpha_FDR = alpha_fdr,
  alpha_raw_exploratory = alpha_raw,
  RPM_pseudocount_for_descriptive_log2_ratio = 1,
  candidate_heatmap_transformation = "row Z-score of log2(RPM + 1)",
  stringsAsFactors = FALSE
)

utils::write.csv(
  mirpm_manifest,
  file.path(
    de_results_dir,
    "DE_RPM_analysis_manifest.csv"
  ),
  row.names = FALSE
)


# ==============================================================================
# 5. ANALYSIS / PROCESSING
# ==============================================================================

# ==============================================================================
# 5.1 Visualization matrix
# ==============================================================================

# This is for visualization only and is not used for statistical testing.
log2_rpm <- log2(
  rpm + 1
)

heatmap_z <- t(
  scale(
    t(
      log2_rpm
    )
  )
)

heatmap_z[
  !is.finite(
    heatmap_z
  )
] <- 0

storage.mode(
  heatmap_z
) <- "numeric"


# ==============================================================================
# 5.2 Helper functions
# ==============================================================================

phenotype_label <- function(
    group_name
) {

  valid_groups <- c(
    "NIA",
    "Mild",
    "Severe"
  )

  group_name <- as.character(
    group_name
  )

  if (
    length(group_name) != 1L ||
    !group_name %in% valid_groups
  ) {
    stop(
      "Unknown phenotype group: ",
      paste(
        group_name,
        collapse = ", "
      ),
      call. = FALSE
    )
  }

  group_name
}


sanitize_filename_local <- function(
    x
) {

  gsub(
    "[^A-Za-z0-9._-]",
    "_",
    x
  )
}


add_audit_significance <- function(
    results_table
) {

  results_table$Holm <- stats::p.adjust(
    results_table$p_value,
    method = "holm"
  )

  results_table$raw_significant <- (
    !is.na(
      results_table$p_value
    ) &
      results_table$p_value < alpha_raw
  )

  results_table$fdr_significant <- (
    !is.na(
      results_table$FDR
    ) &
      results_table$FDR < alpha_fdr
  )

  results_table$holm_significant <- (
    !is.na(
      results_table$Holm
    ) &
      results_table$Holm < alpha_fdr
  )

  results_table$significance_class <- dplyr::case_when(
    results_table$fdr_significant ~ "FDR < 0.05",
    results_table$raw_significant ~ "Raw p < 0.05 only",
    TRUE ~ "Not significant"
  )

  results_table
}


save_result_sets <- function(
    results_table,
    contrast_name
) {

  all_results <- results_table |>
    dplyr::arrange(
      FDR,
      p_value
    )

  raw_candidates <- all_results |>
    dplyr::filter(
      raw_significant
    )

  fdr_candidates <- all_results |>
    dplyr::filter(
      fdr_significant
    )

  holm_candidates <- all_results |>
    dplyr::filter(
      holm_significant
    )

  short_name <- paste0(
    contrast_code(contrast_name),
    ".csv"
  )

  utils::write.csv(
    all_results,
    file.path(
      tables_dir,
      short_name
    ),
    row.names = FALSE
  )

  utils::write.csv(
    raw_candidates,
    file.path(
      candidate_raw_dir,
      short_name
    ),
    row.names = FALSE
  )

  utils::write.csv(
    fdr_candidates,
    file.path(
      candidate_fdr_dir,
      short_name
    ),
    row.names = FALSE
  )

  utils::write.csv(
    holm_candidates,
    file.path(
      candidate_holm_dir,
      short_name
    ),
    row.names = FALSE
  )

  list(
    all = all_results,
    raw = raw_candidates,
    fdr = fdr_candidates,
    holm = holm_candidates
  )
}


run_mirpm_two_group <- function(
    rpm_matrix,
    metadata_subset,
    condition,
    group_order,
    contrast_name,
    positive_effect_label
) {

  result <- miRPM::perform_statistical_tests(
    miRNA_ftd = rpm_matrix,
    metadata = metadata_subset,
    condition = condition,
    output_file = NULL,
    assign_results = FALSE,
    alpha = alpha_fdr,
    p_adjust_method = "BH",
    detection_threshold = 0,
    pseudocount = 1,
    group_order = group_order,
    write_excel = FALSE
  )

  if (!identical(
    result$analysis_type,
    "two_group"
  )) {
    stop(
      contrast_name,
      " did not return a two-group miRPM analysis."
    )
  }

  results_table <- as.data.frame(
    result$results
  )

  results_table <- add_audit_significance(
    results_table
  )

  results_table$effect_direction_definition <- positive_effect_label

  results_table$direction <- dplyr::case_when(
    results_table$log2_median_ratio_group_1_vs_group_2 > 0 ~
      paste0(
        "Higher_in_",
        group_order[1]
      ),
    results_table$log2_median_ratio_group_1_vs_group_2 < 0 ~
      paste0(
        "Higher_in_",
        group_order[2]
      ),
    TRUE ~ "No_change"
  )

  saveRDS(
    result,
    file.path(
      native_dir,
      paste0(
        contrast_code(contrast_name),
        ".rds"
      )
    )
  )

  saved_sets <- save_result_sets(
    results_table,
    contrast_name
  )

  list(
    native = result,
    all_results = saved_sets$all,
    raw_candidates = saved_sets$raw,
    fdr_candidates = saved_sets$fdr,
    holm_candidates = saved_sets$holm
  )
}


plot_fdr_effect_summary <- function(
    analysis_result,
    contrast_name,
    title,
    x_label
) {

  plotting_table <- analysis_result$fdr_candidates

  if (nrow(plotting_table) == 0) {
    message(
      "No FDR < 0.05 candidates for effect plot: ",
      contrast_name
    )

    return(
      invisible(
        NULL
      )
    )
  }

  plotting_table <- plotting_table |>
    dplyr::arrange(
      log2_median_ratio_group_1_vs_group_2
    )

  plotting_table$miRNA <- factor(
    plotting_table$miRNA,
    levels = plotting_table$miRNA
  )

  plot_object <- ggplot2::ggplot(
    plotting_table,
    ggplot2::aes(
      x = log2_median_ratio_group_1_vs_group_2,
      y = miRNA
    )
  ) +
    ggplot2::geom_vline(
      xintercept = 0,
      linetype = "dashed",
      linewidth = 0.5
    ) +
    ggplot2::geom_segment(
      ggplot2::aes(
        x = 0,
        xend = log2_median_ratio_group_1_vs_group_2,
        yend = miRNA
      ),
      linewidth = 0.6
    ) +
    ggplot2::geom_point(
      size = 2.8
    ) +
    ggplot2::labs(
      title = title,
      subtitle = "RPM-based Mann-Whitney-Wilcoxon; BH-FDR < 0.05",
      x = x_label,
      y = NULL
    ) +
    ggplot2::theme_classic(
      base_size = 11
    ) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(
        face = "bold"
      )
    )

  figure_height <- max(
    4,
    min(
      10,
      0.35 * nrow(
        plotting_table
      ) + 2
    )
  )

  short_name <- contrast_code(
    contrast_name
  )

  save_ggplot_pdf(
    plot = plot_object,
    filename = file.path(
      effect_plot_dir,
      paste0(
        short_name,
        ".pdf"
      )
    ),
    width = 7,
    height = figure_height
  )

  save_ggplot_tiff(
    plot = plot_object,
    filename = file.path(
      effect_plot_dir,
      paste0(
        short_name,
        ".tiff"
      )
    ),
    width = 7,
    height = figure_height,
    dpi = 600
  )

  invisible(
    plot_object
  )
}


plot_fdr_expression <- function(
    analysis_result,
    contrast_name,
    metadata_subset,
    group_variable,
    plot_group_order,
    plot_group_labels
) {

  candidates <- analysis_result$fdr_candidates$miRNA

  if (length(candidates) == 0) {
    message(
      "No FDR < 0.05 candidates for expression plots: ",
      contrast_name
    )

    return(
      invisible(
        NULL
      )
    )
  }

  plot_metadata <- metadata_subset

  plot_metadata[[group_variable]] <- factor(
    as.character(
      plot_metadata[[group_variable]]
    ),
    levels = plot_group_order,
    labels = plot_group_labels
  )

  for (miRNA_id in candidates) {

    plot_data <- data.frame(
      Sample = plot_metadata$Sample,
      RPM = as.numeric(
        rpm[
          miRNA_id,
          plot_metadata$Sample
        ]
      ),
      Group = plot_metadata[[group_variable]],
      stringsAsFactors = FALSE
    )

    plot_object <- ggplot2::ggplot(
      plot_data,
      ggplot2::aes(
        x = Group,
        y = RPM
      )
    ) +
      ggplot2::geom_boxplot(
        width = 0.32,
        outlier.shape = NA,
        linewidth = 0.6
      ) +
      ggplot2::geom_jitter(
        width = 0.10,
        height = 0,
        size = 2,
        alpha = 0.8
      ) +
      ggplot2::labs(
        title = miRNA_id,
        subtitle = "RPM-based result; BH-FDR < 0.05",
        x = NULL,
        y = "Expression (RPM)"
      ) +
      ggplot2::theme_classic(
        base_size = 11
      ) +
      ggplot2::theme(
        plot.title = ggplot2::element_text(
          face = "bold",
          hjust = 0.5
        ),
        plot.subtitle = ggplot2::element_text(
          hjust = 0.5
        )
      )

    safe_name <- sanitize_filename_local(
      miRNA_id
    )

    figure_prefix <- paste0(
      contrast_code(contrast_name),
      "_",
      safe_name
    )

    save_ggplot_pdf(
      plot = plot_object,
      filename = file.path(
        expression_plot_dir,
        paste0(
          figure_prefix,
          ".pdf"
        )
      ),
      width = 5,
      height = 4.5
    )

    save_ggplot_tiff(
      plot = plot_object,
      filename = file.path(
        expression_plot_dir,
        paste0(
          figure_prefix,
          ".tiff"
        )
      ),
      width = 5,
      height = 4.5,
      dpi = 600
    )
  }

  invisible(
    NULL
  )
}


save_candidate_heatmap <- function(
    selected_miRNAs,
    contrast_name,
    metadata_subset,
    group_variable,
    group_levels,
    group_labels,
    candidate_type = c(
      "raw",
      "fdr"
    )
) {

  candidate_type <- match.arg(
    candidate_type
  )

  selected_miRNAs <- intersect(
    unique(
      selected_miRNAs
    ),
    rownames(
      heatmap_z
    )
  )

  candidate_label <- if (
    candidate_type == "raw"
  ) {
    "raw p < 0.05"
  } else {
    "BH-FDR < 0.05"
  }

  output_dir <- if (
    candidate_type == "raw"
  ) {
    heatmap_raw_dir
  } else {
    heatmap_fdr_dir
  }

  if (length(selected_miRNAs) == 0) {
    message(
      "Candidate heatmap skipped for ",
      contrast_name,
      " [",
      candidate_label,
      "]: no candidate miRNAs."
    )

    return(
      invisible(
        NULL
      )
    )
  }

  heatmap_metadata <- metadata_subset

  heatmap_metadata[[group_variable]] <- factor(
    as.character(
      heatmap_metadata[[group_variable]]
    ),
    levels = group_levels,
    labels = group_labels
  )

  heatmap_metadata <- heatmap_metadata |>
    dplyr::arrange(
      .data[[group_variable]],
      Sample
    )

  ordered_samples <- heatmap_metadata$Sample

  heatmap_matrix <- heatmap_z[
    selected_miRNAs,
    ordered_samples,
    drop = FALSE
  ]

  annotation <- ComplexHeatmap::HeatmapAnnotation(
    Group = heatmap_metadata[[group_variable]],
    annotation_name_side = "left"
  )

  heatmap_object <- ComplexHeatmap::Heatmap(
    heatmap_matrix,
    name = "Row Z-score",
    col = circlize::colorRamp2(
      c(
        -2,
        0,
        2
      ),
      c(
        "navy",
        "white",
        "firebrick3"
      )
    ),
    top_annotation = annotation,
    column_split = heatmap_metadata[[group_variable]],
    cluster_rows = length(selected_miRNAs) > 1L,
    cluster_columns = FALSE,
    show_column_names = FALSE,
    show_row_names = TRUE,
    row_names_gp = grid::gpar(
      fontsize = 8
    ),
    column_title = paste0(
      contrast_name,
      " — ",
      candidate_label
    ),
    use_raster = FALSE
  )

  short_name <- contrast_code(
    contrast_name
  )

  pdf_file <- file.path(
    output_dir,
    paste0(
      short_name,
      ".pdf"
    )
  )

  tiff_file <- file.path(
    output_dir,
    paste0(
      short_name,
      ".tiff"
    )
  )

  figure_height <- max(
    4.5,
    min(
      10,
      0.28 * length(
        selected_miRNAs
      ) + 3
    )
  )

  draw_heatmap <- function() {
    ComplexHeatmap::draw(
      heatmap_object,
      heatmap_legend_side = "right",
      annotation_legend_side = "right"
    )
  }

  draw_to_pdf(
    filename = pdf_file,
    width = 7,
    height = figure_height,
    draw = draw_heatmap
  )

  draw_to_tiff(
    filename = tiff_file,
    width = 7,
    height = figure_height,
    units = "in",
    res = 600,
    compression = "lzw",
    draw = draw_heatmap
  )

  invisible(
    heatmap_object
  )
}



# ------------------------------------------------------------------------------
# Candidate PCA helper
# ------------------------------------------------------------------------------

# Candidate PCA is deliberately post-selection and therefore exploratory.
# Two versions are generated:
#   - raw p < 0.05 candidates
#   - BH-FDR < 0.05 candidates
#
# These PCA plots must not be interpreted as independent evidence that groups
# separate, because the features were selected using the same outcome labels.

save_candidate_pca <- function(
    selected_miRNAs,
    contrast_name,
    metadata_subset,
    group_variable,
    group_levels,
    group_labels,
    candidate_type = c(
      "raw",
      "fdr"
    ),
    ellipse_level = 0.95
) {

  candidate_type <- match.arg(
    candidate_type
  )

  selected_miRNAs <- intersect(
    unique(
      selected_miRNAs
    ),
    rownames(
      rpm
    )
  )

  candidate_label <- if (
    candidate_type == "raw"
  ) {
    "raw p < 0.05"
  } else {
    "BH-FDR < 0.05"
  }

  output_dir <- if (
    candidate_type == "raw"
  ) {
    candidate_pca_raw_dir
  } else {
    candidate_pca_fdr_dir
  }

  if (length(selected_miRNAs) < 2L) {
    message(
      "Candidate PCA skipped for ",
      contrast_name,
      " [",
      candidate_label,
      "]: fewer than 2 candidate miRNAs."
    )

    return(
      invisible(
        NULL
      )
    )
  }

  pca_metadata <- metadata_subset[
    metadata_subset$Sample %in%
      colnames(
        rpm
      ),
    ,
    drop = FALSE
  ]

  pca_metadata <- pca_metadata[
    match(
      colnames(
        rpm[
          ,
          pca_metadata$Sample,
          drop = FALSE
        ]
      ),
      pca_metadata$Sample
    ),
    ,
    drop = FALSE
  ]

  pca_samples <- pca_metadata$Sample

  candidate_log2_rpm <- log2(
    rpm[
      selected_miRNAs,
      pca_samples,
      drop = FALSE
    ] + 1
  )

  feature_sd <- apply(
    candidate_log2_rpm,
    1,
    stats::sd
  )

  usable_features <- (
    is.finite(
      feature_sd
    ) &
      feature_sd > 0
  )

  candidate_log2_rpm <- candidate_log2_rpm[
    usable_features,
    ,
    drop = FALSE
  ]

  if (nrow(candidate_log2_rpm) < 2L) {
    message(
      "Candidate PCA skipped for ",
      contrast_name,
      " [",
      candidate_label,
      "]: fewer than 2 non-zero-variance candidate miRNAs."
    )

    return(
      invisible(
        NULL
      )
    )
  }

  pca_input <- t(
    candidate_log2_rpm
  )

  pca <- stats::prcomp(
    pca_input,
    center = TRUE,
    scale. = TRUE
  )

  if (ncol(pca$x) < 2L) {
    message(
      "Candidate PCA skipped for ",
      contrast_name,
      " [",
      candidate_label,
      "]: PCA returned fewer than 2 components."
    )

    return(
      invisible(
        NULL
      )
    )
  }

  variance <- (
    pca$sdev^2
  ) / sum(
    pca$sdev^2
  )

  pca_df <- data.frame(
    Sample = rownames(
      pca$x
    ),
    PC1 = pca$x[, 1],
    PC2 = pca$x[, 2],
    stringsAsFactors = FALSE
  )

  if (ncol(pca$x) >= 3L) {
    pca_df$PC3 <- pca$x[, 3]
  }

  pca_df <- dplyr::left_join(
    pca_df,
    pca_metadata,
    by = "Sample"
  )

  pca_df$Plot_group <- factor(
    as.character(
      pca_df[[group_variable]]
    ),
    levels = group_levels,
    labels = group_labels
  )

  utils::write.csv(
    pca_df,
    file.path(
      output_dir,
      paste0(
        contrast_code(contrast_name),
        "_coords.csv"
      )
    ),
    row.names = FALSE
  )

  candidate_variance <- data.frame(
    PC = paste0(
      "PC",
      seq_along(
        variance
      )
    ),
    variance_explained = variance,
    variance_explained_pct = 100 * variance,
    cumulative_variance_explained_pct = 100 * cumsum(
      variance
    ),
    stringsAsFactors = FALSE
  )

  utils::write.csv(
    candidate_variance,
    file.path(
      output_dir,
      paste0(
        contrast_code(contrast_name),
        "_var.csv"
      )
    ),
    row.names = FALSE
  )

  candidate_manifest <- data.frame(
    contrast = contrast_name,
    candidate_definition = candidate_label,
    miRNA = rownames(
      candidate_log2_rpm
    ),
    stringsAsFactors = FALSE
  )

  utils::write.csv(
    candidate_manifest,
    file.path(
      output_dir,
      paste0(
        contrast_code(contrast_name),
        "_mirnas.csv"
      )
    ),
    row.names = FALSE
  )

  group_counts <- table(
    pca_df$Plot_group
  )

  eligible_groups <- names(
    group_counts[
      group_counts >= 3
    ]
  )

  ellipse_data <- pca_df[
    as.character(
      pca_df$Plot_group
    ) %in%
      eligible_groups,
    ,
    drop = FALSE
  ]

  p <- ggplot2::ggplot(
    pca_df,
    ggplot2::aes(
      x = PC1,
      y = PC2,
      color = Plot_group
    )
  )

  if (nrow(ellipse_data) > 0) {
    p <- p +
      ggplot2::stat_ellipse(
        data = ellipse_data,
        ggplot2::aes(
          fill = Plot_group
        ),
        geom = "polygon",
        type = "norm",
        level = ellipse_level,
        alpha = 0.12,
        color = NA,
        show.legend = FALSE
      ) +
      ggplot2::stat_ellipse(
        data = ellipse_data,
        type = "norm",
        level = ellipse_level,
        linewidth = 0.6,
        alpha = 0.85,
        show.legend = FALSE
      )
  }

  p <- p +
    ggplot2::geom_point(
      size = 3,
      alpha = 0.95
    ) +
    ggplot2::labs(
      title = paste0(
        "Candidate PCA — ",
        contrast_name
      ),
      subtitle = paste0(
        nrow(
          candidate_log2_rpm
        ),
        " miRNAs selected at ",
        candidate_label,
        "; exploratory post-selection visualization"
      ),
      x = sprintf(
        "PC1 (%.1f%%)",
        100 * variance[1]
      ),
      y = sprintf(
        "PC2 (%.1f%%)",
        100 * variance[2]
      ),
      color = NULL
    ) +
    ggplot2::theme_classic(
      base_size = 10
    ) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(
        face = "bold"
      ),
      legend.position = "right"
    )

  pca_prefix <- contrast_code(
    contrast_name
  )

  save_ggplot_pdf(
    plot = p,
    filename = file.path(
      output_dir,
      paste0(
        pca_prefix,
        "_pc12.pdf"
      )
    ),
    width = 7,
    height = 5
  )

  save_ggplot_tiff(
    plot = p,
    filename = file.path(
      output_dir,
      paste0(
        pca_prefix,
        "_pc12.tiff"
      )
    ),
    width = 7,
    height = 5,
    dpi = 600
  )

  if (ncol(pca$x) >= 3L) {

    p13 <- ggplot2::ggplot(
      pca_df,
      ggplot2::aes(
        x = PC1,
        y = PC3,
        color = Plot_group
      )
    )

    if (nrow(ellipse_data) > 0) {
      p13 <- p13 +
        ggplot2::stat_ellipse(
          data = ellipse_data,
          ggplot2::aes(
            fill = Plot_group
          ),
          geom = "polygon",
          type = "norm",
          level = ellipse_level,
          alpha = 0.12,
          color = NA,
          show.legend = FALSE
        ) +
        ggplot2::stat_ellipse(
          data = ellipse_data,
          type = "norm",
          level = ellipse_level,
          linewidth = 0.6,
          alpha = 0.85,
          show.legend = FALSE
        )
    }

    p13 <- p13 +
      ggplot2::geom_point(
        size = 3,
        alpha = 0.95
      ) +
      ggplot2::labs(
        title = paste0(
          "Candidate PCA — ",
          contrast_name
        ),
        subtitle = paste0(
          nrow(
            candidate_log2_rpm
          ),
          " miRNAs selected at ",
          candidate_label,
          "; exploratory post-selection visualization"
        ),
        x = sprintf(
          "PC1 (%.1f%%)",
          100 * variance[1]
        ),
        y = sprintf(
          "PC3 (%.1f%%)",
          100 * variance[3]
        ),
        color = NULL
      ) +
      ggplot2::theme_classic(
        base_size = 10
      ) +
      ggplot2::theme(
        plot.title = ggplot2::element_text(
          face = "bold"
        ),
        legend.position = "right"
      )

    save_ggplot_pdf(
      plot = p13,
      filename = file.path(
        output_dir,
        paste0(
          pca_prefix,
          "_pc13.pdf"
        )
      ),
      width = 7,
      height = 5
    )
  }

  invisible(
    list(
      pca = pca,
      coordinates = pca_df,
      variance = candidate_variance,
      miRNAs = rownames(
        candidate_log2_rpm
      ),
      candidate_type = candidate_type,
      plot_PC1_PC2 = p
    )
  )
}


# ==============================================================================
# 5.3 Appendicitis versus NIA
# ==============================================================================

message(
  "Running miRPM Appendicitis versus NIA analysis..."
)

# Group order is intentionally Appendicitis, NIA so that positive effect
# estimates mean higher expression in appendicitis.

condition_analysis <- run_mirpm_two_group(
  rpm_matrix = rpm,
  metadata_subset = metadata,
  condition = "Appendicitis_status",
  group_order = c(
    "Appendicitis",
    "NIA"
  ),
  contrast_name = "Appendicitis_vs_NIA",
  positive_effect_label = "Positive effect = higher in Appendicitis than NIA"
)

plot_fdr_effect_summary(
  condition_analysis,
  contrast_name = "Appendicitis_vs_NIA",
  title = "RPM differential expression: Appendicitis versus NIA",
  x_label = "Log2 median ratio (Appendicitis / NIA)"
)

plot_fdr_expression(
  condition_analysis,
  contrast_name = "Appendicitis_vs_NIA",
  metadata_subset = metadata,
  group_variable = "Appendicitis_status",
  plot_group_order = c(
    "NIA",
    "Appendicitis"
  ),
  plot_group_labels = c(
    "NIA",
    "Appendicitis"
  )
)

save_candidate_heatmap(
  selected_miRNAs = condition_analysis$raw_candidates$miRNA,
  contrast_name = "Appendicitis_vs_NIA",
  metadata_subset = metadata,
  group_variable = "Appendicitis_status",
  group_levels = c(
    "NIA",
    "Appendicitis"
  ),
  group_labels = c(
    "NIA",
    "Appendicitis"
  ),
  candidate_type = "raw"
)

save_candidate_heatmap(
  selected_miRNAs = condition_analysis$fdr_candidates$miRNA,
  contrast_name = "Appendicitis_vs_NIA",
  metadata_subset = metadata,
  group_variable = "Appendicitis_status",
  group_levels = c(
    "NIA",
    "Appendicitis"
  ),
  group_labels = c(
    "NIA",
    "Appendicitis"
  ),
  candidate_type = "fdr"
)

save_candidate_pca(
  selected_miRNAs = condition_analysis$raw_candidates$miRNA,
  contrast_name = "Appendicitis_vs_NIA",
  metadata_subset = metadata,
  group_variable = "Appendicitis_status",
  group_levels = c(
    "NIA",
    "Appendicitis"
  ),
  group_labels = c(
    "NIA",
    "Appendicitis"
  ),
  candidate_type = "raw"
)

save_candidate_pca(
  selected_miRNAs = condition_analysis$fdr_candidates$miRNA,
  contrast_name = "Appendicitis_vs_NIA",
  metadata_subset = metadata,
  group_variable = "Appendicitis_status",
  group_levels = c(
    "NIA",
    "Appendicitis"
  ),
  group_labels = c(
    "NIA",
    "Appendicitis"
  ),
  candidate_type = "fdr"
)


# ==============================================================================
# 5.4 Global clinical-group analysis: NIA / Mild / Severe
# ==============================================================================

message(
  "Running miRPM global severity analysis..."
)

phenotype_global_native <- miRPM::perform_statistical_tests(
  miRNA_ftd = rpm,
  metadata = metadata,
  condition = "Phenotype",
  output_file = NULL,
  assign_results = FALSE,
  alpha = alpha_fdr,
  p_adjust_method = "BH",
  detection_threshold = 0,
  pseudocount = 1,
  group_order = c(
    "NIA",
    "Mild",
    "Severe"
  ),
  posthoc_only_if_global_significant = TRUE,
  write_excel = FALSE
)

if (!identical(
  phenotype_global_native$analysis_type,
  "multi_group"
)) {
  stop(
    "Global severity analysis did not return a multigroup miRPM result."
  )
}

phenotype_global_results <- as.data.frame(
  phenotype_global_native$results
)

phenotype_global_results <- add_audit_significance(
  phenotype_global_results
)

saveRDS(
  phenotype_global_native,
  file.path(
    native_dir,
    "Sg.rds"
  )
)

phenotype_global_sets <- save_result_sets(
  phenotype_global_results,
  "Phenotype_global"
)

# The package-native Dunn output is preserved inside the RDS object for audit,
# but it is not used to define the prespecified pairwise analyses below.


# ==============================================================================
# 5.5 Prespecified pairwise clinical-group comparisons
# ==============================================================================

run_pairwise_phenotype <- function(
    lower_group,
    higher_group,
    contrast_name
) {

  lower_label <- phenotype_label(
    lower_group
  )

  higher_label <- phenotype_label(
    higher_group
  )

  message(
    "Running miRPM pairwise comparison: ",
    lower_label,
    " versus ",
    higher_label
  )

  keep <- metadata$Phenotype %in% c(
    lower_group,
    higher_group
  )

  metadata_pair <- droplevels(
    metadata[
      keep,
      ,
      drop = FALSE
    ]
  )

  rpm_pair <- rpm[
    ,
    metadata_pair$Sample,
    drop = FALSE
  ]

  # Group order is intentionally higher, lower so positive effects correspond
  # to increased expression in the second/more severe phenotype.

  analysis_result <- run_mirpm_two_group(
    rpm_matrix = rpm_pair,
    metadata_subset = metadata_pair,
    condition = "Phenotype",
    group_order = c(
      higher_group,
      lower_group
    ),
    contrast_name = contrast_name,
    positive_effect_label = paste0(
      "Positive effect = higher in ",
      higher_label,
      " than ",
      lower_label
    )
  )

  plot_fdr_effect_summary(
    analysis_result,
    contrast_name = contrast_name,
    title = paste0(
      "RPM differential expression: ",
      higher_label,
      " versus ",
      lower_label
    ),
    x_label = paste0(
      "Log2 median ratio (",
      higher_label,
      " / ",
      lower_label,
      ")"
    )
  )

  plot_fdr_expression(
    analysis_result,
    contrast_name = contrast_name,
    metadata_subset = metadata_pair,
    group_variable = "Phenotype",
    plot_group_order = c(
      lower_group,
      higher_group
    ),
    plot_group_labels = c(
      lower_label,
      higher_label
    )
  )

  save_candidate_heatmap(
    selected_miRNAs = analysis_result$raw_candidates$miRNA,
    contrast_name = contrast_name,
    metadata_subset = metadata_pair,
    group_variable = "Phenotype",
    group_levels = c(
      lower_group,
      higher_group
    ),
    group_labels = c(
      lower_label,
      higher_label
    ),
    candidate_type = "raw"
  )

  save_candidate_heatmap(
    selected_miRNAs = analysis_result$fdr_candidates$miRNA,
    contrast_name = contrast_name,
    metadata_subset = metadata_pair,
    group_variable = "Phenotype",
    group_levels = c(
      lower_group,
      higher_group
    ),
    group_labels = c(
      lower_label,
      higher_label
    ),
    candidate_type = "fdr"
  )

  save_candidate_pca(
    selected_miRNAs = analysis_result$raw_candidates$miRNA,
    contrast_name = contrast_name,
    metadata_subset = metadata_pair,
    group_variable = "Phenotype",
    group_levels = c(
      lower_group,
      higher_group
    ),
    group_labels = c(
      lower_label,
      higher_label
    ),
    candidate_type = "raw"
  )

  save_candidate_pca(
    selected_miRNAs = analysis_result$fdr_candidates$miRNA,
    contrast_name = contrast_name,
    metadata_subset = metadata_pair,
    group_variable = "Phenotype",
    group_levels = c(
      lower_group,
      higher_group
    ),
    group_labels = c(
      lower_label,
      higher_label
    ),
    candidate_type = "fdr"
  )

  analysis_result
}


nia_vs_mild <- run_pairwise_phenotype(
  lower_group = "NIA",
  higher_group = "Mild",
  contrast_name = "NIA_vs_Mild"
)

nia_vs_severe <- run_pairwise_phenotype(
  lower_group = "NIA",
  higher_group = "Severe",
  contrast_name = "NIA_vs_Severe"
)

mild_vs_severe <- run_pairwise_phenotype(
  lower_group = "Mild",
  higher_group = "Severe",
  contrast_name = "Mild_vs_Severe"
)


# ==============================================================================
# 5.6 Global clinical-group candidate heatmap/PCA
# ==============================================================================

save_candidate_heatmap(
  selected_miRNAs = phenotype_global_sets$raw$miRNA,
  contrast_name = "Phenotype_global",
  metadata_subset = metadata,
  group_variable = "Phenotype",
  group_levels = c(
    "NIA",
    "Mild",
    "Severe"
  ),
  group_labels = c(
    "NIA",
    "Mild",
    "Severe"
  ),
  candidate_type = "raw"
)

save_candidate_heatmap(
  selected_miRNAs = phenotype_global_sets$fdr$miRNA,
  contrast_name = "Phenotype_global",
  metadata_subset = metadata,
  group_variable = "Phenotype",
  group_levels = c(
    "NIA",
    "Mild",
    "Severe"
  ),
  group_labels = c(
    "NIA",
    "Mild",
    "Severe"
  ),
  candidate_type = "fdr"
)

save_candidate_pca(
  selected_miRNAs = phenotype_global_sets$raw$miRNA,
  contrast_name = "Phenotype_global",
  metadata_subset = metadata,
  group_variable = "Phenotype",
  group_levels = c(
    "NIA",
    "Mild",
    "Severe"
  ),
  group_labels = c(
    "NIA",
    "Mild",
    "Severe"
  ),
  candidate_type = "raw"
)

save_candidate_pca(
  selected_miRNAs = phenotype_global_sets$fdr$miRNA,
  contrast_name = "Phenotype_global",
  metadata_subset = metadata,
  group_variable = "Phenotype",
  group_levels = c(
    "NIA",
    "Mild",
    "Severe"
  ),
  group_labels = c(
    "NIA",
    "Mild",
    "Severe"
  ),
  candidate_type = "fdr"
)



# ==============================================================================
# 5.7 Cross-analysis candidate signal summary
# ==============================================================================

# These summaries are deliberately data-driven.
#
# Every miRNA in the complete upstream-frozen feature set is represented.
# No historical candidate list is supplied to this section.
#
# The analyses summarized here are not independent. Consequently, the number
# of nominally significant analyses is a descriptive recurrence metric only.

contrast_results <- list(
  Appendicitis_vs_NIA = condition_analysis$all_results,
  Phenotype_global = phenotype_global_sets$all,
  NIA_vs_Mild = nia_vs_mild$all_results,
  NIA_vs_Severe = nia_vs_severe$all_results,
  Mild_vs_Severe = mild_vs_severe$all_results
)


all_results_long <- dplyr::bind_rows(
  contrast_results,
  .id = "contrast"
)


required_signal_columns <- c(
  "miRNA",
  "p_value",
  "FDR",
  "Holm",
  "raw_significant",
  "fdr_significant",
  "holm_significant"
)


if (!all(
  required_signal_columns %in%
    colnames(
      all_results_long
    )
)) {

  stop(
    "Combined RPM-DE results lack one or more required signal-summary columns.",
    call. = FALSE
  )
}


expected_contrast_names <- c(
  "Appendicitis_vs_NIA",
  "Phenotype_global",
  "NIA_vs_Mild",
  "NIA_vs_Severe",
  "Mild_vs_Severe"
)


if (!identical(
  names(
    contrast_results
  ),
  expected_contrast_names
)) {

  stop(
    "Unexpected contrast set while building the RPM candidate signal summary.",
    call. = FALSE
  )
}


if (
  nrow(
    all_results_long
  ) !=
    nrow(
      rpm
    ) *
      length(
        contrast_results
      )
) {

  stop(
    "Combined RPM-DE result table has an unexpected number of rows.",
    call. = FALSE
  )
}


utils::write.csv(
  all_results_long,
  prepare_output_file(
    file.path(
      de_results_dir,
      "DE_RPM_all_contrasts_long.csv"
    )
  ),
  row.names = FALSE
)


collapse_contrasts <- function(
    x,
    flag
) {

  hits <- x[
    !is.na(
      flag
    ) &
      flag
  ]

  if (
    length(
      hits
    ) == 0L
  ) {

    return(
      ""
    )
  }

  paste(
    unique(
      hits
    ),
    collapse = "; "
  )
}


safe_min <- function(
    x
) {

  x <- x[
    is.finite(
      x
    )
  ]

  if (
    length(
      x
    ) == 0L
  ) {

    return(
      NA_real_
    )
  }

  min(
    x
  )
}


best_contrast_from_metric <- function(
    contrast,
    metric
) {

  usable <- (
    !is.na(
      metric
    ) &
      is.finite(
        metric
      )
  )

  if (!any(
    usable
  )) {

    return(
      ""
    )
  }

  contrast[
    which.min(
      ifelse(
        usable,
        metric,
        Inf
      )
    )
  ][1L]
}


candidate_signal_summary <- all_results_long |>
  dplyr::group_by(
    miRNA
  ) |>
  dplyr::summarise(

    n_analyses_tested = dplyr::n(),

    minimum_raw_p = safe_min(
      p_value
    ),

    minimum_FDR = safe_min(
      FDR
    ),

    minimum_Holm = safe_min(
      Holm
    ),

    best_raw_p_analysis = best_contrast_from_metric(
      contrast,
      p_value
    ),

    best_FDR_analysis = best_contrast_from_metric(
      contrast,
      FDR
    ),

    n_nominal_analyses = sum(
      raw_significant,
      na.rm = TRUE
    ),

    n_FDR_analyses = sum(
      fdr_significant,
      na.rm = TRUE
    ),

    n_Holm_analyses = sum(
      holm_significant,
      na.rm = TRUE
    ),

    nominal_analyses = collapse_contrasts(
      contrast,
      raw_significant
    ),

    FDR_analyses = collapse_contrasts(
      contrast,
      fdr_significant
    ),

    Holm_analyses = collapse_contrasts(
      contrast,
      holm_significant
    ),

    .groups = "drop"
  )


candidate_signal_summary$any_nominal_signal <-
  candidate_signal_summary$n_nominal_analyses >= 1L


candidate_signal_summary$recurrent_nominal_signal <-
  candidate_signal_summary$n_nominal_analyses >= 2L


candidate_signal_summary$any_FDR_signal <-
  candidate_signal_summary$n_FDR_analyses >= 1L


candidate_signal_summary$any_Holm_signal <-
  candidate_signal_summary$n_Holm_analyses >= 1L


candidate_signal_summary$signal_tier <- dplyr::case_when(

  candidate_signal_summary$any_FDR_signal ~
    "FDR_supported",

  candidate_signal_summary$recurrent_nominal_signal ~
    "recurrent_nominal",

  candidate_signal_summary$any_nominal_signal ~
    "single_nominal",

  TRUE ~
    "no_nominal_signal"
)


signal_tier_order <- c(
  "FDR_supported",
  "recurrent_nominal",
  "single_nominal",
  "no_nominal_signal"
)


candidate_signal_summary$signal_tier <- factor(
  candidate_signal_summary$signal_tier,
  levels = signal_tier_order
)


candidate_signal_summary <- candidate_signal_summary |>
  dplyr::arrange(
    signal_tier,
    dplyr::desc(
      n_FDR_analyses
    ),
    dplyr::desc(
      n_nominal_analyses
    ),
    minimum_FDR,
    minimum_raw_p
  )


candidate_signal_summary$signal_tier <- as.character(
  candidate_signal_summary$signal_tier
)


if (
  nrow(
    candidate_signal_summary
  ) !=
    nrow(
      rpm
    ) ||
  !setequal(
    candidate_signal_summary$miRNA,
    rownames(
      rpm
    )
  )
) {

  stop(
    "Candidate signal summary does not contain exactly the complete frozen ",
    "RPM feature set.",
    call. = FALSE
  )
}


candidate_any_nominal <- candidate_signal_summary |>
  dplyr::filter(
    any_nominal_signal
  )


candidate_recurrent_nominal <- candidate_signal_summary |>
  dplyr::filter(
    recurrent_nominal_signal
  )


candidate_FDR_supported <- candidate_signal_summary |>
  dplyr::filter(
    any_FDR_signal
  )


utils::write.csv(
  candidate_signal_summary,
  prepare_output_file(
    file.path(
      de_results_dir,
      "DE_RPM_candidate_signal_summary.csv"
    )
  ),
  row.names = FALSE
)


utils::write.csv(
  candidate_any_nominal,
  prepare_output_file(
    file.path(
      de_results_dir,
      "DE_RPM_candidate_any_nominal.csv"
    )
  ),
  row.names = FALSE
)


utils::write.csv(
  candidate_recurrent_nominal,
  prepare_output_file(
    file.path(
      de_results_dir,
      "DE_RPM_candidate_recurrent_nominal.csv"
    )
  ),
  row.names = FALSE
)


utils::write.csv(
  candidate_FDR_supported,
  prepare_output_file(
    file.path(
      de_results_dir,
      "DE_RPM_candidate_FDR_supported.csv"
    )
  ),
  row.names = FALSE
)


message(
  ""
)

message(
  "RPM candidate signal summary:"
)

message(
  "- any nominal p < 0.05: ",
  nrow(
    candidate_any_nominal
  )
)

message(
  "- recurrent nominal signal (>=2 analyses): ",
  nrow(
    candidate_recurrent_nominal
  )
)

message(
  "- FDR-supported in >=1 analysis: ",
  nrow(
    candidate_FDR_supported
  )
)

if (
  nrow(
    candidate_any_nominal
  ) > 0L
) {

  print(
    candidate_any_nominal[
      ,
      c(
        "miRNA",
        "signal_tier",
        "n_nominal_analyses",
        "n_FDR_analyses",
        "minimum_raw_p",
        "minimum_FDR",
        "nominal_analyses",
        "FDR_analyses"
      ),
      drop = FALSE
    ]
  )
}



# ==============================================================================
# 5.8 Exploratory PCA and heatmaps of cross-analysis candidate sets
# ==============================================================================

# IMPORTANT:
#   These plots are post-selection visualizations.
#
#   The same clinical labels used to identify differential-expression signals
#   are also used to display the samples. Therefore, apparent separation in
#   these PCA/heatmap figures is descriptive and must not be interpreted as
#   independent evidence of diagnostic or prognostic performance.
#
# Two data-driven candidate sets are visualized:
#
#   any_nominal:
#       raw p < 0.05 in at least one of the five prespecified analyses.
#
#   recurrent_nominal:
#       raw p < 0.05 in at least two of the five prespecified analyses.
#
# No historical miRNA list is used.


save_cross_analysis_heatmap <- function(
    selected_miRNAs,
    set_code,
    set_label
) {

  selected_miRNAs <- intersect(
    unique(
      selected_miRNAs
    ),
    rownames(
      heatmap_z
    )
  )


  if (
    length(
      selected_miRNAs
    ) == 0L
  ) {

    message(
      "Cross-analysis heatmap skipped for ",
      set_label,
      ": no miRNAs."
    )

    return(
      invisible(
        NULL
      )
    )
  }


  plot_metadata <- metadata |>
    dplyr::arrange(
      Phenotype,
      Sample
    )


  ordered_samples <- plot_metadata$Sample


  heatmap_matrix <- heatmap_z[
    selected_miRNAs,
    ordered_samples,
    drop = FALSE
  ]


  annotation <- ComplexHeatmap::HeatmapAnnotation(
    Phenotype = plot_metadata$Phenotype,
    annotation_name_side = "left"
  )


  heatmap_object <- ComplexHeatmap::Heatmap(

    heatmap_matrix,

    name = "Row Z-score",

    col = circlize::colorRamp2(
      c(
        -2,
        0,
        2
      ),
      c(
        "navy",
        "white",
        "firebrick3"
      )
    ),

    top_annotation = annotation,

    column_split = plot_metadata$Phenotype,

    cluster_rows = length(
      selected_miRNAs
    ) > 1L,

    cluster_columns = FALSE,

    show_column_names = FALSE,

    show_row_names = TRUE,

    row_names_gp = grid::gpar(
      fontsize = if (
        length(
          selected_miRNAs
        ) > 35L
      ) {
        6.5
      } else {
        8
      }
    ),

    column_title = paste0(
      set_label,
      " (",
      length(
        selected_miRNAs
      ),
      " miRNAs)"
    ),

    use_raster = FALSE
  )


  draw_heatmap <- function() {

    ComplexHeatmap::draw(
      heatmap_object,
      heatmap_legend_side = "right",
      annotation_legend_side = "right"
    )
  }


  figure_height <- max(
    6,
    min(
      12,
      0.18 *
        length(
          selected_miRNAs
        ) +
        3.5
    )
  )


  draw_to_pdf(
    filename = file.path(
      candidate_summary_heatmap_dir,
      paste0(
        set_code,
        "_heatmap.pdf"
      )
    ),
    width = 8,
    height = figure_height,
    draw = draw_heatmap
  )


  draw_to_tiff(
    filename = file.path(
      candidate_summary_heatmap_dir,
      paste0(
        set_code,
        "_heatmap.tiff"
      )
    ),
    width = 8,
    height = figure_height,
    units = "in",
    res = 600,
    compression = "lzw",
    draw = draw_heatmap
  )


  utils::write.csv(
    data.frame(
      candidate_set = set_code,
      candidate_definition = set_label,
      miRNA = selected_miRNAs,
      stringsAsFactors = FALSE
    ),
    prepare_output_file(
      file.path(
        candidate_summary_heatmap_dir,
        paste0(
          set_code,
          "_miRNAs.csv"
        )
      )
    ),
    row.names = FALSE
  )


  invisible(
    heatmap_object
  )
}


save_cross_analysis_pca <- function(
    selected_miRNAs,
    set_code,
    set_label
) {

  selected_miRNAs <- intersect(
    unique(
      selected_miRNAs
    ),
    rownames(
      rpm
    )
  )


  if (
    length(
      selected_miRNAs
    ) < 2L
  ) {

    message(
      "Cross-analysis PCA skipped for ",
      set_label,
      ": fewer than two miRNAs."
    )

    return(
      invisible(
        NULL
      )
    )
  }


  pca_matrix <- log2(
    rpm[
      selected_miRNAs,
      metadata$Sample,
      drop = FALSE
    ] +
      1
  )


  feature_sd <- apply(
    pca_matrix,
    1L,
    stats::sd
  )


  usable_features <- (
    is.finite(
      feature_sd
    ) &
      feature_sd > 0
  )


  pca_matrix <- pca_matrix[
    usable_features,
    ,
    drop = FALSE
  ]


  if (
    nrow(
      pca_matrix
    ) < 2L
  ) {

    message(
      "Cross-analysis PCA skipped for ",
      set_label,
      ": fewer than two variable miRNAs."
    )

    return(
      invisible(
        NULL
      )
    )
  }


  pca_object <- stats::prcomp(
    t(
      pca_matrix
    ),
    center = TRUE,
    scale. = TRUE
  )


  variance <- (
    pca_object$sdev^2
  ) /
    sum(
      pca_object$sdev^2
    )


  pca_coordinates <- data.frame(
    Sample = rownames(
      pca_object$x
    ),
    PC1 = pca_object$x[
      ,
      1L
    ],
    PC2 = pca_object$x[
      ,
      2L
    ],
    stringsAsFactors = FALSE
  )


  if (
    ncol(
      pca_object$x
    ) >= 3L
  ) {

    pca_coordinates$PC3 <- pca_object$x[
      ,
      3L
    ]
  }


  pca_coordinates <- dplyr::left_join(
    pca_coordinates,
    metadata[
      ,
      c(
        "Sample",
        "Phenotype",
        "Phenotype_full",
        "Appendicitis_status",
        "Sex",
        "Age"
      ),
      drop = FALSE
    ],
    by = "Sample"
  )


  pca_variance <- data.frame(
    PC = paste0(
      "PC",
      seq_along(
        variance
      )
    ),
    variance_explained = variance,
    variance_explained_pct = 100 *
      variance,
    cumulative_variance_explained_pct = 100 *
      cumsum(
        variance
      ),
    stringsAsFactors = FALSE
  )


  utils::write.csv(
    pca_coordinates,
    prepare_output_file(
      file.path(
        candidate_summary_pca_dir,
        paste0(
          set_code,
          "_PCA_coordinates.csv"
        )
      )
    ),
    row.names = FALSE
  )


  utils::write.csv(
    pca_variance,
    prepare_output_file(
      file.path(
        candidate_summary_pca_dir,
        paste0(
          set_code,
          "_PCA_variance.csv"
        )
      )
    ),
    row.names = FALSE
  )


  utils::write.csv(
    data.frame(
      candidate_set = set_code,
      candidate_definition = set_label,
      miRNA = rownames(
        pca_matrix
      ),
      stringsAsFactors = FALSE
    ),
    prepare_output_file(
      file.path(
        candidate_summary_pca_dir,
        paste0(
          set_code,
          "_miRNAs.csv"
        )
      )
    ),
    row.names = FALSE
  )


  group_counts <- table(
    pca_coordinates$Phenotype
  )


  eligible_groups <- names(
    group_counts[
      group_counts >= 3L
    ]
  )


  ellipse_data <- pca_coordinates[
    as.character(
      pca_coordinates$Phenotype
    ) %in%
      eligible_groups,
    ,
    drop = FALSE
  ]


  plot_object <- ggplot2::ggplot(
    pca_coordinates,
    ggplot2::aes(
      x = PC1,
      y = PC2,
      color = Phenotype
    )
  )


  if (
    nrow(
      ellipse_data
    ) > 0L
  ) {

    plot_object <- plot_object +
      ggplot2::stat_ellipse(
        data = ellipse_data,
        ggplot2::aes(
          fill = Phenotype
        ),
        geom = "polygon",
        type = "norm",
        level = 0.95,
        alpha = 0.12,
        color = NA,
        show.legend = FALSE
      ) +
      ggplot2::stat_ellipse(
        data = ellipse_data,
        type = "norm",
        level = 0.95,
        linewidth = 0.6,
        alpha = 0.85,
        show.legend = FALSE
      )
  }


  plot_object <- plot_object +
    ggplot2::geom_point(
      size = 3,
      alpha = 0.95
    ) +
    ggplot2::labs(
      title = paste0(
        set_label,
        " — exploratory PCA"
      ),
      subtitle = paste0(
        nrow(
          pca_matrix
        ),
        " miRNAs; post-selection visualization"
      ),
      x = sprintf(
        "PC1 (%.1f%%)",
        100 *
          variance[1L]
      ),
      y = sprintf(
        "PC2 (%.1f%%)",
        100 *
          variance[2L]
      ),
      color = NULL
    ) +
    ggplot2::theme_classic(
      base_size = 11
    ) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(
        face = "bold"
      ),
      legend.position = "right"
    )


  save_ggplot_pdf(
    plot = plot_object,
    filename = file.path(
      candidate_summary_pca_dir,
      paste0(
        set_code,
        "_PCA_PC1_PC2.pdf"
      )
    ),
    width = 7,
    height = 5
  )


  save_ggplot_tiff(
    plot = plot_object,
    filename = file.path(
      candidate_summary_pca_dir,
      paste0(
        set_code,
        "_PCA_PC1_PC2.tiff"
      )
    ),
    width = 7,
    height = 5,
    dpi = 600
  )


  invisible(
    list(
      pca = pca_object,
      coordinates = pca_coordinates,
      variance = pca_variance,
      miRNAs = rownames(
        pca_matrix
      ),
      plot = plot_object
    )
  )
}


candidate_any_nominal_heatmap <- save_cross_analysis_heatmap(
  selected_miRNAs = candidate_any_nominal$miRNA,
  set_code = "Any_nominal",
  set_label = "Any nominal signal"
)


candidate_any_nominal_pca <- save_cross_analysis_pca(
  selected_miRNAs = candidate_any_nominal$miRNA,
  set_code = "Any_nominal",
  set_label = "Any nominal signal"
)


candidate_recurrent_heatmap <- save_cross_analysis_heatmap(
  selected_miRNAs = candidate_recurrent_nominal$miRNA,
  set_code = "Recurrent_nominal",
  set_label = "Recurrent nominal signal"
)


candidate_recurrent_pca <- save_cross_analysis_pca(
  selected_miRNAs = candidate_recurrent_nominal$miRNA,
  set_code = "Recurrent_nominal",
  set_label = "Recurrent nominal signal"
)


message(
  "Exploratory candidate-set figures generated:"
)

message(
  "- any nominal signal set: ",
  nrow(
    candidate_any_nominal
  ),
  " miRNAs"
)

message(
  "- recurrent nominal signal set: ",
  nrow(
    candidate_recurrent_nominal
  ),
  " miRNAs"
)



# ==============================================================================
# 6. OUTPUTS
# ==============================================================================

# ==============================================================================
# 6.1 Consolidated workbook
# ==============================================================================



workbook_path <- file.path(
  de_results_dir,
  "DE_RPM_results.xlsx"
)

workbook <- openxlsx::createWorkbook()


add_sheet <- function(
    workbook,
    sheet_name,
    data
) {

  safe_sheet_name <- substr(
    gsub(
      "[\\[\\]\\*\\?/\\\\:]",
      "_",
      sheet_name
    ),
    1,
    31
  )

  openxlsx::addWorksheet(
    workbook,
    safe_sheet_name
  )

  openxlsx::writeData(
    workbook,
    safe_sheet_name,
    data
  )

  openxlsx::freezePane(
    workbook,
    safe_sheet_name,
    firstRow = TRUE
  )

  if (ncol(data) > 0) {
    openxlsx::setColWidths(
      workbook,
      safe_sheet_name,
      cols = seq_len(
        ncol(
          data
        )
      ),
      widths = "auto"
    )
  }
}


add_sheet(
  workbook,
  "Appendicitis_vs_NIA_all",
  condition_analysis$all_results
)

add_sheet(
  workbook,
  "Appendicitis_vs_NIA_FDR",
  condition_analysis$fdr_candidates
)

add_sheet(
  workbook,
  "Phenotype_global_all",
  phenotype_global_sets$all
)

add_sheet(
  workbook,
  "Phenotype_global_FDR",
  phenotype_global_sets$fdr
)

add_sheet(
  workbook,
  "NIA_vs_Mild_all",
  nia_vs_mild$all_results
)

add_sheet(
  workbook,
  "NIA_vs_Mild_FDR",
  nia_vs_mild$fdr_candidates
)

add_sheet(
  workbook,
  "NIA_vs_Severe_all",
  nia_vs_severe$all_results
)

add_sheet(
  workbook,
  "NIA_vs_Severe_FDR",
  nia_vs_severe$fdr_candidates
)

add_sheet(
  workbook,
  "Mild_vs_Severe_all",
  mild_vs_severe$all_results
)

add_sheet(
  workbook,
  "Mild_vs_Severe_FDR",
  mild_vs_severe$fdr_candidates
)

add_sheet(
  workbook,
  "Candidate_signal_summary",
  candidate_signal_summary
)

add_sheet(
  workbook,
  "Any_nominal",
  candidate_any_nominal
)

add_sheet(
  workbook,
  "Recurrent_nominal",
  candidate_recurrent_nominal
)

add_sheet(
  workbook,
  "FDR_supported",
  candidate_FDR_supported
)

openxlsx::saveWorkbook(
  workbook,
  workbook_path,
  overwrite = TRUE
)


# ==============================================================================
# 7. QC / AUDIT
# ==============================================================================

# ==============================================================================
# 7.1 Analysis summary
# ==============================================================================

summary_table <- data.frame(
  analysis = c(
    "Appendicitis_vs_NIA",
    "Phenotype_global",
    "NIA_vs_Mild",
    "NIA_vs_Severe",
    "Mild_vs_Severe"
  ),
  n_miRNAs_tested = c(
    nrow(
      condition_analysis$all_results
    ),
    nrow(
      phenotype_global_sets$all
    ),
    nrow(
      nia_vs_mild$all_results
    ),
    nrow(
      nia_vs_severe$all_results
    ),
    nrow(
      mild_vs_severe$all_results
    )
  ),
  raw_p_lt_0.05 = c(
    nrow(
      condition_analysis$raw_candidates
    ),
    nrow(
      phenotype_global_sets$raw
    ),
    nrow(
      nia_vs_mild$raw_candidates
    ),
    nrow(
      nia_vs_severe$raw_candidates
    ),
    nrow(
      mild_vs_severe$raw_candidates
    )
  ),
  FDR_lt_0.05 = c(
    nrow(
      condition_analysis$fdr_candidates
    ),
    nrow(
      phenotype_global_sets$fdr
    ),
    nrow(
      nia_vs_mild$fdr_candidates
    ),
    nrow(
      nia_vs_severe$fdr_candidates
    ),
    nrow(
      mild_vs_severe$fdr_candidates
    )
  ),
  Holm_lt_0.05 = c(
    nrow(
      condition_analysis$holm_candidates
    ),
    nrow(
      phenotype_global_sets$holm
    ),
    nrow(
      nia_vs_mild$holm_candidates
    ),
    nrow(
      nia_vs_severe$holm_candidates
    ),
    nrow(
      mild_vs_severe$holm_candidates
    )
  ),
  stringsAsFactors = FALSE
)

utils::write.csv(
  summary_table,
  prepare_output_file(
    file.path(
      de_results_dir,
      "DE_RPM_analysis_summary.csv"
    )
  ),
  row.names = FALSE
)

print(
  summary_table
)


# ==============================================================================
# 7.2 Final QC summary
# ==============================================================================

final_qc <- data.frame(
  analysis_id = context$analysis_id,

  n_samples = ncol(
    rpm
  ),

  n_NIA = sum(
    metadata$Phenotype == "NIA"
  ),

  n_Mild = sum(
    metadata$Phenotype == "Mild"
  ),

  n_Severe = sum(
    metadata$Phenotype == "Severe"
  ),

  n_filtered_miRNAs = nrow(
    rpm
  ),

  n_prespecified_analyses = length(
    contrast_results
  ),

  all_analyses_test_same_feature_set = all(
    summary_table$n_miRNAs_tested ==
      nrow(
        rpm
      )
  ),

  all_features_present_in_signal_summary = (
    nrow(
      candidate_signal_summary
    ) ==
      nrow(
        rpm
      ) &&
      setequal(
        candidate_signal_summary$miRNA,
        rownames(
          rpm
        )
      )
  ),

  n_any_nominal_candidates = nrow(
    candidate_any_nominal
  ),

  n_recurrent_nominal_candidates = nrow(
    candidate_recurrent_nominal
  ),

  n_FDR_supported_candidates = nrow(
    candidate_FDR_supported
  ),

  any_nominal_PCA_generated =
    !is.null(
      candidate_any_nominal_pca
    ),

  any_nominal_heatmap_generated =
    !is.null(
      candidate_any_nominal_heatmap
    ),

  recurrent_nominal_PCA_generated =
    !is.null(
      candidate_recurrent_pca
    ),

  recurrent_nominal_heatmap_generated =
    !is.null(
      candidate_recurrent_heatmap
    ),

  candidate_selection_is_data_driven = TRUE,

  historical_candidate_list_used = FALSE,

  samples_removed_by_script = 0L,

  stringsAsFactors = FALSE
)

utils::write.csv(
  final_qc,
  prepare_output_file(
    file.path(
      de_results_dir,
      "04_final_QC_summary.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 8. REPRODUCIBILITY
# ==============================================================================

write_session_info(
  results_dir
)


message("")
message(
  "04 complete — RPM-based differential expression performed with ",
  "miRPM::perform_statistical_tests()."
)
message(
  "Analysis: ",
  context$analysis_id,
  "; ",
  nrow(rpm),
  " filtered miRNAs; ",
  ncol(rpm),
  " samples."
)
message(
  "Primary multiplicity correction: Benjamini-Hochberg FDR."
)
message(
  "Raw p < 0.05 is exploratory and triggers candidate heatmaps and PCA."
)
message(
  "Candidate heatmaps and PCA are exported separately for raw p < 0.05 and BH-FDR < 0.05 candidates."
)
message(
  "miRNAs with nominal p < 0.05 in >=1 analysis: ",
  nrow(
    candidate_any_nominal
  )
)
message(
  "miRNAs with recurrent nominal signal in >=2 analyses: ",
  nrow(
    candidate_recurrent_nominal
  )
)
message(
  "miRNAs with BH-FDR < 0.05 in >=1 analysis: ",
  nrow(
    candidate_FDR_supported
  )
)
message(
  "No historical candidate list was used for testing or candidate definition."
)
message(
  "Exploratory aggregate PCA/heatmaps generated for any-nominal and recurrent-nominal candidate sets."
)
message(
  "No sample was removed in this script."
)
message("")
message(
  "Main outputs:"
)
message(
  "- ",
  file.path(
    de_results_dir,
    "DE_RPM_analysis_manifest.csv"
  )
)
message(
  "- ",
  file.path(
    de_results_dir,
    "DE_RPM_analysis_summary.csv"
  )
)
message(
  "- ",
  file.path(
    de_results_dir,
    "DE_RPM_results.xlsx"
  )
)
message(
  "- ",
  file.path(
    de_results_dir,
    "DE_RPM_all_contrasts_long.csv"
  )
)
message(
  "- ",
  file.path(
    de_results_dir,
    "DE_RPM_candidate_signal_summary.csv"
  )
)
message(
  "- ",
  file.path(
    de_results_dir,
    "DE_RPM_candidate_any_nominal.csv"
  )
)
message(
  "- ",
  file.path(
    de_results_dir,
    "DE_RPM_candidate_recurrent_nominal.csv"
  )
)
message(
  "- ",
  file.path(
    de_results_dir,
    "DE_RPM_candidate_FDR_supported.csv"
  )
)
message(
  "- ",
  file.path(
    de_results_dir,
    "04_final_QC_summary.csv"
  )
)
message(
  "- ",
  tables_dir
)
message(
  "- ",
  candidate_dir
)
message(
  "- ",
  native_dir
)
message(
  "- ",
  effect_plot_dir
)
message(
  "- ",
  expression_plot_dir
)
message(
  "- ",
  heatmap_dir
)
message(
  "  - ",
  heatmap_raw_dir
)
message(
  "  - ",
  heatmap_fdr_dir
)
message(
  "- ",
  candidate_pca_dir
)
message(
  "  - ",
  candidate_pca_raw_dir
)
message(
  "  - ",
  candidate_pca_fdr_dir
)
message(
  "  - ",
  candidate_summary_pca_dir
)
message(
  "- ",
  candidate_summary_heatmap_dir
)

message(
  "============================================================\n"
)
