# ==============================================================================
# 06_integrated_method_comparison.R
# ==============================================================================
#
# Project:
#   Pediatric appendicitis plasma miRNA-seq
#
# Purpose:
#   Integrate the complete differential-expression evidence generated by
#   scripts 04 and 05 across RPM/miRPM, edgeR-TMM and DESeq2.
#
# Role in pipeline:
#   Evidence integration and candidate prioritization.
#
# IMPORTANT:
#   This script does NOT use a predefined historical miRNA panel.
#   All miRNAs in the upstream-frozen feature set are integrated.
#
# Clinical variables inherited from script 01:
#   Appendicitis_status = NIA / Appendicitis
#   Phenotype           = NIA / Mild / Severe
#
# Prespecified analyses:
#   Appendicitis_vs_NIA
#   Phenotype_global
#   NIA_vs_Mild
#   NIA_vs_Severe
#   Mild_vs_Severe
#
# Methods:
#   RPM / miRPM:
#       supportive non-parametric evidence from script 04.
#
#   edgeR-TMM:
#       primary count-based validation from script 05.
#
#   DESeq2:
#       primary count-based validation from script 05.
#
# Models:
#   unadjusted:
#       primary count-based validation layer.
#
#   adjusted_age_sex:
#       sensitivity layer.
#
# Integration principles:
#
#   1. All methods are integrated on exactly the same upstream-filtered feature set.
#
#   2. For pairwise analyses, concordance requires the same effect direction.
#
#   3. Phenotype_global is an omnibus test and therefore has no unique
#      effect direction; direction is not required for its concordance.
#
#   4. FDR is interpreted within each original method x model x analysis.
#      No new p-value or artificial composite score is generated here.
#
#   5. The adjusted model is sensitivity evidence and does not create an
#      independent replicate. Robustness after age+sex adjustment is recorded
#      separately.
#
# Data-driven evidence classes:
#
#   FDR_concordant_robust:
#       edgeR and DESeq2 both have FDR < 0.05 for the same analysis, with
#       concordant direction when applicable, in BOTH unadjusted and age+sex
#       adjusted models.
#
#   FDR_cross_supported_robust:
#       at least one count method has FDR < 0.05 and the other is nominal
#       p < 0.05 for the same analysis, with concordant direction, in BOTH
#       unadjusted and age+sex adjusted models.
#
#   FDR_concordant_primary:
#       edgeR and DESeq2 both have FDR < 0.05 for the same analysis in the
#       unadjusted primary model, but the same evidence is not retained after
#       adjustment.
#
#   FDR_cross_supported_primary:
#       at least one count method has FDR < 0.05 and the other is nominal
#       p < 0.05 for the same analysis in the unadjusted primary model.
#
#   FDR_single_count_method:
#       at least one count-based method has FDR < 0.05 in the primary model,
#       without cross-method support at the same nominal threshold.
#
#   All_three_nominal_concordant:
#       RPM, edgeR and DESeq2 all have raw p < 0.05 for at least one same
#       analysis, with concordant direction when applicable.
#
#   Count_methods_nominal_concordant:
#       edgeR and DESeq2 both have raw p < 0.05 for at least one same analysis,
#       with concordant direction when applicable.
#
#   Other_nominal_signal:
#       nominal evidence exists but does not meet the above recurrence criteria.
#
#   No_integrated_signal:
#       no raw p < 0.05 in any primary method/analysis.
#
# NOTE:
#   These evidence classes are descriptive prioritization labels, not new
#   statistical significance tests.
#
# Visualization:
#   Integrated PCA/heatmaps are generated from log2(RPM + 1) only as a common
#   visualization scale after candidate definition.
#
#   These figures are post-selection and are NOT independent evidence.
#
# Main outputs:
#   results/<analysis_id>/integrated/
#
#     integrated_evidence_long.csv
#     integrated_candidate_summary_all_analyses.csv
#     integrated_candidate_summary_phenotype.csv
#     downstream_candidate_priority.csv
#     candidate_hierarchy_summary.csv
#     method_concordance_summary.csv
#     age_sex_stability.csv
#
#     candidates_count_nominal_concordant.csv
#     candidates_all_three_nominal_concordant.csv
#     candidates_primary_FDR_supported.csv
#     candidates_primary_FDR_cross_supported.csv
#     candidates_age_sex_robust_FDR.csv
#
#     integrated_manifest.csv
#     06_final_QC_summary.csv
#
# No sample or miRNA is removed in this script.
# ==============================================================================


# ==============================================================================
# 1. DEPENDENCIES
# ==============================================================================

source(
  here::here(
    "R",
    "00_analysis_config.R"
  )
)

source(
  here::here(
    "R",
    "00_utils.R"
  )
)


required_packages <- c(
  "dplyr",
  "ggplot2",
  "ComplexHeatmap",
  "circlize"
)


missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]


if (
  length(
    missing_packages
  ) > 0L
) {

  stop(
    "Missing package(s) required by R/06_integrated_method_comparison.R:\n",
    paste(
      "-",
      missing_packages,
      collapse = "\n"
    ),
    "\nRun R/00_packages_setup.R first.",
    call. = FALSE
  )
}


# ==============================================================================
# 2. CONFIGURATION
# ==============================================================================

context <- get_analysis_context()

results_dir <- context$results_dir
figures_dir <- context$figures_dir


rpm_results_dir <- file.path(
  results_dir,
  "de_rpm"
)

validation_results_dir <- file.path(
  results_dir,
  "de_val"
)

integrated_results_dir <- file.path(
  results_dir,
  "integrated"
)

integrated_figures_dir <- file.path(
  figures_dir,
  "integrated"
)

pca_dir <- file.path(
  integrated_figures_dir,
  "pca"
)

heatmap_dir <- file.path(
  integrated_figures_dir,
  "hm"
)


for (
  directory in c(
    integrated_results_dir,
    integrated_figures_dir,
    pca_dir,
    heatmap_dir
  )
) {

  ensure_dir(
    directory
  )
}


contrast_code <- function(
    contrast
) {

  codes <- c(
    Appendicitis_vs_NIA = "AvN",
    Phenotype_global = "Pg",
    NIA_vs_Mild = "NvM",
    NIA_vs_Severe = "NvS",
    Mild_vs_Severe = "MvS"
  )

  code <- unname(
    codes[
      contrast
    ]
  )

  if (
    length(
      code
    ) != 1L ||
    is.na(
      code
    )
  ) {

    stop(
      "Unknown contrast: ",
      contrast,
      call. = FALSE
    )
  }

  code
}


model_code <- function(
    model
) {

  codes <- c(
    unadjusted = "unadj",
    adjusted_age_sex = "age_sex"
  )

  code <- unname(
    codes[
      model
    ]
  )

  if (
    length(
      code
    ) != 1L ||
    is.na(
      code
    )
  ) {

    stop(
      "Unknown model: ",
      model,
      call. = FALSE
    )
  }

  code
}


method_code <- function(
    method
) {

  codes <- c(
    edgeR_TMM = "edger",
    DESeq2 = "deseq2"
  )

  code <- unname(
    codes[
      method
    ]
  )

  if (
    length(
      code
    ) != 1L ||
    is.na(
      code
    )
  ) {

    stop(
      "Unknown method: ",
      method,
      call. = FALSE
    )
  }

  code
}


contrasts <- c(
  "Appendicitis_vs_NIA",
  "Phenotype_global",
  "NIA_vs_Mild",
  "NIA_vs_Severe",
  "Mild_vs_Severe"
)


phenotype_contrasts <- c(
  "Phenotype_global",
  "NIA_vs_Mild",
  "NIA_vs_Severe",
  "Mild_vs_Severe"
)


pairwise_contrasts <- setdiff(
  contrasts,
  "Phenotype_global"
)


contrast_specs <- list(

  Appendicitis_vs_NIA = list(
    variable = "Appendicitis_status",
    levels = c(
      "NIA",
      "Appendicitis"
    ),
    positive_group = "Appendicitis",
    negative_group = "NIA",
    global_test = FALSE
  ),

  Phenotype_global = list(
    variable = "Phenotype",
    levels = c(
      "NIA",
      "Mild",
      "Severe"
    ),
    positive_group = NA_character_,
    negative_group = NA_character_,
    global_test = TRUE
  ),

  NIA_vs_Mild = list(
    variable = "Phenotype",
    levels = c(
      "NIA",
      "Mild"
    ),
    positive_group = "Mild",
    negative_group = "NIA",
    global_test = FALSE
  ),

  NIA_vs_Severe = list(
    variable = "Phenotype",
    levels = c(
      "NIA",
      "Severe"
    ),
    positive_group = "Severe",
    negative_group = "NIA",
    global_test = FALSE
  ),

  Mild_vs_Severe = list(
    variable = "Phenotype",
    levels = c(
      "Mild",
      "Severe"
    ),
    positive_group = "Severe",
    negative_group = "Mild",
    global_test = FALSE
  )
)


output_path_dictionary <- data.frame(

  type = c(
    rep(
      "contrast",
      length(
        contrasts
      )
    ),
    rep(
      "evidence_class",
      9L
    )
  ),

  code = c(
    vapply(
      contrasts,
      contrast_code,
      FUN.VALUE = character(1)
    ),
    c(
      "fdr_robust",
      "fdr_cross_robust",
      "fdr_primary",
      "fdr_cross_primary",
      "fdr_single",
      "all3_raw",
      "count2_raw",
      "other_raw",
      "no_signal"
    )
  ),

  label = c(
    contrasts,
    c(
      "FDR_concordant_robust",
      "FDR_cross_supported_robust",
      "FDR_concordant_primary",
      "FDR_cross_supported_primary",
      "FDR_single_count_method",
      "All_three_nominal_concordant",
      "Count_methods_nominal_concordant",
      "Other_nominal_signal",
      "No_integrated_signal"
    )
  ),

  stringsAsFactors = FALSE
)


utils::write.csv(
  output_path_dictionary,
  prepare_output_file(
    file.path(
      integrated_results_dir,
      "output_path_dictionary.csv"
    )
  ),
  row.names = FALSE
)


message(
  "\n============================================================"
)

message(
  "06_integrated_method_comparison.R"
)

message(
  "Analysis ID: ",
  context$analysis_id
)

message(
  "Role: ",
  context$role
)

message(
  "Expected n: ",
  context$expected_n
)

message(
  "Integrating RPM + edgeR-TMM + DESeq2 without a predefined miRNA panel."
)

message(
  "============================================================\n"
)


# ==============================================================================
# 3. INPUTS
# ==============================================================================

required_common <- c(

  filtered_RPM = file.path(
    results_dir,
    "filtered_RPM.rds"
  ),

  metadata = file.path(
    results_dir,
    "metadata_analysis_samples.rds"
  )
)


missing_common <- required_common[
  !file.exists(
    required_common
  )
]


if (
  length(
    missing_common
  ) > 0L
) {

  stop(
    "Missing common input(s) from script 01:\n",
    paste(
      "-",
      missing_common,
      collapse = "\n"
    ),
    call. = FALSE
  )
}


if (
  !dir.exists(
    rpm_results_dir
  )
) {

  stop(
    "RPM differential-expression results are missing. Run script 04 first.",
    call. = FALSE
  )
}


if (
  !dir.exists(
    validation_results_dir
  )
) {

  stop(
    "Count-based differential-expression results are missing. Run script 05 first.",
    call. = FALSE
  )
}


rpm_matrix <- as.matrix(
  readRDS(
    required_common[[
      "filtered_RPM"
    ]]
  )
)


metadata <- as.data.frame(
  readRDS(
    required_common[[
      "metadata"
    ]]
  ),
  stringsAsFactors = FALSE
)


storage.mode(
  rpm_matrix
) <- "numeric"


# ==============================================================================
# 4. VALIDATION
# ==============================================================================

required_metadata_columns <- c(
  "Sample",
  "Apend_type",
  "Phenotype",
  "Phenotype_full",
  "Appendicitis_status",
  "Age",
  "Sex"
)


missing_metadata_columns <- setdiff(
  required_metadata_columns,
  colnames(
    metadata
  )
)


if (
  length(
    missing_metadata_columns
  ) > 0L
) {

  stop(
    "Metadata lacks required column(s): ",
    paste(
      missing_metadata_columns,
      collapse = ", "
    ),
    call. = FALSE
  )
}


metadata$Sample <- as.character(
  metadata$Sample
)


if (
  anyDuplicated(
    metadata$Sample
  ) > 0L
) {

  stop(
    "Duplicated sample identifiers detected in metadata.",
    call. = FALSE
  )
}


if (
  anyDuplicated(
    rownames(
      rpm_matrix
    )
  ) > 0L ||
  anyDuplicated(
    colnames(
      rpm_matrix
    )
  ) > 0L
) {

  stop(
    "Duplicated miRNA or sample identifiers detected in filtered_RPM.",
    call. = FALSE
  )
}


if (
  anyNA(
    rpm_matrix
  ) ||
  any(
    !is.finite(
      rpm_matrix
    )
  ) ||
  any(
    rpm_matrix < 0
  )
) {

  stop(
    "filtered_RPM contains invalid expression values.",
    call. = FALSE
  )
}


if (
  !setequal(
    colnames(
      rpm_matrix
    ),
    metadata$Sample
  )
) {

  stop(
    "filtered_RPM and metadata contain different samples.",
    call. = FALSE
  )
}


metadata <- metadata[
  match(
    colnames(
      rpm_matrix
    ),
    metadata$Sample
  ),
  ,
  drop = FALSE
]


if (
  !identical(
    metadata$Sample,
    colnames(
      rpm_matrix
    )
  )
) {

  stop(
    "Metadata and filtered_RPM are not identically ordered.",
    call. = FALSE
  )
}


metadata$Phenotype <- factor(
  as.character(
    metadata$Phenotype
  ),
  levels = c(
    "NIA",
    "Mild",
    "Severe"
  )
)


metadata$Phenotype_full <- factor(
  as.character(
    metadata$Phenotype_full
  ),
  levels = c(
    "Non-inflamed appendix",
    "Mild appendicitis",
    "Severe appendicitis"
  )
)


metadata$Appendicitis_status <- factor(
  as.character(
    metadata$Appendicitis_status
  ),
  levels = c(
    "NIA",
    "Appendicitis"
  )
)


if (
  anyNA(
    metadata$Phenotype
  ) ||
  anyNA(
    metadata$Phenotype_full
  ) ||
  anyNA(
    metadata$Appendicitis_status
  )
) {

  stop(
    "Canonical clinical labels contain missing or unexpected values.",
    call. = FALSE
  )
}


observed_phenotype <- table(
  metadata$Phenotype
)


if (
  ncol(rpm_matrix) != nrow(metadata) ||
  nrow(rpm_matrix) == 0L
) {
  stop(
    "Integrated-analysis inputs are empty or inconsistent across samples.",
    call. = FALSE
  )
}


message(
  "Common inputs validated: ",
  nrow(
    rpm_matrix
  ),
  " miRNAs x ",
  ncol(
    rpm_matrix
  ),
  " samples."
)

message(
  "Clinical groups: ",
  paste(
    names(
      observed_phenotype
    ),
    as.integer(
      observed_phenotype
    ),
    collapse = "; "
  )
)


# ==============================================================================
# 5. RESULT READERS
# ==============================================================================

read_rpm_table <- function(
    contrast
) {

  path <- file.path(
    rpm_results_dir,
    "tab",
    paste0(
      contrast_code(
        contrast
      ),
      ".csv"
    )
  )


  if (
    !file.exists(
      path
    )
  ) {

    stop(
      "Missing RPM result table: ",
      path,
      call. = FALSE
    )
  }


  x <- utils::read.csv(
    path,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )


  required <- c(
    "miRNA",
    "p_value",
    "FDR"
  )


  if (
    !all(
      required %in%
        colnames(
          x
        )
    )
  ) {

    stop(
      "Unexpected RPM result structure for ",
      contrast,
      ".",
      call. = FALSE
    )
  }


  effect <- if (
    "log2_median_ratio_group_1_vs_group_2" %in%
      colnames(
        x
      )
  ) {

    as.numeric(
      x$log2_median_ratio_group_1_vs_group_2
    )

  } else if (
    "log2_median_ratio" %in%
      colnames(
        x
      )
  ) {

    as.numeric(
      x$log2_median_ratio
    )

  } else {

    rep(
      NA_real_,
      nrow(
        x
      )
    )
  }


  out <- data.frame(

    miRNA = as.character(
      x$miRNA
    ),

    RPM_effect = effect,

    RPM_p = as.numeric(
      x$p_value
    ),

    RPM_FDR = as.numeric(
      x$FDR
    ),

    RPM_raw = (
      !is.na(
        x$p_value
      ) &
        x$p_value < ALPHA_RAW
    ),

    RPM_FDR_sig = (
      !is.na(
        x$FDR
      ) &
        x$FDR < ALPHA_FDR
    ),

    stringsAsFactors = FALSE
  )


  if (
    nrow(
      out
    ) !=
      nrow(
        rpm_matrix
      ) ||
    !setequal(
      out$miRNA,
      rownames(
        rpm_matrix
      )
    )
  ) {

    stop(
      "RPM result table for ",
      contrast,
      " does not contain exactly the upstream-frozen miRNA feature set.",
      call. = FALSE
    )
  }


  out
}


read_count_table <- function(
    model,
    method,
    contrast,
    suffix
) {

  path <- file.path(
    validation_results_dir,
    model_code(
      model
    ),
    method_code(
      method
    ),
    "tab",
    paste0(
      contrast_code(
        contrast
      ),
      ".csv"
    )
  )


  if (
    !file.exists(
      path
    )
  ) {

    return(
      NULL
    )
  }


  x <- utils::read.csv(
    path,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )


  required <- c(
    "miRNA",
    "p_value",
    "FDR"
  )


  if (
    !all(
      required %in%
        colnames(
          x
        )
    )
  ) {

    stop(
      "Unexpected count-method result structure: ",
      path,
      call. = FALSE
    )
  }


  effect <- if (
    "log2FC" %in%
      colnames(
        x
      )
  ) {

    as.numeric(
      x$log2FC
    )

  } else {

    rep(
      NA_real_,
      nrow(
        x
      )
    )
  }


  out <- data.frame(

    miRNA = as.character(
      x$miRNA
    ),

    effect = effect,

    p = as.numeric(
      x$p_value
    ),

    FDR = as.numeric(
      x$FDR
    ),

    raw = (
      !is.na(
        x$p_value
      ) &
        x$p_value < ALPHA_RAW
    ),

    FDR_sig = (
      !is.na(
        x$FDR
      ) &
        x$FDR < ALPHA_FDR
    ),

    stringsAsFactors = FALSE
  )


  if (
    nrow(
      out
    ) !=
      nrow(
        rpm_matrix
      ) ||
    !setequal(
      out$miRNA,
      rownames(
        rpm_matrix
      )
    )
  ) {

    stop(
      "Count-method result table ",
      path,
      " does not contain exactly the upstream-frozen miRNA feature set.",
      call. = FALSE
    )
  }


  colnames(
    out
  )[
    -1L
  ] <- paste0(
    suffix,
    "_",
    colnames(
      out
    )[
      -1L
    ]
  )


  out
}


# ==============================================================================
# 6. CONCORDANCE HELPERS
# ==============================================================================

same_direction <- function(
    effect_1,
    effect_2,
    global_test = FALSE
) {

  if (
    isTRUE(
      global_test
    )
  ) {

    return(
      rep(
        TRUE,
        length(
          effect_1
        )
      )
    )
  }


  valid <- (
    is.finite(
      effect_1
    ) &
      is.finite(
        effect_2
      ) &
      effect_1 != 0 &
      effect_2 != 0
  )


  out <- rep(
    FALSE,
    length(
      effect_1
    )
  )


  out[
    valid
  ] <- sign(
    effect_1[
      valid
    ]
  ) ==
    sign(
      effect_2[
        valid
      ]
    )


  out
}


same_direction_three <- function(
    effect_1,
    effect_2,
    effect_3,
    global_test = FALSE
) {

  if (
    isTRUE(
      global_test
    )
  ) {

    return(
      rep(
        TRUE,
        length(
          effect_1
        )
      )
    )
  }


  valid <- (
    is.finite(
      effect_1
    ) &
      is.finite(
        effect_2
      ) &
      is.finite(
        effect_3
      ) &
      effect_1 != 0 &
      effect_2 != 0 &
      effect_3 != 0
  )


  out <- rep(
    FALSE,
    length(
      effect_1
    )
  )


  out[
    valid
  ] <- (
    sign(
      effect_1[
        valid
      ]
    ) ==
      sign(
        effect_2[
          valid
        ]
      ) &
      sign(
        effect_2[
          valid
        ]
      ) ==
        sign(
          effect_3[
            valid
          ]
        )
  )


  out
}


collapse_values <- function(
    x
) {

  x <- unique(
    as.character(
      x[
        !is.na(
          x
        ) &
          nzchar(
            as.character(
              x
            )
          )
      ]
    )
  )


  if (
    length(
      x
    ) == 0L
  ) {

    return(
      ""
    )
  }


  paste(
    x,
    collapse = "; "
  )
}


safe_min <- function(
    x
) {

  x <- as.numeric(
    x
  )

  x <- x[
    !is.na(
      x
    ) &
      is.finite(
        x
      )
  ]


  if (
    length(
      x
    ) == 0L
  ) {

    return(
      NA_real_
    )
  }


  min(
    x
  )
}


# ==============================================================================
# 7. BUILD INTEGRATED CONTRAST TABLES
# ==============================================================================

integrated_tables <- list()


adjusted_available <- (
  dir.exists(
    file.path(
      validation_results_dir,
      model_code(
        "adjusted_age_sex"
      )
    )
  )
)


for (
  contrast in contrasts
) {

  message(
    "Integrating: ",
    contrast
  )


  spec <- contrast_specs[[
    contrast
  ]]


  rpm_tab <- read_rpm_table(
    contrast
  )


  edgeR_unadjusted <- read_count_table(
    model = "unadjusted",
    method = "edgeR_TMM",
    contrast = contrast,
    suffix = "edgeR"
  )


  DESeq2_unadjusted <- read_count_table(
    model = "unadjusted",
    method = "DESeq2",
    contrast = contrast,
    suffix = "DESeq2"
  )


  if (
    is.null(
      edgeR_unadjusted
    ) ||
    is.null(
      DESeq2_unadjusted
    )
  ) {

    stop(
      "Missing primary unadjusted edgeR or DESeq2 results for ",
      contrast,
      ".",
      call. = FALSE
    )
  }


  integrated <- rpm_tab |>
    dplyr::left_join(
      edgeR_unadjusted,
      by = "miRNA"
    ) |>
    dplyr::left_join(
      DESeq2_unadjusted,
      by = "miRNA"
    )


  integrated$count_direction_concordant_unadjusted <- same_direction(
    integrated$edgeR_effect,
    integrated$DESeq2_effect,
    global_test = spec$global_test
  )


  integrated$all_three_direction_concordant <- same_direction_three(
    integrated$RPM_effect,
    integrated$edgeR_effect,
    integrated$DESeq2_effect,
    global_test = spec$global_test
  )


  integrated$count_nominal_both_unadjusted <- (
    integrated$edgeR_raw &
      integrated$DESeq2_raw &
      integrated$count_direction_concordant_unadjusted
  )


  integrated$all_three_nominal_unadjusted <- (
    integrated$RPM_raw &
      integrated$edgeR_raw &
      integrated$DESeq2_raw &
      integrated$all_three_direction_concordant
  )


  integrated$count_FDR_both_unadjusted <- (
    integrated$edgeR_FDR_sig &
      integrated$DESeq2_FDR_sig &
      integrated$count_direction_concordant_unadjusted
  )


  integrated$count_FDR_cross_supported_unadjusted <- (
    (
      integrated$edgeR_FDR_sig &
        integrated$DESeq2_raw
    ) |
      (
        integrated$DESeq2_FDR_sig &
          integrated$edgeR_raw
      )
  ) &
    integrated$count_direction_concordant_unadjusted


  integrated$count_any_FDR_unadjusted <- (
    integrated$edgeR_FDR_sig |
      integrated$DESeq2_FDR_sig
  )


  integrated$RPM_supports_count_FDR_unadjusted <- (
    integrated$RPM_raw &
      integrated$count_FDR_cross_supported_unadjusted &
      integrated$all_three_direction_concordant
  )


  # ---------------------------------------------------------------------------
  # Age + sex sensitivity
  # ---------------------------------------------------------------------------

  if (
    adjusted_available
  ) {

    edgeR_adjusted <- read_count_table(
      model = "adjusted_age_sex",
      method = "edgeR_TMM",
      contrast = contrast,
      suffix = "edgeR_adjusted"
    )


    DESeq2_adjusted <- read_count_table(
      model = "adjusted_age_sex",
      method = "DESeq2",
      contrast = contrast,
      suffix = "DESeq2_adjusted"
    )

  } else {

    edgeR_adjusted <- NULL
    DESeq2_adjusted <- NULL
  }


  if (
    !is.null(
      edgeR_adjusted
    ) &&
    !is.null(
      DESeq2_adjusted
    )
  ) {

    integrated <- integrated |>
      dplyr::left_join(
        edgeR_adjusted,
        by = "miRNA"
      ) |>
      dplyr::left_join(
        DESeq2_adjusted,
        by = "miRNA"
      )


    integrated$count_direction_concordant_adjusted <- same_direction(
      integrated$edgeR_adjusted_effect,
      integrated$DESeq2_adjusted_effect,
      global_test = spec$global_test
    )


    integrated$count_nominal_both_adjusted <- (
      integrated$edgeR_adjusted_raw &
        integrated$DESeq2_adjusted_raw &
        integrated$count_direction_concordant_adjusted
    )


    integrated$count_FDR_both_adjusted <- (
      integrated$edgeR_adjusted_FDR_sig &
        integrated$DESeq2_adjusted_FDR_sig &
        integrated$count_direction_concordant_adjusted
    )


    integrated$count_FDR_cross_supported_adjusted <- (
      (
        integrated$edgeR_adjusted_FDR_sig &
          integrated$DESeq2_adjusted_raw
      ) |
        (
          integrated$DESeq2_adjusted_FDR_sig &
            integrated$edgeR_adjusted_raw
        )
    ) &
      integrated$count_direction_concordant_adjusted


    integrated$count_any_FDR_adjusted <- (
      integrated$edgeR_adjusted_FDR_sig |
        integrated$DESeq2_adjusted_FDR_sig
    )


    integrated$edgeR_direction_stable_after_adjustment <- same_direction(
      integrated$edgeR_effect,
      integrated$edgeR_adjusted_effect,
      global_test = spec$global_test
    )


    integrated$DESeq2_direction_stable_after_adjustment <- same_direction(
      integrated$DESeq2_effect,
      integrated$DESeq2_adjusted_effect,
      global_test = spec$global_test
    )

  } else {

    integrated$edgeR_adjusted_effect <- NA_real_
    integrated$edgeR_adjusted_p <- NA_real_
    integrated$edgeR_adjusted_FDR <- NA_real_
    integrated$edgeR_adjusted_raw <- FALSE
    integrated$edgeR_adjusted_FDR_sig <- FALSE

    integrated$DESeq2_adjusted_effect <- NA_real_
    integrated$DESeq2_adjusted_p <- NA_real_
    integrated$DESeq2_adjusted_FDR <- NA_real_
    integrated$DESeq2_adjusted_raw <- FALSE
    integrated$DESeq2_adjusted_FDR_sig <- FALSE

    integrated$count_direction_concordant_adjusted <- FALSE
    integrated$count_nominal_both_adjusted <- FALSE
    integrated$count_FDR_both_adjusted <- FALSE
    integrated$count_FDR_cross_supported_adjusted <- FALSE
    integrated$count_any_FDR_adjusted <- FALSE
    integrated$edgeR_direction_stable_after_adjustment <- FALSE
    integrated$DESeq2_direction_stable_after_adjustment <- FALSE
  }


  integrated$FDR_concordant_robust_same_contrast <- (
    integrated$count_FDR_both_unadjusted &
      integrated$count_FDR_both_adjusted
  )


  integrated$FDR_cross_supported_robust_same_contrast <- (
    integrated$count_FDR_cross_supported_unadjusted &
      integrated$count_FDR_cross_supported_adjusted
  )


  integrated$nominal_count_robust_same_contrast <- (
    integrated$count_nominal_both_unadjusted &
      integrated$count_nominal_both_adjusted
  )


  integrated$contrast <- contrast
  integrated$global_test <- spec$global_test

  integrated$positive_effect_definition <- if (
    isTRUE(
      spec$global_test
    )
  ) {

    "Omnibus test; no unique effect direction"

  } else {

    paste0(
      "Positive effect = higher in ",
      spec$positive_group,
      " than ",
      spec$negative_group
    )
  }


  integrated <- integrated |>
    dplyr::arrange(
      dplyr::desc(
        FDR_concordant_robust_same_contrast
      ),
      dplyr::desc(
        count_FDR_both_unadjusted
      ),
      dplyr::desc(
        count_FDR_cross_supported_unadjusted
      ),
      dplyr::desc(
        all_three_nominal_unadjusted
      ),
      dplyr::desc(
        count_nominal_both_unadjusted
      ),
      edgeR_FDR,
      DESeq2_FDR,
      RPM_FDR
    )


  utils::write.csv(
    integrated,
    prepare_output_file(
      file.path(
        integrated_results_dir,
        paste0(
          contrast,
          "_integrated_results.csv"
        )
      )
    ),
    row.names = FALSE
  )


  integrated_tables[[
    contrast
  ]] <- integrated
}


# ==============================================================================
# 8. LONG EVIDENCE TABLE
# ==============================================================================

integrated_evidence_long <- dplyr::bind_rows(
  integrated_tables
)


integrated_evidence_long$analysis_id <- context$analysis_id


expected_long_rows <- (
  nrow(
    rpm_matrix
  ) *
    length(
      contrasts
    )
)


if (
  nrow(
    integrated_evidence_long
  ) !=
    expected_long_rows
) {

  stop(
    "Integrated evidence table has ",
    nrow(
      integrated_evidence_long
    ),
    " rows; expected ",
    expected_long_rows,
    ".",
    call. = FALSE
  )
}


utils::write.csv(
  integrated_evidence_long,
  prepare_output_file(
    file.path(
      integrated_results_dir,
      "integrated_evidence_long.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 9. METHOD CONCORDANCE SUMMARY
# ==============================================================================

method_concordance_summary <- integrated_evidence_long |>
  dplyr::group_by(
    contrast
  ) |>
  dplyr::summarise(

    n_miRNAs = dplyr::n(),

    RPM_nominal = sum(
      RPM_raw,
      na.rm = TRUE
    ),

    edgeR_nominal = sum(
      edgeR_raw,
      na.rm = TRUE
    ),

    DESeq2_nominal = sum(
      DESeq2_raw,
      na.rm = TRUE
    ),

    count_nominal_both = sum(
      count_nominal_both_unadjusted,
      na.rm = TRUE
    ),

    all_three_nominal = sum(
      all_three_nominal_unadjusted,
      na.rm = TRUE
    ),

    edgeR_FDR = sum(
      edgeR_FDR_sig,
      na.rm = TRUE
    ),

    DESeq2_FDR = sum(
      DESeq2_FDR_sig,
      na.rm = TRUE
    ),

    count_FDR_both = sum(
      count_FDR_both_unadjusted,
      na.rm = TRUE
    ),

    count_FDR_cross_supported = sum(
      count_FDR_cross_supported_unadjusted,
      na.rm = TRUE
    ),

    RPM_supports_count_FDR = sum(
      RPM_supports_count_FDR_unadjusted,
      na.rm = TRUE
    ),

    adjusted_count_nominal_both = sum(
      count_nominal_both_adjusted,
      na.rm = TRUE
    ),

    adjusted_count_FDR_both = sum(
      count_FDR_both_adjusted,
      na.rm = TRUE
    ),

    adjusted_count_FDR_cross_supported = sum(
      count_FDR_cross_supported_adjusted,
      na.rm = TRUE
    ),

    robust_FDR_both_same_contrast = sum(
      FDR_concordant_robust_same_contrast,
      na.rm = TRUE
    ),

    .groups = "drop"
  )


utils::write.csv(
  method_concordance_summary,
  prepare_output_file(
    file.path(
      integrated_results_dir,
      "method_concordance_summary.csv"
    )
  ),
  row.names = FALSE
)


print(
  method_concordance_summary
)


# ==============================================================================
# 10. PER-miRNA INTEGRATED SUMMARY
# ==============================================================================

summarize_integrated_evidence <- function(
    evidence_data
) {

  evidence_data |>
    dplyr::group_by(
      miRNA
    ) |>
    dplyr::summarise(

      n_analyses = dplyr::n(),

      n_RPM_nominal = sum(
        RPM_raw,
        na.rm = TRUE
      ),

      n_edgeR_nominal = sum(
        edgeR_raw,
        na.rm = TRUE
      ),

      n_DESeq2_nominal = sum(
        DESeq2_raw,
        na.rm = TRUE
      ),

      n_count_nominal_both = sum(
        count_nominal_both_unadjusted,
        na.rm = TRUE
      ),

      n_all_three_nominal = sum(
        all_three_nominal_unadjusted,
        na.rm = TRUE
      ),

      n_count_FDR_any = sum(
        count_any_FDR_unadjusted,
        na.rm = TRUE
      ),

      n_count_FDR_cross_supported = sum(
        count_FDR_cross_supported_unadjusted,
        na.rm = TRUE
      ),

      n_count_FDR_both = sum(
        count_FDR_both_unadjusted,
        na.rm = TRUE
      ),

      n_RPM_supports_count_FDR = sum(
        RPM_supports_count_FDR_unadjusted,
        na.rm = TRUE
      ),

      n_adjusted_count_nominal_both = sum(
        count_nominal_both_adjusted,
        na.rm = TRUE
      ),

      n_adjusted_count_FDR_cross_supported = sum(
        count_FDR_cross_supported_adjusted,
        na.rm = TRUE
      ),

      n_adjusted_count_FDR_both = sum(
        count_FDR_both_adjusted,
        na.rm = TRUE
      ),

      n_FDR_concordant_robust_same_contrast = sum(
        FDR_concordant_robust_same_contrast,
        na.rm = TRUE
      ),

      n_FDR_cross_supported_robust_same_contrast = sum(
        FDR_cross_supported_robust_same_contrast,
        na.rm = TRUE
      ),

      n_nominal_count_robust_same_contrast = sum(
        nominal_count_robust_same_contrast,
        na.rm = TRUE
      ),

      minimum_RPM_p = safe_min(
        RPM_p
      ),

      minimum_RPM_FDR = safe_min(
        RPM_FDR
      ),

      minimum_edgeR_p = safe_min(
        edgeR_p
      ),

      minimum_edgeR_FDR = safe_min(
        edgeR_FDR
      ),

      minimum_DESeq2_p = safe_min(
        DESeq2_p
      ),

      minimum_DESeq2_FDR = safe_min(
        DESeq2_FDR
      ),

      minimum_edgeR_adjusted_FDR = safe_min(
        edgeR_adjusted_FDR
      ),

      minimum_DESeq2_adjusted_FDR = safe_min(
        DESeq2_adjusted_FDR
      ),

      RPM_nominal_analyses = collapse_values(
        contrast[
          RPM_raw %in%
            TRUE
        ]
      ),

      count_nominal_concordant_analyses = collapse_values(
        contrast[
          count_nominal_both_unadjusted %in%
            TRUE
        ]
      ),

      all_three_nominal_analyses = collapse_values(
        contrast[
          all_three_nominal_unadjusted %in%
            TRUE
        ]
      ),

      count_FDR_cross_supported_analyses = collapse_values(
        contrast[
          count_FDR_cross_supported_unadjusted %in%
            TRUE
        ]
      ),

      count_FDR_concordant_analyses = collapse_values(
        contrast[
          count_FDR_both_unadjusted %in%
            TRUE
        ]
      ),

      adjusted_FDR_cross_supported_analyses = collapse_values(
        contrast[
          count_FDR_cross_supported_adjusted %in%
            TRUE
        ]
      ),

      adjusted_FDR_concordant_analyses = collapse_values(
        contrast[
          count_FDR_both_adjusted %in%
            TRUE
        ]
      ),

      robust_FDR_concordant_analyses = collapse_values(
        contrast[
          FDR_concordant_robust_same_contrast %in%
            TRUE
        ]
      ),

      .groups = "drop"
    )
}


candidate_summary_all <- summarize_integrated_evidence(
  integrated_evidence_long
)


candidate_summary_phenotype <- summarize_integrated_evidence(
  integrated_evidence_long |>
    dplyr::filter(
      contrast %in%
        phenotype_contrasts
    )
)


# ==============================================================================
# 10.1 Evidence class
# ==============================================================================

add_evidence_class <- function(
    summary_table
) {

  summary_table$any_primary_nominal_signal <- (
    summary_table$n_RPM_nominal > 0L |
      summary_table$n_edgeR_nominal > 0L |
      summary_table$n_DESeq2_nominal > 0L
  )


  summary_table$evidence_class <- dplyr::case_when(

    summary_table$n_FDR_concordant_robust_same_contrast > 0L ~
      "FDR_concordant_robust",

    summary_table$n_FDR_cross_supported_robust_same_contrast > 0L ~
      "FDR_cross_supported_robust",

    summary_table$n_count_FDR_both > 0L ~
      "FDR_concordant_primary",

    summary_table$n_count_FDR_cross_supported > 0L ~
      "FDR_cross_supported_primary",

    summary_table$n_count_FDR_any > 0L ~
      "FDR_single_count_method",

    summary_table$n_all_three_nominal > 0L ~
      "All_three_nominal_concordant",

    summary_table$n_count_nominal_both > 0L ~
      "Count_methods_nominal_concordant",

    summary_table$any_primary_nominal_signal ~
      "Other_nominal_signal",

    TRUE ~
      "No_integrated_signal"
  )


  evidence_order <- c(
    "FDR_concordant_robust",
    "FDR_cross_supported_robust",
    "FDR_concordant_primary",
    "FDR_cross_supported_primary",
    "FDR_single_count_method",
    "All_three_nominal_concordant",
    "Count_methods_nominal_concordant",
    "Other_nominal_signal",
    "No_integrated_signal"
  )


  summary_table$evidence_class <- factor(
    summary_table$evidence_class,
    levels = evidence_order
  )


  summary_table <- summary_table |>
    dplyr::arrange(
      evidence_class,
      dplyr::desc(
        n_FDR_concordant_robust_same_contrast
      ),
      dplyr::desc(
        n_count_FDR_both
      ),
      dplyr::desc(
        n_count_FDR_cross_supported
      ),
      dplyr::desc(
        n_all_three_nominal
      ),
      dplyr::desc(
        n_count_nominal_both
      ),
      minimum_edgeR_FDR,
      minimum_DESeq2_FDR,
      minimum_RPM_p
    )


  summary_table$evidence_class <- as.character(
    summary_table$evidence_class
  )


  summary_table
}


candidate_summary_all <- add_evidence_class(
  candidate_summary_all
)


candidate_summary_phenotype <- add_evidence_class(
  candidate_summary_phenotype
)


if (
  nrow(
    candidate_summary_all
  ) !=
    nrow(
      rpm_matrix
    ) ||
  !setequal(
    candidate_summary_all$miRNA,
    rownames(
      rpm_matrix
    )
  )
) {

  stop(
    "All-analysis candidate summary does not contain exactly the upstream-frozen miRNA feature set.",
    call. = FALSE
  )
}


if (
  nrow(
    candidate_summary_phenotype
  ) !=
    nrow(
      rpm_matrix
    ) ||
  !setequal(
    candidate_summary_phenotype$miRNA,
    rownames(
      rpm_matrix
    )
  )
) {

  stop(
    "Phenotype candidate summary does not contain exactly the upstream-frozen miRNA feature set.",
    call. = FALSE
  )
}


utils::write.csv(
  candidate_summary_all,
  prepare_output_file(
    file.path(
      integrated_results_dir,
      "integrated_candidate_summary_all_analyses.csv"
    )
  ),
  row.names = FALSE
)


utils::write.csv(
  candidate_summary_phenotype,
  prepare_output_file(
    file.path(
      integrated_results_dir,
      "integrated_candidate_summary_phenotype.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 11. FINAL DOWNSTREAM CANDIDATE HIERARCHY
# ==============================================================================

# Script 06 is the single source of truth for the miRNAs carried forward into
# downstream clinical and in-silico analyses.
#
# The hierarchy is derived from the integrated evidence classes:
#
#   Primary_robust
#       FDR_concordant_robust
#       FDR_cross_supported_robust
#
#   Secondary_integrated
#       All_three_nominal_concordant
#
# All remaining miRNAs stay in the complete integrated evidence tables but are
# not carried forward into targeted downstream analyses.

candidate_priority_all <- candidate_summary_all |>
  dplyr::mutate(
    downstream_category = dplyr::case_when(
      evidence_class %in% c(
        "FDR_concordant_robust",
        "FDR_cross_supported_robust"
      ) ~ "Primary_robust",

      evidence_class ==
        "All_three_nominal_concordant" ~
        "Secondary_integrated",

      TRUE ~
        "Exploratory_not_carried_forward"
    ),
    best_evidence_class = evidence_class
  )


downstream_candidate_priority <- candidate_priority_all |>
  dplyr::filter(
    downstream_category %in% c(
      "Primary_robust",
      "Secondary_integrated"
    )
  ) |>
  dplyr::mutate(
    downstream_rank = dplyr::row_number()
  )


candidate_hierarchy_summary <- candidate_priority_all |>
  dplyr::count(
    downstream_category,
    name = "n_miRNAs"
  )


if (
  anyDuplicated(
    downstream_candidate_priority$miRNA
  ) > 0L
) {
  stop(
    "Duplicated miRNAs detected in the downstream candidate hierarchy.",
    call. = FALSE
  )
}


utils::write.csv(
  downstream_candidate_priority,
  prepare_output_file(
    file.path(
      integrated_results_dir,
      "downstream_candidate_priority.csv"
    )
  ),
  row.names = FALSE
)


utils::write.csv(
  candidate_hierarchy_summary,
  prepare_output_file(
    file.path(
      integrated_results_dir,
      "candidate_hierarchy_summary.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 12. EXPLICIT DATA-DRIVEN CANDIDATE SETS
# ==============================================================================

candidates_count_nominal_concordant <- candidate_summary_all |>
  dplyr::filter(
    n_count_nominal_both > 0L
  )


candidates_all_three_nominal <- candidate_summary_all |>
  dplyr::filter(
    n_all_three_nominal > 0L
  )


candidates_primary_FDR_supported <- candidate_summary_all |>
  dplyr::filter(
    n_count_FDR_any > 0L
  )


candidates_primary_FDR_cross_supported <- candidate_summary_all |>
  dplyr::filter(
    n_count_FDR_cross_supported > 0L
  )


candidates_age_sex_robust_FDR <- candidate_summary_all |>
  dplyr::filter(
    n_FDR_cross_supported_robust_same_contrast > 0L |
      n_FDR_concordant_robust_same_contrast > 0L
  )


utils::write.csv(
  candidates_count_nominal_concordant,
  prepare_output_file(
    file.path(
      integrated_results_dir,
      "candidates_count_nominal_concordant.csv"
    )
  ),
  row.names = FALSE
)


utils::write.csv(
  candidates_all_three_nominal,
  prepare_output_file(
    file.path(
      integrated_results_dir,
      "candidates_all_three_nominal_concordant.csv"
    )
  ),
  row.names = FALSE
)


utils::write.csv(
  candidates_primary_FDR_supported,
  prepare_output_file(
    file.path(
      integrated_results_dir,
      "candidates_primary_FDR_supported.csv"
    )
  ),
  row.names = FALSE
)


utils::write.csv(
  candidates_primary_FDR_cross_supported,
  prepare_output_file(
    file.path(
      integrated_results_dir,
      "candidates_primary_FDR_cross_supported.csv"
    )
  ),
  row.names = FALSE
)


utils::write.csv(
  candidates_age_sex_robust_FDR,
  prepare_output_file(
    file.path(
      integrated_results_dir,
      "candidates_age_sex_robust_FDR.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 13. AGE + SEX STABILITY
# ==============================================================================

age_sex_stability <- integrated_evidence_long |>
  dplyr::select(
    miRNA,
    contrast,
    global_test,
    edgeR_effect,
    edgeR_p,
    edgeR_FDR,
    edgeR_adjusted_effect,
    edgeR_adjusted_p,
    edgeR_adjusted_FDR,
    edgeR_direction_stable_after_adjustment,
    DESeq2_effect,
    DESeq2_p,
    DESeq2_FDR,
    DESeq2_adjusted_effect,
    DESeq2_adjusted_p,
    DESeq2_adjusted_FDR,
    DESeq2_direction_stable_after_adjustment,
    count_nominal_both_unadjusted,
    count_nominal_both_adjusted,
    count_FDR_cross_supported_unadjusted,
    count_FDR_cross_supported_adjusted,
    count_FDR_both_unadjusted,
    count_FDR_both_adjusted
  )


utils::write.csv(
  age_sex_stability,
  prepare_output_file(
    file.path(
      integrated_results_dir,
      "age_sex_stability.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 14. INTEGRATED VISUALIZATION HELPERS
# ==============================================================================

log2_rpm <- log2(
  rpm_matrix +
    1
)


save_integrated_heatmap <- function(
    selected_miRNAs,
    set_code,
    set_label
) {

  selected_miRNAs <- intersect(
    unique(
      selected_miRNAs
    ),
    rownames(
      log2_rpm
    )
  )


  if (
    length(
      selected_miRNAs
    ) == 0L
  ) {

    message(
      "Integrated heatmap skipped for ",
      set_label,
      ": no miRNAs."
    )

    return(
      invisible(
        NULL
      )
    )
  }


  plot_metadata <- metadata |>
    dplyr::arrange(
      Phenotype,
      Sample
    )


  ordered_samples <- plot_metadata$Sample


  matrix_selected <- log2_rpm[
    selected_miRNAs,
    ordered_samples,
    drop = FALSE
  ]


  z_matrix <- t(
    scale(
      t(
        matrix_selected
      )
    )
  )


  z_matrix[
    !is.finite(
      z_matrix
    )
  ] <- 0


  annotation <- ComplexHeatmap::HeatmapAnnotation(
    Phenotype = plot_metadata$Phenotype,
    annotation_name_side = "left"
  )


  heatmap_object <- ComplexHeatmap::Heatmap(

    z_matrix,

    name = "Row Z-score",

    col = circlize::colorRamp2(
      c(
        -2,
        0,
        2
      ),
      c(
        "navy",
        "white",
        "firebrick3"
      )
    ),

    top_annotation = annotation,

    column_split = plot_metadata$Phenotype,

    cluster_rows = length(
      selected_miRNAs
    ) > 1L,

    cluster_columns = FALSE,

    show_column_names = FALSE,

    show_row_names = TRUE,

    row_names_gp = grid::gpar(
      fontsize = if (
        length(
          selected_miRNAs
        ) > 35L
      ) {
        6.5
      } else {
        8
      }
    ),

    column_title = paste0(
      set_label,
      " (",
      length(
        selected_miRNAs
      ),
      " miRNAs)"
    ),

    use_raster = FALSE
  )


  output_dir <- file.path(
    heatmap_dir,
    set_code
  )


  ensure_dir(
    output_dir
  )


  figure_height <- max(
    5,
    min(
      12,
      0.20 *
        length(
          selected_miRNAs
        ) +
        3.5
    )
  )


  draw_heatmap <- function() {

    ComplexHeatmap::draw(
      heatmap_object,
      heatmap_legend_side = "right",
      annotation_legend_side = "right"
    )
  }


  draw_to_pdf(
    filename = file.path(
      output_dir,
      paste0(
        set_code,
        "_heatmap.pdf"
      )
    ),
    width = 8,
    height = figure_height,
    draw = draw_heatmap
  )


  draw_to_tiff(
    filename = file.path(
      output_dir,
      paste0(
        set_code,
        "_heatmap.tiff"
      )
    ),
    width = 8,
    height = figure_height,
    units = "in",
    res = 600,
    compression = "lzw",
    draw = draw_heatmap
  )


  utils::write.csv(
    data.frame(
      candidate_set = set_code,
      definition = set_label,
      miRNA = selected_miRNAs,
      stringsAsFactors = FALSE
    ),
    prepare_output_file(
      file.path(
        output_dir,
        paste0(
          set_code,
          "_miRNAs.csv"
        )
      )
    ),
    row.names = FALSE
  )


  invisible(
    heatmap_object
  )
}


save_integrated_pca <- function(
    selected_miRNAs,
    set_code,
    set_label
) {

  selected_miRNAs <- intersect(
    unique(
      selected_miRNAs
    ),
    rownames(
      log2_rpm
    )
  )


  if (
    length(
      selected_miRNAs
    ) < 2L
  ) {

    message(
      "Integrated PCA skipped for ",
      set_label,
      ": fewer than two miRNAs."
    )

    return(
      invisible(
        NULL
      )
    )
  }


  pca_matrix <- log2_rpm[
    selected_miRNAs,
    metadata$Sample,
    drop = FALSE
  ]


  feature_sd <- apply(
    pca_matrix,
    1L,
    stats::sd
  )


  pca_matrix <- pca_matrix[
    is.finite(
      feature_sd
    ) &
      feature_sd > 0,
    ,
    drop = FALSE
  ]


  if (
    nrow(
      pca_matrix
    ) < 2L
  ) {

    return(
      invisible(
        NULL
      )
    )
  }


  pca <- stats::prcomp(
    t(
      pca_matrix
    ),
    center = TRUE,
    scale. = TRUE
  )


  variance <- (
    pca$sdev^2
  ) /
    sum(
      pca$sdev^2
    )


  pca_df <- data.frame(

    Sample = rownames(
      pca$x
    ),

    PC1 = pca$x[
      ,
      1L
    ],

    PC2 = pca$x[
      ,
      2L
    ],

    stringsAsFactors = FALSE
  )


  if (
    ncol(
      pca$x
    ) >= 3L
  ) {

    pca_df$PC3 <- pca$x[
      ,
      3L
    ]
  }


  pca_df <- dplyr::left_join(
    pca_df,
    metadata[
      ,
      c(
        "Sample",
        "Phenotype",
        "Phenotype_full",
        "Appendicitis_status",
        "Age",
        "Sex"
      ),
      drop = FALSE
    ],
    by = "Sample"
  )


  group_counts <- table(
    pca_df$Phenotype
  )


  eligible_groups <- names(
    group_counts[
      group_counts >= 3L
    ]
  )


  ellipse_data <- pca_df[
    as.character(
      pca_df$Phenotype
    ) %in%
      eligible_groups,
    ,
    drop = FALSE
  ]


  plot_object <- ggplot2::ggplot(
    pca_df,
    ggplot2::aes(
      x = PC1,
      y = PC2,
      color = Phenotype
    )
  )


  if (
    nrow(
      ellipse_data
    ) > 0L
  ) {

    plot_object <- plot_object +
      ggplot2::stat_ellipse(
        data = ellipse_data,
        ggplot2::aes(
          fill = Phenotype
        ),
        geom = "polygon",
        type = "norm",
        level = 0.95,
        alpha = 0.12,
        color = NA,
        show.legend = FALSE
      ) +
      ggplot2::stat_ellipse(
        data = ellipse_data,
        type = "norm",
        level = 0.95,
        linewidth = 0.6,
        alpha = 0.85,
        show.legend = FALSE
      )
  }


  plot_object <- plot_object +
    ggplot2::geom_point(
      size = 3,
      alpha = 0.95
    ) +
    ggplot2::labs(
      title = paste0(
        set_label,
        " — exploratory PCA"
      ),
      subtitle = paste0(
        nrow(
          pca_matrix
        ),
        " miRNAs; integrated post-selection visualization"
      ),
      x = sprintf(
        "PC1 (%.1f%%)",
        100 *
          variance[1L]
      ),
      y = sprintf(
        "PC2 (%.1f%%)",
        100 *
          variance[2L]
      ),
      color = NULL
    ) +
    ggplot2::theme_classic(
      base_size = 11
    ) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(
        face = "bold"
      ),
      legend.position = "right"
    )


  output_dir <- file.path(
    pca_dir,
    set_code
  )


  ensure_dir(
    output_dir
  )


  save_ggplot_pdf(
    plot = plot_object,
    filename = file.path(
      output_dir,
      paste0(
        set_code,
        "_PCA_PC1_PC2.pdf"
      )
    ),
    width = 7,
    height = 5
  )


  save_ggplot_tiff(
    plot = plot_object,
    filename = file.path(
      output_dir,
      paste0(
        set_code,
        "_PCA_PC1_PC2.tiff"
      )
    ),
    width = 7,
    height = 5,
    dpi = 600
  )


  utils::write.csv(
    pca_df,
    prepare_output_file(
      file.path(
        output_dir,
        paste0(
          set_code,
          "_PCA_coordinates.csv"
        )
      )
    ),
    row.names = FALSE
  )


  utils::write.csv(
    data.frame(
      PC = paste0(
        "PC",
        seq_along(
          variance
        )
      ),
      variance_explained_pct = 100 *
        variance,
      cumulative_variance_explained_pct = 100 *
        cumsum(
          variance
        ),
      stringsAsFactors = FALSE
    ),
    prepare_output_file(
      file.path(
        output_dir,
        paste0(
          set_code,
          "_PCA_variance.csv"
        )
      )
    ),
    row.names = FALSE
  )


  invisible(
    list(
      pca = pca,
      coordinates = pca_df,
      variance = variance,
      plot = plot_object
    )
  )
}


save_integrated_visual_pair <- function(
    selected_miRNAs,
    set_code,
    set_label
) {

  heatmap_object <- save_integrated_heatmap(
    selected_miRNAs = selected_miRNAs,
    set_code = set_code,
    set_label = set_label
  )


  pca_object <- save_integrated_pca(
    selected_miRNAs = selected_miRNAs,
    set_code = set_code,
    set_label = set_label
  )


  invisible(
    list(
      heatmap = heatmap_object,
      pca = pca_object
    )
  )
}


# ==============================================================================
# 15. INTEGRATED POST-SELECTION VISUALIZATIONS
# ==============================================================================

visual_count_nominal <- save_integrated_visual_pair(

  selected_miRNAs =
    candidates_count_nominal_concordant$miRNA,

  set_code =
    "count_nominal_concordant",

  set_label =
    "Count-method nominal concordance"
)


visual_all_three <- save_integrated_visual_pair(

  selected_miRNAs =
    candidates_all_three_nominal$miRNA,

  set_code =
    "all_three_nominal",

  set_label =
    "RPM + edgeR + DESeq2 nominal concordance"
)


visual_primary_FDR <- save_integrated_visual_pair(

  selected_miRNAs =
    candidates_primary_FDR_cross_supported$miRNA,

  set_code =
    "primary_FDR_cross_supported",

  set_label =
    "Primary count-based FDR with cross-method support"
)


visual_robust_FDR <- save_integrated_visual_pair(

  selected_miRNAs =
    candidates_age_sex_robust_FDR$miRNA,

  set_code =
    "age_sex_robust_FDR",

  set_label =
    "FDR evidence robust after age + sex adjustment"
)


# ==============================================================================
# 16. MANIFEST
# ==============================================================================

manifest <- data.frame(

  analysis_id = context$analysis_id,

  n_samples = ncol(
    rpm_matrix
  ),

  n_miRNAs = nrow(
    rpm_matrix
  ),

  n_analyses = length(
    contrasts
  ),

  RPM_role =
    "supportive non-parametric evidence",

  primary_count_methods =
    "edgeR-TMM; DESeq2",

  primary_count_model =
    "unadjusted",

  sensitivity_model =
    "age + sex",

  direction_requirement =
    "required for pairwise concordance; not applicable to Phenotype_global",

  no_composite_score =
    TRUE,

  historical_candidate_list_used =
    FALSE,

  integrated_visualization_matrix =
    "log2(RPM + 1)",

  visualization_interpretation =
    "post-selection exploratory only",

  stringsAsFactors = FALSE
)


utils::write.csv(
  manifest,
  prepare_output_file(
    file.path(
      integrated_results_dir,
      "integrated_manifest.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 17. FINAL QC / AUDIT
# ==============================================================================

final_qc <- data.frame(

  analysis_id = context$analysis_id,

  n_samples = ncol(
    rpm_matrix
  ),

  n_NIA = sum(
    metadata$Phenotype ==
      "NIA"
  ),

  n_Mild = sum(
    metadata$Phenotype ==
      "Mild"
  ),

  n_Severe = sum(
    metadata$Phenotype ==
      "Severe"
  ),

  n_miRNAs = nrow(
    rpm_matrix
  ),

  n_contrasts = length(
    contrasts
  ),

  integrated_long_rows = nrow(
    integrated_evidence_long
  ),

  expected_integrated_long_rows =
    expected_long_rows,

  complete_grid_valid = (
    nrow(
      integrated_evidence_long
    ) ==
      expected_long_rows
  ),

  adjusted_age_sex_available =
    adjusted_available,

  n_count_nominal_concordant = nrow(
    candidates_count_nominal_concordant
  ),

  n_all_three_nominal_concordant = nrow(
    candidates_all_three_nominal
  ),

  n_primary_FDR_supported = nrow(
    candidates_primary_FDR_supported
  ),

  n_primary_FDR_cross_supported = nrow(
    candidates_primary_FDR_cross_supported
  ),

  n_age_sex_robust_FDR = nrow(
    candidates_age_sex_robust_FDR
  ),

  n_primary_robust = sum(
    downstream_candidate_priority$downstream_category ==
      "Primary_robust"
  ),

  n_secondary_integrated = sum(
    downstream_candidate_priority$downstream_category ==
      "Secondary_integrated"
  ),

  n_downstream_carried_forward = nrow(
    downstream_candidate_priority
  ),

  historical_candidate_list_used =
    FALSE,

  samples_removed_by_script =
    0L,

  miRNAs_removed_by_script =
    0L,

  stringsAsFactors = FALSE
)


utils::write.csv(
  final_qc,
  prepare_output_file(
    file.path(
      integrated_results_dir,
      "06_final_QC_summary.csv"
    )
  ),
  row.names = FALSE
)


# ==============================================================================
# 18. REPRODUCIBILITY
# ==============================================================================

write_session_info(
  results_dir
)


message(
  ""
)

message(
  "============================================================"
)

message(
  "06 complete — integrated RPM / edgeR / DESeq2 evidence."
)

message(
  "Analysis: ",
  context$analysis_id
)

message(
  "Samples: ",
  ncol(
    rpm_matrix
  )
)

message(
  "NIA / Mild / Severe: ",
  sum(
    metadata$Phenotype ==
      "NIA"
  ),
  " / ",
  sum(
    metadata$Phenotype ==
      "Mild"
  ),
  " / ",
  sum(
    metadata$Phenotype ==
      "Severe"
  )
)

message(
  "Integrated miRNAs: ",
  nrow(
    rpm_matrix
  )
)

message(
  "Count-method nominal concordance: ",
  nrow(
    candidates_count_nominal_concordant
  )
)

message(
  "RPM + edgeR + DESeq2 nominal concordance: ",
  nrow(
    candidates_all_three_nominal
  )
)

message(
  "Primary count-method FDR support: ",
  nrow(
    candidates_primary_FDR_supported
  )
)

message(
  "Primary FDR with cross-method nominal support: ",
  nrow(
    candidates_primary_FDR_cross_supported
  )
)

message(
  "FDR evidence robust after age + sex adjustment: ",
  nrow(
    candidates_age_sex_robust_FDR
  )
)

message(
  ""
)

message(
  "Top integrated evidence:"
)

print(
  utils::head(
    candidate_summary_all[
      ,
      c(
        "miRNA",
        "evidence_class",
        "n_RPM_nominal",
        "n_count_nominal_both",
        "n_all_three_nominal",
        "n_count_FDR_cross_supported",
        "n_count_FDR_both",
        "n_FDR_cross_supported_robust_same_contrast",
        "minimum_RPM_p",
        "minimum_edgeR_FDR",
        "minimum_DESeq2_FDR"
      ),
      drop = FALSE
    ],
    20L
  )
)

message(
  ""
)

message(
  "No historical candidate list was used."
)

message(
  "Final downstream hierarchy: ",
  sum(
    downstream_candidate_priority$downstream_category ==
      "Primary_robust"
  ),
  " Primary_robust + ",
  sum(
    downstream_candidate_priority$downstream_category ==
      "Secondary_integrated"
  ),
  " Secondary_integrated = ",
  nrow(
    downstream_candidate_priority
  ),
  " carried-forward miRNAs."
)

message(
  "No new p-values or composite normalization/evidence scores were created."
)

message(
  "Integrated PCA/heatmaps are post-selection exploratory visualizations."
)

message(
  "No samples or miRNAs were removed by script 06."
)

message(
  "============================================================\n"
)
